hubmapconsortium/portal-ui

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/proposal.md
CHANGELOG.md

- I feel ok with leaving out the body templates: If I'm a good person, I'll be sufficiently precise without the paperwork, and if I'm not, then it won't help.
- Does this feel like the right set of top-level types? I feel like making a distinction between an actionable "enhancement" and a "proposal" that needs buy-in is useful. Thoughts?

new issue templates

---

README.md

Work is being spread across a number of repos, so I think there should be some roadmap of how things interrelate, without being buried in details.

Diagram related repos

---

CHANGELOG.md
context/app/static/js/App.jsx

John conroy/fix alerts conditional

---

CHANGELOG.md
context/app/static/js/App.jsx
context/app/static/js/components/Details.jsx
context/app/static/js/components/ProvTable.jsx
context/app/static/js/components/ProvTypesList.jsx
context/app/static/js/components/VisTabs.jsx
context/app/templates/pages/search.html

Towards #249 . There's more to be done, but I want to get this in so @ilan-gold can merge the vitessce changes.

John conroy/improve provenance

---

CHANGELOG.md
context/app/static/js/components/Search/Search.jsx

Tiffany, it looks like this right now... which may not be what we want for the long term? I don't know.
If you don't see big problems, I'd suggest approving, and filing a follow-up issue for yourself, if necessary.

Sort by last modified. Fix #272

---

CHANGELOG.md
context/app/templates/pages/base_react.html

Add favicon to react page template

---

CHANGELOG.md
context/app/static/js/components/Home.jsx

Adding the requested call to action to the home page for the demo.

John conroy/home page call to action

---

CHANGELOG.md
context/app/static/js/components/Detail/ProvTable.jsx

Fix conditional logic in provenance table to stop creating links to derived donors.

John conroy/fix prov table derived links

---

CHANGELOG.md
context/app/static/js/components/DatasetDetail.jsx
context/app/static/js/components/Detail/Visualization.jsx

John conroy/update visualization section

---

CHANGELOG.md
context/app/static/js/components/Detail/Summary.jsx

John conroy/uniform section padding

---

CHANGELOG.md
context/app/static/js/components/Detail/FileTable.jsx

John conroy/increase files table height

---

CHANGELOG.md
context/app/static/js/components/SampleDetail.jsx

John conroy/fix sample organ logic

---

CHANGELOG.md
context/app/static/js/components/DatasetDetail.jsx
context/app/static/js/components/Detail/DagProv.jsx

A temporary component to demonstrate dag data structure.

John conroy/temporary dag provenance

---

CHANGELOG-avoid-merge-conflicts.md
README.md
push.sh
test.sh

Fix #332. Inspired by, but simpler than, the pattern John linked to. Explanation of changes is in README. Does this seem like good idea to people?

Build changelog from individual files to avoid merge conflicts

---

CHANGELOG-update-detail-attribution.md
context/app/static/js/components/Detail/Attribution.jsx

Updates detail attribution per v2 design.

John conroy/update detail attribution

---

CHANGELOG-uniform-width.md
CHANGELOG-uniform-widths.md
context/app/static/js/App.jsx
context/app/static/js/Header.jsx
context/app/static/js/components/Detail/DetailLayout.jsx
context/app/static/js/components/Home.jsx
context/app/static/js/components/Search/Search.jsx

John conroy/uniform width

---

CHANGELOG-metadata-table-description-as-column.md
context/app/static/js/components/Detail/MetadataTable.jsx

John conroy/metadata table description as column

---

CHANGELOG-webpack-cleanup.md
context/build-utils/webpack.common.js
context/package-lock.json
context/package.json

The plugin cleans the public directory before each build.

John conroy/webpack cleanup

---

CHANGELOG-update-field-descriptions.md

@tsliaw : At some point you said you were having trouble getting the submodules... Are things working for you now?

Pull latest field descriptions

---

CHANGELOG-prettier-react.md
context/.eslintrc.yml
context/app/static/js/components/Detail/ProvTable.jsx

Fixes additional eslint and prettier conflicts. You should now be able to use prettier IDE plugins without issue.

John conroy/prettier react

---

CHANGELOG-push-nl.md
push.sh

fix log concatenation

---

CHANGELOG-index-config.md
context/app/api/client.py
context/app/default_config.py
context/app/routes_main.py
context/app/templates/pages/ccf-eui.html

Config: Support search endpoints. Fix #411

---

.gitignore
CHANGELOG-fix-viz-table-of-contents.md
context/app/static/js/components/Detail/Dataset/Dataset.jsx

John conroy/fix viz table of contents

---

CHANGELOG-free-text-search.md
context/app/static/js/components/Search/Search.jsx
context/app/static/js/components/Search/SearchWrapper.jsx

Fix #344. @tsliaw : I think you had found the search-on-keypress distracting, so I've turned that off. I'll file a follow-up issue in search-api for the next steps.

Towards free-text search

---

.gitignore
CHANGELOG.md
README.md
example-app.conf

While trying to set up the development environment just now I noticed that some of the paths in the readme were out of date / incomplete.

Update paths in README

---

CHANGELOG-index-routing.md
context/app/default_config.py
example-app.conf

I'll follow up on this and start looking at the `portal` index, now that it's available.

index routing

---

CHANGELOG-welcome.md
context/app/routes_main.py

Unless there's a different plan?

Add "Welcome"

---

CHANGELOG-no-login-for-ccf.md
context/app/routes_main.py

@bherr2 : When you've pushed a version to the CDN that should accommodate this, let me know here, and I'll run the portal locally to check, and then merge. Thanks!
Fix #466.

No login required for CCF

---

CHANGELOG-mailto.md
context/app/static/js/components/Home/DataUseGuidelines/DataUseGuidelines.jsx

Add mailto link on homepage.

---

CHANGELOG-last-modified.md
context/app/static/js/components/Search/config.js

Add last modified column to search results

---

CHANGELOG-searchkit-css.md
context/app/static/js/components/Search/Search.css
context/app/static/js/components/Search/Search.jsx
context/app/static/js/components/Search/Search.scss
context/app/static/js/index.css

Fix #287. @tsliaw : Let me know if you need anything else as you get into styling the search pages.

Allow SK SCSS overrides

---

CHANGELOG-download-metadata-table.md
context/app/static/js/components/Detail/Dataset/Dataset.jsx
context/app/static/js/components/Detail/MetadataTable/MetadataTable.jsx
context/app/static/js/components/Detail/MetadataTable/style.js
context/app/static/js/helpers/__tests__/tableToDelimitedString.spec.js
context/app/static/js/helpers/functions.js

I believe this is a situation where `React.memo()` makes sense.

John conroy/download metadata table

---

CHANGELOG-login-button-hover.md
context/app/static/js/components/Header/LoginButton/style.js

John conroy/login button hover

---

CHANGELOG-basic-collections.md
context/app/routes_main.py
context/app/static/js/components/Collections/Card/Card.jsx
context/app/static/js/components/Collections/Card/index.js
context/app/static/js/components/Collections/Card/style.js
context/app/static/js/components/Collections/Collections/Collections.jsx
context/app/static/js/components/Collections/Collections/index.js
context/app/static/js/components/Collections/index.js
context/app/static/js/components/Header/Header/Header.jsx
context/app/static/js/components/Header/Menu/Menu.jsx
context/app/static/js/components/Routes.jsx
context/app/static/js/index.jsx

Basic collections page to demonstrate api response. I didn't follow usual conventions for organizing components because they will likely be deleted shortly.

John conroy/basic collections

---

CHANGELOG-fix-home-page-data.md
context/app/static/js/components/Home/BarChart/BarChart.jsx

Fixes the issue of dummy data being displayed before real data.

John conroy/fix home page data

---

CHANGELOG-fix-safari-vitessce.md
context/package-lock.json
context/package.json

@mccalluc Do you know what the error on Travis means?

Update vitessce to fix safari bugs.

---

CHANGELOG-no-results.md
context/app/static/js/components/Search/Search.jsx
context/app/static/js/components/Search/SearchWrapper.jsx

Fix #514. @tsliaw : Does this seem sufficient to you? Do you think there's anything else we should say?

More help if no search results.

---

context/app/markdown/docs/metadata.md

Melissa Schwenk will come through and add the appropriate links to the .md pages once those are imported / set up in GitHub.  @mccalluc - heads up as we may need your help creating or importing the md docs.

Removed G-Docs, added placeholder for .md URLs

---

CHANGELOG-cell-type-annotation-showcase.md
context/app/showcase/satija.md
context/app/static/js/components/Header/ShowcaseLinks/ShowcaseLinks.jsx

This adds a new showcase http://localhost:5001/showcase/satija

Cell type annotation showcase

---

CHANGELOG-lookup-ancestor.md
context/app/static/js/components/Search/AncestorNote.jsx
context/app/static/js/components/Search/Search.jsx
context/app/static/js/components/Search/SearchWrapper.jsx
context/app/static/js/helpers/LookupEntity.jsx

- Fix #517: add explanatory note on constrained search results.
- Get rid of the old, uninformative filter button.
- Introduce `LookupEntity`: Given a UUID, queries ES and pass the result to a child element via the `entity` prop.

Describe constrained searches better

---

context/app/markdown/docs.md
context/app/markdown/docs/help.md

Replace PR #615, which had merge conflicts.

Help doc from Chris

---

context/app/markdown/docs/metadata.md

Fill in missing links

---

context/app/markdown/docs/help.md

Added images to How to sections.

Update help.md with images

---

CHANGELOG-provvis-bug-fix.md
context/app/static/js/components/Detail/ProvGraph/ProvGraph.jsx

Fix bugs in Prov Vis click handling: Fix #650, Fix #642

Fix provvis bugs

---

CHANGELOG-donor-metadata-everywhere.md
context/app/static/js/components/Search/config.js

Towards #671 , but does not provide any organization for the facet list.

Add donor facets

---

CHANGELOG-entity-counts-order.md
context/app/static/js/components/Home/DataSummary/DataSummary.jsx

John conroy/entity counts order

---

CHANGELOG-fix-prov-table-duplication.md
context/app/static/js/components/Detail/ProvTable/ProvTable.jsx

John conroy/fix prov table duplication

---

CHANGELOG-fix-prov-table-order.md
context/app/static/js/components/Detail/ProvTable/ProvTable.jsx

Temporary fix until a more permanent solution can be found. Fixes #669

John conroy/fix prov table order

---

CHANGELOG-markdown-content.md
context/app/showcase/satija.md

This is the description I received from the Satija Lab

Update showcase description

---

context/app/markdown/docs/assay/seqfish.md

Added reference links to the source of images in Figures 3 & 4:
(Images provided by The Cai Lab)(http://singlecell.caltech.edu/research/index.html)

Update seqFISH.md added reference links

---

CHANGELOG-globus-link.md
context/app/static/js/components/Detail/GlobusLink/GlobusLink.jsx

use same variable everwhere / desctructuring. Fix #754.
@tsliaw : Code review, and sanity check that that the UI change is good.

Change globus link text to "Download from Globus"

---

CHANGELOG-fix-login-button.md
context/app/static/js/components/Header/LoginButton/LoginButton.jsx
context/app/static/js/components/Header/LoginButton/style.js
cypress-etc/cypress/integration/portal-ui.spec.js

Fixes #761 . I switched to using `text-transform: capitalize` instead of capitalizing the string itself and had to change the cypress test as a result. Let me know if you have a preference.

John conroy/fix login button

---

CHANGELOG-lazy-home-viz.md
CHANGELOG-lazy-vitessce.md
context/.babelrc
context/app/static/js/components/Detail/Dataset/Dataset.jsx
context/app/static/js/components/Detail/Visualization/style.js
context/app/static/js/components/Detail/VisualizationWrapper/VisualizationWrapper.jsx
context/app/static/js/components/Detail/VisualizationWrapper/index.js
context/app/static/js/components/Detail/VisualizationWrapper/style.js
context/app/static/js/components/Home/Home/Home.jsx
context/app/static/js/components/Home/Home/style.js
context/app/static/js/components/Showcase/Showcase.jsx
context/build-utils/webpack.common.js
context/package-lock.json
context/package.json

Dynamically import home page visualization (including vega/associated packages) component and display circular progress indicator as fallback.

John conroy/lazy home viz

---

CHANGELOG-lazy-home-viz.md
CHANGELOG-lazy-vitessce.md
CHANGELOG-split-bundle-vendors.md
context/.babelrc
context/app/static/js/components/Detail/Dataset/Dataset.jsx
context/app/static/js/components/Detail/Visualization/style.js
context/app/static/js/components/Detail/VisualizationWrapper/VisualizationWrapper.jsx
context/app/static/js/components/Detail/VisualizationWrapper/index.js
context/app/static/js/components/Detail/VisualizationWrapper/style.js
context/app/static/js/components/Home/Home/Home.jsx
context/app/static/js/components/Home/Home/style.js
context/app/static/js/components/Showcase/Showcase.jsx
context/app/templates/pages/base.html
context/app/templates/pages/base_react.html
context/build-utils/webpack.common.js
context/package-lock.json
context/package.json

Splits all shared node modules into own entry chunk named `vendors.bundle.js`. The main bundle has been renamed `main.bundle.js`.

John conroy/split bundle vendors

---

CHANGELOG-fix-entity-tile-colors.md
context/app/static/js/components/Detail/EntityTile/EntityTile.jsx
context/app/static/js/components/Detail/EntityTile/style.js

Fixes #741. Also changes the icon color of regular tiles from black to primary purple.

John conroy/fix entity tile colors

---

CHANGELOG-dua.md
context/app/static/js/components/Home/DataUseGuidelines/DataUseGuidelines.jsx

Policy group requested changes to wording.

Update homepage DUA. Fix #788.

---

CHANGELOG-fix-entity-tile-style.md
context/app/static/js/components/Detail/ProvTableDerivedLink/ProvTableDerivedLink.jsx
context/app/static/js/components/Detail/ProvTableDerivedLink/style.js
context/app/static/js/components/Detail/ProvTableTile/ProvTableTile.jsx
context/app/static/js/components/entity-tile/EntityTile/EntityTile.jsx
context/app/static/js/components/entity-tile/EntityTile/style.js
context/app/static/js/components/entity-tile/EntityTileBottom/EntityTileBottom.jsx
context/app/static/js/components/entity-tile/EntityTileBottom/style.js
context/app/static/js/components/entity-tile/EntityTileTop/EntityTileTop.jsx
context/app/static/js/components/entity-tile/EntityTileTop/style.js
context/app/static/js/components/entity-tile/EntityTileTopText/EntityTileTopText.jsx
context/app/static/js/components/entity-tile/EntityTileTopText/style.js
context/app/static/js/theme.jsx

Fixes and simplifies styles for entity tile components.

John conroy/fix entity tile style

---

CHANGELOG-update-globus-link.md
context/app/static/js/components/Detail/Dataset/Dataset.jsx
context/app/static/js/components/Detail/Files/Files.jsx
context/app/static/js/components/Detail/GlobusLink/GlobusLink.jsx
context/app/static/js/components/Detail/GlobusLink/style.js
context/app/static/js/components/Detail/GlobusLinkMessage/GlobusLinkMessage.jsx
context/app/static/js/components/Detail/GlobusLinkMessage/index.js
context/app/static/js/components/Detail/GlobusLinkMessage/style.js
context/app/static/js/shared-styles/icons/index.js
context/app/static/js/shared-styles/surfaces/index.js

John conroy/update globus link

---

push.sh

@ilan-gold / @john-conroy / @tsliaw : I'm going to self-merge this before I make the image for the next version, but I want to let you know about a small change in the release process.

update submodules *after* making image, not before

---

CHANGELOG-prov-table-dataset-chevron.md
context/app/static/js/components/Detail/ProvTable/ProvTable.jsx
context/app/static/js/components/Detail/ProvTableTile/ProvTableTile.jsx

John conroy/prov table dataset chevron

---

CHANGELOG-ccf-docs-link.md
context/app/markdown/docs.md

If either of you had something else in mind, please revise as you see fit.

link to CCF docs. Fix #865

---

CHANGELOG-satija-data-version.md
context/app/preview/satija.md

I received updated cell set annotations, this updates the JSON file URLs to point to the updated processed files.

Satija showcase data version bump

---

CHANGELOG-dataset-tile-descendant-counts.md
context/app/static/js/components/Detail/ProvTableTile/ProvTableTile.jsx

John conroy/dataset tile descendant counts

---

CHANGELOG-json-icon.md
context/app/static/js/components/Detail/Summary/Summary.jsx
context/app/static/js/components/Detail/Summary/style.js
context/app/static/js/components/Detail/SummaryData/SummaryData.jsx
context/app/static/js/components/Detail/SummaryData/index.js
context/app/static/js/components/Detail/SummaryData/style.js
context/app/static/js/components/Detail/SummaryItem.jsx
context/app/static/js/shared-styles/icons/index.js

John conroy/json icon

---

CHANGELOG-upgrade-vitessce-019.md
context/app/api/vitessce.py
context/app/routes_main.py
context/package-lock.json
context/package.json

If you want to test locally (any, some, or all - up to you):
MALDI: http://localhost:5001/browse/dataset/d66b802cbc2e8e83e84803f75d31bfcd
CODEX: http://localhost:5001/browse/dataset/63a35af025a3662cb368eb3999fe2948
MxIF: http://localhost:5001/browse/dataset/ac5d138c88d83b3cb80a4c42d36b05e2
PAS: http://localhost:5001/browse/dataset/2ce183e38a31ff1d836675d3b75654b0
SCRNA-seq: http://localhost:5001/browse/dataset/18c14ef9165c978a14256674158cc181
The IMS stuff is because these images have no data types except "image pyramid" so this (for now) is my best attempt at giving some sort of good configuration for them.

Upgrade vitessce 0.1.10

---

CHANGELOG-latest-protocol.md
context/app/static/js/components/Detail/Protocol/Protocol.jsx
context/app/static/js/hooks/useProtocolData.js

Example : `browse/donor/c624abbe9836c7e3b6a8d8216a316f30`
@tsliaw you can also make a GET at `https://www.protocols.io/api/v3/protocols/7hhhj36?last_version=1` to see what other protocol data is available.

John conroy/latest protocol

---

CHANGELOG-preview-descriptions.md
context/app/static/js/components/Preview/Preview.jsx
context/app/static/js/components/Preview/style.js

Implements: https://www.figma.com/file/ejCWSUFHyIGY900cZZ8Jgl/Previews?node-id=48%3A441
The spacing is a little more generous, but that is true not only for this little addition but for the rest of the page as well.
Fixes #907.

Preview description

---

CHANGELOG-preview-titles.md
context/app/preview/cell-type-annotations.md
context/app/preview/multimodal-molecular-imaging-data.md

Minor updates to previews

---

CHANGELOG-footer-citation-link.md
context/app/static/js/components/Footer/Footer.jsx

John conroy/footer citation link

---

CHANGELOG-collections-description.md
context/app/static/js/components/Collections/Collections/Collections.jsx
context/app/static/js/components/Collections/Collections/style.js
context/app/static/js/components/Detail/Description/Description.jsx
context/app/static/js/components/Detail/Description/index.js
context/app/static/js/components/Detail/Description/style.js
context/app/static/js/components/Detail/SectionContainer.jsx
context/app/static/js/components/Preview/Preview.jsx
context/app/static/js/components/Preview/style.js

Fix #944. Also slightly increases spacing between sections on entity detail pages.

John conroy/collections description

---

CHANGELOG-display-access-level.md
context/app/static/js/components/Detail/Dataset/Dataset.jsx
context/app/static/js/components/Detail/Summary/Summary.jsx
context/app/static/js/components/Detail/SummaryData/SummaryData.jsx

John conroy/display access level

---

CHANGELOG-wrap-on-safari.md
context/app/static/js/components/Search/style.js

Fix results wrapping on safari

---

CHANGELOG.md

Explanation of what went wrong: I'll self merge, and try to stick to the procedure in the future.

My apologies

---

CHANGELOG-fix_963_sprm.md
context/app/api/vitessce.py
context/package-lock.json
context/package.json

Fixes #963: see the issue for testing this PR.  Beyond that, no other Vitessce changes should be noticeable.

Only Show Imaging in SPRM When There are no Segmentations

---

CHANGELOG-webpack-less-verbose.md
context/package.json

John conroy/webpack less verbose

---

CHANGELOG-webpack-dev-less-verbose.md
context/package.json

The previous PR #979 did not resolve the issue, we're running `dev-start` in travis.. Fix #974 .

John conroy/webpack dev less verbose

---

CHANGELOG-dockerfile-reorder.md
context/Dockerfile

Reorder Dockerfile to improve caching

---

CHANGELOG-977_fix.md
context/app/api/vitessce.py
context/package-lock.json
context/package.json

Fixes #978 and #977 
I know you opened #982 and #985 @mccalluc, which goes somewhat against what I have here, so I will handle that tomorrow.  There are some deeper fixes that I could put into it.  Thanks for being on top of this.
Using the PROD conf I sent yesterday, you should be able to see:
http://localhost:5001/browse/dataset/912889b51fed4ac4fdf2d4d3c5550f72
http://localhost:5001/browse/dataset/46a69f99d8793f9ddf8ee4a1dba5d0e3
for example.
Nothing else should change.

Upgrade and handle IMC.

---

CHANGELOG-fallback-search.md
context/app/static/js/components/Search/Search.jsx
context/app/static/js/components/Search/config.js

Let unqualified "/search" work

---

CHANGELOG-status-icon-test.md
context/app/static/js/components/Detail/StatusIcon/StatusIcon.spec.js

Add test for status icon component.

John conroy/status icon test

---

context/CHANGELOG-donor-metadata-tests.md
context/app/static/js/components/Detail/DonorMetadata/DonorMetadata.jsx
context/app/static/js/components/Detail/DonorMetadata/DonorMetadata.spec.js

Add tests for donor metadata component.

John conroy/donor metadata tests

---

CHANGELOG-detail-summary-tests.md
CHANGELOG-status-icon-test.md
context/app/static/js/components/Detail/StatusIcon/StatusIcon.spec.js
context/app/static/js/components/Detail/Summary/Summary.jsx
context/app/static/js/components/Detail/Summary/Summary.spec.js
context/app/static/js/components/Detail/SummaryData/SummaryData.spec.js

Add tests for summary component.

John conroy/detail summary tests

---

CHANGELOG-detail-summary-data-tests.md
CHANGELOG-detail-summary-tests.md
CHANGELOG-status-icon-test.md
context/app/static/js/components/Detail/StatusIcon/StatusIcon.jsx
context/app/static/js/components/Detail/StatusIcon/StatusIcon.spec.js
context/app/static/js/components/Detail/Summary/Summary.jsx
context/app/static/js/components/Detail/Summary/Summary.spec.js
context/app/static/js/components/Detail/SummaryData/SummaryData.jsx
context/app/static/js/components/Detail/SummaryData/SummaryData.spec.js

Adds basic tests to `SummaryData` component for entity detail pages.

John conroy/detail summary data tests

---

CHANGELOG-safari-esc-hack.md
context/app/static/js/components/Detail/Visualization/Visualization.jsx

Hack for full-screen safari w/ full-window vitessce

---

CHANGELOG-markdown-bottom-margin.md
context/app/static/js/components/Markdown/style.js
context/app/static/js/components/Preview/style.js

Add bottom margin

---

context/app/api/CHANGELOG-seqfish.md
context/app/api/test_vitessce.py
context/app/api/vitessce.py

This updates the view configuration for seqFish so that hybridization cycles with a given position can be overlaid, as is suggested by the data.  To test go to http://localhost:5001/browse/dataset/38d0c2dc36f512ac54a5a62318033ecb on TEST

seqFish Vitessce Display

---

CHANGELOG-no-401s-on-public-data.md
context/app/api/client.py

No empty Authorization headers

---

CHANGELOG-fix-null-token.md
context/app/static/js/components/files/FileBrowserFile/FileBrowserFile.jsx
context/app/static/js/components/files/GlobusLink/GlobusLink.jsx
context/app/static/js/helpers/LookupEntity.jsx
context/app/static/js/helpers/functions.js
context/app/static/js/hooks/useEntityData.js

Fix #1085. Created #1086 to cleanup requests code.

John conroy/fix null token

---

CHANGELOG-no-donor-group-for-datasets.md
context/app/static/js/components/Search/config.js

Use group of entity, not parent donor

---

.travis.yml
CHANGELOG-submodules.md
README.md
dev-start.sh

Check that submodules are being pulled

---

CHANGELOG-mapped-bar-chart-labels.md
context/app/static/js/components/Home/BarChart/BarChart.jsx

John conroy/mapped bar chart labels

---

CHANGELOG-route.md
context/app/static/js/components/Header/HeaderAppBar/HeaderAppBar.jsx
context/app/static/js/components/Header/HeaderAppBar/style.js
context/app/static/js/components/Preview/Preview.jsx
context/app/static/js/components/Routes/Route.jsx
context/app/static/js/components/Routes/Routes.jsx

Add a wrapper component for a route and remove margin bottom from the header component.

John conroy/route

---

CHANGELOG-fix-login.md
context/app/static/js/components/Header/LoginButton/LoginButton.jsx
context/app/static/js/components/Header/LoginButton/LoginButton.spec.js

John conroy/fix login

---

CHANGELOG-search-bottom-margin.md
context/app/static/js/components/Search/Search.scss

Use two argument form for margin css

---

CHANGELOG-footer-link.md
context/app/static/js/components/Footer/Footer.jsx

Change link

---

CHANGELOG-increase-bar-chart-bars.md
context/app/static/js/components/Home/BarChart/BarChart.jsx

John conroy/increase bar chart bars

---

CHANGELOG-fix-donor-entity-tile-age.md
context/app/static/js/components/entity-tile/EntityTileTopText/EntityTileTopText.jsx

Update donor entity tile age field and get age unit from data.

John conroy/fix donor entity tile age

---

CHANGELOG-replace-tissue-location-ccf.md
context/app/static/js/components/Detail/SampleTissue/SampleTissue.jsx
context/app/static/js/components/Detail/SampleTissue/SampleTissue.spec.js
context/app/static/js/components/Detail/SectionItem.jsx

John conroy/replace tissue location ccf

---

CHANGELOG-fix-search-requests.md
context/app/static/js/helpers/LookupEntity.jsx

Can we just use `useEntityData` hook? They seem similar. I've also looked into using `react-query` which may simplify our data fetching.

John conroy/fix search requests

---

CHANGELOG-update-prov-analysis.md
context/app/static/js/components/Detail/ProvAnalysisDetails/ProvAnalysisDetails.jsx
context/app/static/js/components/Detail/ProvAnalysisDetails/ProvAnalysisDetails.spec.js
context/app/static/js/components/Detail/ProvAnalysisDetails/style.js
context/app/static/js/components/Detail/ProvAnalysisDetailsLink/ProvAnalysisDetailsLink.jsx
context/app/static/js/components/Detail/ProvAnalysisDetailsLink/ProvAnalysisDetailsLink.spec.js
context/app/static/js/components/Detail/ProvAnalysisDetailsLink/style.js
context/app/static/js/components/Detail/ProvAnalysisDetailsList/ProvAnalysisDetailsList.jsx
context/app/static/js/components/Detail/ProvAnalysisDetailsList/index.js

John conroy/update prov analysis

---

CHANGELOG-fix-home-data-summary-prop-type.md
context/app/static/js/components/Home/Home/Home.jsx

John conroy/fix home data summary prop type

---

CHANGELOG-fix-donor-metadata-download.md
context/app/static/js/components/Detail/Donor/Donor.jsx

John conroy/fix donor metadata download

---

CHANGELOG-fix-donor-metadata-anchor.md
context/app/static/js/components/Detail/Dataset/Dataset.jsx
context/app/static/js/components/Detail/DetailLayout/DetailLayout.jsx
context/app/static/js/components/Detail/DetailLayout/utils.js
context/app/static/js/components/Detail/Donor/Donor.jsx
context/app/static/js/components/Detail/MetadataTable/MetadataTable.jsx
context/app/static/js/components/Detail/Sample/Sample.jsx
context/app/static/js/components/Detail/utils.js

Fix #1158. Is it worth refactoring some of the repeated code in the entity detail pages?

John conroy/fix donor metadata anchor

---

CHANGELOG-fix-prov-data-hook.md
context/app/static/js/hooks/useProvData.js

- Fix headers in useProvData hook.

John conroy/fix prov data hook

---

CHANGELOG-dockerignore.md
context/.dockerignore

Images should be a bit smaller

Dockerignore

---

CHANGELOG-fix-vitessce-theme-switch.md
context/app/static/js/components/Detail/Visualization/Visualization.jsx

Fix #1208. Let me know if there is a more sensible solution and I'd be glad to implement it.

John conroy/fix vitessce theme switch

---

CHANGELOG-fix-prov-analysis-details-headers.md
context/app/static/js/components/Detail/ProvAnalysisDetails/ProvAnalysisDetails.jsx
context/app/static/js/components/Detail/ProvAnalysisDetails/ProvAnalysisDetails.spec.js

John conroy/fix prov analysis details headers

---

CHANGELOG-style-error-boundary.md
context/app/static/js/components/Routes/ErrorBoundary.jsx
context/app/static/js/components/Routes/index.js
context/app/static/js/pages/Error/Error.jsx
context/app/static/js/pages/Error/Error.spec.js
context/app/static/js/pages/Error/utils.js

John conroy/style error boundary

---

CHANGELOG-fix-metadata-table-short-circuit.md
context/app/static/js/components/Detail/Dataset/Dataset.jsx
context/app/static/js/components/Detail/Sample/Sample.jsx

John conroy/fix metadata table short circuit

---

CHANGELOG-header-elevation.md
context/app/static/js/components/Header/HeaderAppBar/HeaderAppBar.jsx

John conroy/header elevation

---

CHANGELOG-header-elevation.md
CHANGELOG-user-email-header.md
context/app/main.py
context/app/routes_auth.py
context/app/static/js/components/Header/Dropdown/Dropdown.jsx
context/app/static/js/components/Header/HeaderAppBar/HeaderAppBar.jsx
context/app/static/js/components/Header/HeaderContent/HeaderContent.jsx
context/app/static/js/components/Header/HeaderContent/style.js
context/app/static/js/components/Header/LoginButton/LoginButton.jsx
context/app/static/js/components/Header/LoginButton/LoginButton.spec.js
context/app/static/js/components/Header/LoginButton/style.js
context/app/templates/pages/base_react.html

Fix #1030. Fix #1178.
Should I check the status code for the get request or is this sufficient?

John conroy/user email header

---

CHANGELOG-fix-ancestor-link-color.md
context/app/static/js/components/Search/AncestorNote.jsx

John conroy/fix ancestor link color

---

.travis.yml
CHANGELOG-update-banner-styles.md
context/app/static/js/components/Detail/ProvSection/ProvSection.jsx
context/app/static/js/components/Detail/Visualization/Visualization.jsx
context/app/static/js/shared-styles/alerts/index.js
context/package-lock.json

Fix #1077. The screenshots below are only meant to demonstrate the styling, ignore the text.
Warning
Info
Error
Success

John conroy/update banner styles

---

CHANGELOG-fix-analysis-details-link-ext-bug.md
context/app/static/js/components/Detail/ProvAnalysisDetailsLink/ProvAnalysisDetailsLink.jsx
context/app/static/js/components/Detail/ProvAnalysisDetailsLink/ProvAnalysisDetailsLink.spec.js

Towards #1215. As noted in the issue, I will wait to close it until the slack thread is concluded. Does this work or would you prefer a regex solution?
Update: Fix #1215.

John conroy/fix analysis details link ext bug

---

CHANGELOG-fix-error-page-html-titles.md
context/app/main.py

Fix #1213. This should fix error page html titles for all flask registered error routes.

John conroy/fix error page html titles

---

CHANGELOG-fix-search-page-safari-bugs.md
context/app/static/js/components/Search/ResultsTable.jsx
context/app/static/js/components/Search/styleForTable.js

Fix #1091. Fix #1144.
Could you also take a look at the search page in safari to confirm the bugs are fixed?

John conroy/fix search page safari bugs

---

CHANGELOG-assay-types.md
context/app/static/js/pages/search/DevSearch.jsx

This exposes information I needed to map the assay types.

Add more information to dev-search

---

context/app/static/js/components/Collections/Panel/style.js
context/app/static/js/components/Detail/TableOfContents/TableOfContents.jsx
context/app/static/js/components/Detail/entityHeader/EntityHeader/EntityHeader.jsx
context/app/static/js/components/Detail/entityHeader/EntityHeader/index.js
context/app/static/js/components/Detail/entityHeader/EntityHeader/style.js
context/app/static/js/components/Detail/entityHeader/EntityHeader/utils.js
context/app/static/js/components/Detail/entityHeader/EntityHeader/utils.spec.js
context/app/static/js/components/Detail/entityHeader/EntityHeaderContent/EntityHeaderContent.jsx
context/app/static/js/components/Detail/entityHeader/EntityHeaderContent/EntityHeaderContent.spec.js
context/app/static/js/components/Detail/entityHeader/EntityHeaderItem/style.js
context/app/static/js/components/Detail/visualization/Visualization/Visualization.jsx
context/app/static/js/components/Detail/visualization/Visualization/style.js
context/app/static/js/components/Header/HeaderAppBar/HeaderAppBar.jsx
context/app/static/js/components/Header/HeaderAppBar/style.js
context/app/static/js/components/Search/styleForSidebar.js
context/app/static/js/components/Search/styleForTable.js
context/app/static/js/components/files/FileBrowserDirectory/style.js
context/app/static/js/components/files/FileBrowserFile/style.js
context/app/static/js/pages/Collections/style.js
context/app/static/js/pages/Dataset/Dataset.jsx
context/app/static/js/pages/Donor/Donor.jsx
context/app/static/js/pages/Home/style.js
context/app/static/js/pages/Sample/Sample.jsx
context/app/static/js/stores/useEntityStore.js
context/app/static/js/theme.jsx

Implementing suggestions from #1244. Fix #1246, fix #1252, add tests. 
@ilan-gold / @keller-mark there are a few changes to the visualization component.

John conroy/detail header suggestions

---

CHANGELOG-fix-entity-header-safari-bugs.md
context/app/static/js/components/Detail/entityHeader/EntityHeader/style.js

John conroy/fix entity header safari bugs

---

CHANGELOG-expand-headers-in-fullscreen.md
context/app/static/js/components/Detail/entityHeader/EntityHeaderContent/EntityHeaderContent.jsx
context/app/static/js/components/Header/Header/Header.jsx
context/app/static/js/components/Header/HeaderAppBar/HeaderAppBar.jsx

John conroy/expand headers in fullscreen

---

CHANGELOG-detail-header.md
CHANGELOG-fix-first-header-render.md
context/app/static/js/components/Detail/SummaryData/SummaryData.jsx
context/app/static/js/components/Detail/TableOfContents/TableOfContents.jsx
context/app/static/js/components/Detail/entityHeader/EntityHeader/EntityHeader.jsx
context/app/static/js/components/Detail/entityHeader/EntityHeaderItem/EntityHeaderItem.jsx
context/app/static/js/components/Header/Header/Header.jsx
context/app/static/js/stores/useEntityStore.js

Fix #1266, Fix #1269. Let me know if anything is unclear and you feel like we'd benefit from a comment or two. This should be the last batch of fixes for the subheader.

John conroy/fix first header render

---

CHANGELOG-fix-header-elevation-in-fullscreen.md
context/app/static/js/components/Header/Header/Header.jsx

John conroy/fix header elevation in fullscreen

---

CHANGELOG-links-in-md.md
context/app/static/js/components/Markdown/style.js
context/app/static/js/theme.jsx

blue links

---

CHANGELOG-update-home-page-title.md
context/app/routes_main.py
context/app/templates/pages/base_react.html

John conroy/update home page title

---

CHANGELOG-fix-ingest-git-url.md
context/app/static/js/components/ServiceStatusTable/ServiceStatusTable.jsx

Fix ingest URL

---

context/app/static/js/components/Search/DevResults/DevResults.jsx
context/app/static/js/components/Search/DevResults/index.js
context/app/static/js/components/Search/SearchWrapper.jsx
context/app/static/js/pages/search/DevSearch.jsx
context/app/static/js/pages/search/Search.jsx
context/app/static/js/stores/useSearchViewStore.js

Fixes dev search page following the changes to search.

John conroy/fix dev search

---

context/app/static/js/components/Search/TilesSortDropdown/TilesSortDropdown.jsx
context/app/static/js/components/Search/TilesSortDropdown/TilesSortDropdown.spec.js
context/app/static/js/components/Search/TilesSortDropdown/style.js
context/app/static/js/shared-styles/dropdowns/index.js

Fixes the dropdown ~~so that it doesn't display the selected option in its available options~~ and adds a few tests.

John conroy/fix and test tiles sort dropdown

---

CHANGELOG-show-gateway-url.md
context/app/static/js/components/ServiceStatusTable/hooks.js
context/app/static/js/pages/Services/Services.jsx

On status, show where api info comes from

---

CHANGELOG-dropdown-accessibility.md
context/app/static/js/components/Detail/visualization/Visualization/Visualization.jsx
context/app/static/js/components/Detail/visualization/Visualization/style.js
context/app/static/js/components/Search/TilesSortDropdown/TilesSortDropdown.jsx
context/app/static/js/components/Search/TilesSortDropdown/style.js
context/app/static/js/shared-styles/dropdowns/DropdownListbox/DropdownListbox.jsx
context/app/static/js/shared-styles/dropdowns/DropdownListbox/index.js
context/app/static/js/shared-styles/dropdowns/DropdownListbox/style.js
context/app/static/js/shared-styles/dropdowns/DropdownListboxOption/DropdownListboxOption.jsx
context/app/static/js/shared-styles/dropdowns/DropdownListboxOption/index.js
context/app/static/js/shared-styles/dropdowns/DropdownListboxOption/style.js
context/app/static/js/shared-styles/dropdowns/index.js

@mccalluc As we discussed, let me know if this seems on track. Passing in the child components and their props this way isn't the cleanest solution but we have challenges with the portal and needing to make minor adjustments to styles. 
@tsliaw do you want to take a look at both the sort dropdown in search's tile view and the visualization dropdown to make sure they work as you expect.
9db61adfc017670a196ea9b3ca1852a0 has a visualization with the dropdown.

John conroy/shared dropdown listbox component

---

CHANGELOG-styled-components-plugin.md
context/.babelrc
context/package-lock.json
context/package.json

Adds styled-components babel plugin for better debugging.
https://styled-components.com/docs/tooling#babel-plugin

John conroy/styled components plugin

---

CHANGELOG-fix-detail-summary-spacing.md
context/app/static/js/components/Detail/Summary/style.js

John conroy/fix detail summary spacing

---

context/app/static/js/components/files/FileBrowserDirectory/FileBrowserDirectory.jsx
context/app/static/js/components/files/FileBrowserFile/FileBrowserFile.spec.js
context/app/static/js/components/files/FileBrowserFile/style.js

Adds arrow icons to the file browser.

John conroy/file browser icons

---

context/app/static/js/components/files/FileBrowser/FileBrowser.spec.js
context/app/static/js/components/files/FileBrowserFile/FileBrowserFile.spec.js

Adds tests for the updated file browser with qa files.

John conroy/qa files tests

---

.github/workflows/portal-ci.yml
CHANGELOG-try-github-actions.md
docker.sh
test.sh

A work in progress, but I think this would be the general idea. We may have to modify `test.sh` and `portal-ci.yml` to make this work. Right now I'm just making `test.sh` flexible enough to run both github actions and travis.
I was getting the error below and had to remove the `tput` code from `docker.sh`.
```
tput: No value for $TERM and no -T specified
Error: Process completed with exit code 2.
```

John conroy/try GitHub actions

---

CHANGELOG-fix-github-actions-branch-check.md
test.sh

CI on master failed... the conditional in `test.sh` for whether to check for a changelog file was incorrect.

John conroy/fix GitHub actions branch check

---

CHANGELOG-z-index.md
context/app/static/js/components/Detail/entityHeader/EntityHeader/style.js
context/app/static/js/components/Detail/visualization/Visualization/style.js
context/app/static/js/components/Header/Dropdown/style.js
context/app/static/js/shared-styles/dropdowns/DropdownListbox/style.js
context/app/static/js/theme.jsx

Fix #1340.
- Not sure about the best names... Generally chose something based on the directory it's in, but they could probably be improved.
- Have not confirmed that each of these works in the browser.

centralize z-indexes

---

CHANGELOG-no-help.md
context/app/markdown/docs.md

Remove dead link

---

.github/workflows/portal-ci.yml
.travis.yml
CHANGELOG-remove-dev-server-from-ci.md
copy-app-conf.sh
dev-start.sh
test.sh

Fix #1387. Do we need to everything between lines 34-46 of `test.sh` or can we just run ./copy-app-conf.sh?

John conroy/remove dev server from ci

---

CHANGELOG-rm-vestigial-config.md
context/app/config.py
context/app/routes_main.py
context/app/test_routes_errors.py
context/app/test_routes_main.py

Remove config.py

---

CHANGELOG-no-submission.md
context/app/markdown/docs.md

Follow up to https://github.com/hubmapconsortium/portal-docs/pull/44

rm submission link

---

CHANGELOG-uwsgi-buffer.md
context/uwsgi.ini

Fix #1420... hopefully. Could make the buffer even larger. Could try to understand why the requests are large, too.

double uwsgi buffer

---

CHANGELOG-validation-warnings.md
context/app/static/js/index.jsx

Disable schema validation warnings

---

CHANGELOG-tutorial-changes.md
context/app/static/js/components/tutorials/DatasetSearchPrompt/DatasetSearchPrompt.jsx
context/app/static/js/components/tutorials/SearchDatasetTutorial/SearchDatasetTutorial.jsx
context/app/static/js/components/tutorials/TooltipProgressButton/TooltipProgressButton.jsx
context/app/static/js/components/tutorials/TooltipProgressButton/index.js
context/app/static/js/components/tutorials/TutorialTooltip/TutorialTooltip.jsx
context/app/static/js/components/tutorials/TutorialTooltip/style.js
context/app/static/js/shared-styles/buttons/index.js
context/app/static/js/stores/useSearchDatasetTutorialStore.js
context/app/static/js/theme.jsx

Fix #1413. Closing #1414 since we need to keep the tutorial controlled for the keydown listeners.
@mccalluc confirmed the animation is not present so no change needed there.

John conroy/tutorial changes

---

CHANGELOG-minor-math.md
push.sh

We need some kind of tweak between now and the next release... this might be making it more complicated than it needs to be.... could go back to doing it by hand, if this is getting to be too much.

minor version math

---

context/app/markdown/CHANGELOG.md

Increments changelog to match dockerhub version.

John conroy/increment changelog version

---

CHANGELOG-notes-on-design-process.md
README.md

Does this seem accurate and useful?

Notes on design process

---

CHANGELOG-spatial-dev-search.md
context/app/static/js/pages/search/DevSearch.jsx

Fix #1446.
(Replaces PR #1450 ... I accidental pushed another commit to that branch that carried it in the wrong direction.)

Fix / expand spatial dev-search facets

---

CHANGELOG-github-ci-fold.md
test.sh

Use github ci folding

---

CHANGELOG-collections-doi.md
context/app/static/js/pages/Collection/Collection.jsx
context/app/static/js/pages/Collection/style.js

Not sure about design here.
Fix #1449

Link to collections DOI URL; not sure about design

---

CHANGELOG-prune-props.md
context/app/static/js/components/Detail/provenance/ProvTabs/ProvTabs.jsx

unused, not listed in propTypes.

remove unused props

---

context/app/static/js/components/Detail/SaveEditEntityButton/SaveEditEntityButton.jsx
context/app/static/js/components/savedLists/EditSavedStatusButton/EditSavedStatusButton.jsx
context/app/static/js/components/savedLists/EditSavedStatusDialog/EditSavedStatusDialog.jsx
context/app/static/js/stores/useSavedEntitiesStore.js

Fix bug where you couldn't deselect a list.

John conroy/fix edit saved status

---

context/app/static/js/components/Detail/SaveEditEntityButton/SaveEditEntityButton.jsx
context/app/static/js/components/savedLists/CreateListDialog/CreateListDialog.jsx
context/app/static/js/components/savedLists/EditSavedStatusButton/EditSavedStatusButton.jsx
context/app/static/js/components/savedLists/EditSavedStatusDialog/EditSavedStatusDialog.jsx
context/app/static/js/components/savedLists/SaveToListDialog/SaveToListDialog.jsx
context/app/static/js/stores/useSavedEntitiesStore.js

Fix closing a few dialogs which remained open after submitting.

John conroy/fix closing dialogs

---

CHANGELOG-lightsheet.md

If this could be merged before the release, that'd be great. Thanks!

lightsheet

---

context/app/static/js/components/Detail/SaveEditEntityButton/SaveEditEntityButton.jsx
context/app/static/js/components/savedLists/CreateListDialog/CreateListDialog.jsx
context/app/static/js/components/savedLists/CreateListDialog/style.js
context/app/static/js/components/savedLists/EditListButton/EditListButton.jsx
context/app/static/js/components/savedLists/EditListButton/index.js
context/app/static/js/components/savedLists/EditListDialog/EditListDialog.jsx
context/app/static/js/components/savedLists/EditListDialog/index.js
context/app/static/js/components/savedLists/EditListDialog/style.js
context/app/static/js/components/savedLists/EditSavedStatusButton/EditSavedStatusButton.jsx
context/app/static/js/components/savedLists/EditSavedStatusDialog/EditSavedStatusDialog.jsx
context/app/static/js/components/savedLists/SaveToListDialog/SaveToListDialog.jsx
context/app/static/js/components/savedLists/listTextFields/index.js
context/app/static/js/pages/SavedList/SavedList.jsx
context/app/static/js/pages/SavedLists/SavedLists.jsx
context/app/static/js/shared-styles/formFields/index.js
context/app/static/js/shared-styles/icons/index.js
context/app/static/js/stores/useSavedEntitiesStore.js

Enables the user to edit a saved list's description and title from the list detail page. Refactor the text fields to be reusable across components.

John conroy/edit saved list

---

context/app/static/js/components/savedLists/SavedListScrollbox/SavedListScrollbox.jsx
context/app/static/js/components/savedLists/SavedListScrollbox/index.js
context/app/static/js/components/savedLists/SavedListScrollbox/style.js
context/app/static/js/pages/SavedLists/SavedLists.jsx
context/app/static/js/pages/SavedLists/style.js

The only actual change is adding a max height to the scroll box. The other changes are just from moving the component to its own file.

John conroy/my lists scrollbox max height

---

context/app/static/js/components/savedLists/CreateListDialog/CreateListDialog.jsx
context/app/static/js/components/savedLists/EditListDialog/EditListDialog.jsx
context/app/static/js/components/savedLists/SavedListScrollbox/SavedListScrollbox.jsx
context/app/static/js/components/savedLists/SavedListScrollbox/index.js
context/app/static/js/components/savedLists/SavedListScrollbox/style.js
context/app/static/js/pages/SavedLists/SavedLists.jsx
context/app/static/js/pages/SavedLists/style.js
context/app/static/js/shared-styles/DialogModal/DialogModal.jsx

I wrote the text myself so please let me know what you would like me to replace it with. Also made changes to reset the create list form fields on exit.

John conroy/enforce unique list titles

---

context/app/static/js/components/savedLists/CreateListDialog/CreateListDialog.jsx
context/app/static/js/components/savedLists/EditListDialog/EditListDialog.jsx
context/app/static/js/components/savedLists/EditSavedStatusButton/EditSavedStatusButton.jsx
context/app/static/js/components/savedLists/EditSavedStatusDialog/EditSavedStatusDialog.jsx
context/app/static/js/components/savedLists/SavedEntitiesTable/SavedEntitiesTable.jsx
context/app/static/js/components/savedLists/SavedEntitiesTableRow/SavedEntitiesTableRow.jsx
context/app/static/js/components/savedLists/SavedListPanel/SavedListPanel.jsx
context/app/static/js/components/savedLists/SavedListPanel/index.js
context/app/static/js/components/savedLists/SavedListScrollbox/SavedListScrollbox.jsx
context/app/static/js/components/savedLists/SavedListScrollbox/index.js
context/app/static/js/components/savedLists/SavedListScrollbox/style.js
context/app/static/js/pages/SavedList/SavedList.jsx
context/app/static/js/pages/SavedLists/SavedLists.jsx
context/app/static/js/pages/SavedLists/style.js
context/app/static/js/shared-styles/DialogModal/DialogModal.jsx
context/app/static/js/shared-styles/panels/index.js
context/app/static/js/stores/useSavedEntitiesStore.js

Converges the saved entities in each list into a single object instead of being separated by entity type to allow easier access at the cost of additional looping to determine count by type.

John conroy/undo separation of list entities by type

---

context/app/routes_main.py
context/app/static/js/components/App.jsx
context/app/static/js/components/Routes/Routes.jsx
context/app/static/js/components/savedLists/AddToList/AddToList.jsx
context/app/static/js/components/savedLists/AddToListItem/AddToListItem.jsx
context/app/static/js/components/savedLists/EditListButton/EditListButton.jsx
context/app/static/js/components/savedLists/EditListDialog/EditListDialog.jsx
context/app/static/js/components/savedLists/EditSavedStatusDialog/EditSavedStatusDialog.jsx
context/app/static/js/components/savedLists/SavedListMenuButton/SavedListMenuButton.jsx
context/app/static/js/components/savedLists/SavedListPanel/SavedListPanel.jsx
context/app/static/js/components/savedLists/SavedListScrollbox/SavedListScrollbox.jsx
context/app/static/js/components/savedLists/listTextFields/index.js
context/app/static/js/pages/SavedList/SavedList.jsx
context/app/static/js/stores/useSavedEntitiesStore.js
context/package-lock.json
context/package.json

Replaces list title as key with a uuid and uses uuid in url route.

John conroy/replace title key with

---

context/app/routes_main.py
context/app/static/js/components/App.jsx
context/app/static/js/components/Routes/Routes.jsx
context/app/static/js/components/savedLists/AddToList/AddToList.jsx
context/app/static/js/components/savedLists/AddToList/style.js
context/app/static/js/components/savedLists/AddToListItem/AddToListItem.jsx
context/app/static/js/components/savedLists/EditListButton/EditListButton.jsx
context/app/static/js/components/savedLists/EditListDialog/EditListDialog.jsx
context/app/static/js/components/savedLists/EditSavedStatusDialog/EditSavedStatusDialog.jsx
context/app/static/js/components/savedLists/SavedListMenuButton/SavedListMenuButton.jsx
context/app/static/js/components/savedLists/SavedListPanel/SavedListPanel.jsx
context/app/static/js/components/savedLists/SavedListScrollbox/SavedListScrollbox.jsx
context/app/static/js/components/savedLists/listTextFields/index.js
context/app/static/js/pages/SavedList/SavedList.jsx
context/app/static/js/stores/useSavedEntitiesStore.js
context/package-lock.json
context/package.json

Adds max height so overflow can be scrolled.

Set max height for add to list in dialogs

---

CHANGELOG-saved-list-fixes.md
context/app/static/js/components/Detail/DetailLayout/DetailLayout.jsx
context/app/static/js/components/savedLists/EditSavedStatusButton/EditSavedStatusButton.jsx
context/app/static/js/components/savedLists/EditSavedStatusDialog/EditSavedStatusDialog.jsx
context/app/static/js/components/savedLists/SavedEntitiesTable/SavedEntitiesTable.jsx

In addition to showing "You don't have any lists. To assign this [dataset/sample/donor] to one or more lists, create a list in My Lists.", I disabled the save button.
Fix #1526.
Fix #1527.
Fix #1529.

John conroy/saved list fixes

---

CHANGELOG-track-errors-in-ga.md
context/app/static/js/components/Routes/ErrorBoundary.jsx

John conroy/track errors in ga

---

CHANGELOG-disable-saving-collection.md
context/app/static/js/components/Detail/Summary/Summary.jsx
context/app/static/js/components/Detail/SummaryData/SummaryData.jsx
context/app/static/js/components/Routes/useSendWebVitals.js
context/app/static/js/pages/Collection/Collection.jsx

Disable saving collections to saved lists. Also fixes a prettier error introduced from an earlier code suggestion.

John conroy/disable saving collection

---

CHANGELOG-empty-saved-list-table.md
context/app/static/js/pages/SavedList/SavedList.jsx
context/app/static/js/pages/SavedList/style.js

I altered the text slightly since we're calling it 'My Saved Items' instead of 'My Saves List'. Let me know if I should change the text. Fix #1550.

John conroy/empty saved list table

---

CHANGELOG-my-lists-add-items-alert.md
context/app/static/js/components/savedLists/SaveToListDialog/SaveToListDialog.jsx
context/app/static/js/components/savedLists/SavedEntitiesTable/SavedEntitiesTable.jsx
context/app/static/js/pages/SavedLists/SavedLists.jsx

Fix #1551. Also disables the button when no lists are selected.

John conroy/my lists add items alert

---

CHANGELOG-fix-table-button-ui-shift.md
context/app/static/js/components/Detail/SampleTissue/SampleTissue.jsx
context/app/static/js/components/savedLists/SavedEntitiesTable/style.js

John conroy/fix table button UI shift

---

CHANGELOG-fix-prov-vis-react.md
context/app/static/js/components/Detail/provenance/ProvGraph/ProvGraph.jsx
context/app/static/js/components/Detail/provenance/ProvTabs/ProvTabs.jsx
context/app/static/js/components/Detail/provenance/ProvVis/ProvVis.jsx
context/app/static/js/components/Detail/provenance/ProvVis/__tests__/ProvVis.spec.js
context/app/static/js/components/Detail/provenance/ProvVis/index.js

Fix #154. Fix #1486. From my perspective everything looks and performs as it should, but you're much more familiar with the prov vis so it may be worth testing locally. The test in `ProvVis.spec.js` looks a little strange still, but probably not worth revisiting until we add more testing.

John conroy/fix prov vis react

---

CHANGELOG-my-lists-narrow.md
context/app/static/js/components/Header/Menu/Menu.jsx

Merge #1591 into this to make CI happy.

Add My Lists to narrow

---

CHANGELOG-software-link.md
context/app/static/js/components/Header/DocumentationLinks/DocumentationLinks.jsx

software link

---

CHANGELOG-prev-next.md
context/app/static/js/pages/search/DevSearch.jsx

not expecting to see any data for a while, but search-api will expose these fields: https://github.com/hubmapconsortium/search-api/issues/233

Add prev and next to dev-search

---

CHANGELOG-upgrade-commons.md
context/package-lock.json
context/requirements.txt

@ilan-gold - If you could do some manual QA, just to make sure the vitessce-config generation is working as expected, that would be good. Thanks!

upgrade commons

---

CHANGELOG-tidy-config.md
context/app/default_config.py
example-app.conf

I've had exactly the problem you had this morning. Sorry it's gotten untidy.

Tidy up config; remove vestigial ENTITY_API_TIMEOUT

---

CHANGELOG-donors-without-metadata.md
context/app/static/js/pages/Donor/Donor.jsx

John conroy/donors without metadata

---

CHANGELOG-weird-protocol-bug.md
context/app/static/js/components/Detail/Protocol/Protocol.jsx
context/app/static/js/hooks/useProtocolData.js

Slightly more robust to bad protocols urls

---

CHANGELOG-start-prov-with-donor-entity-node.md
context/app/static/js/components/Detail/provenance/ProvGraph/ProvGraph.spec.js
context/app/static/js/components/Detail/provenance/ProvVis/ProvData.js
context/package-lock.json

Fix #1609.
@tsliaw It seems that the first node will always be light purple. Is that fine or should we make it light green to match the other entity nodes?

John conroy/start prov with donor entity node

---

CHANGELOG-container-names.md
CHANGELOG-faster-deploy-schedule.md
CHANGELOG-fix-donor-prov.md
CHANGELOG-provenance-testing.md
CHANGELOG-start-prov-with-donor-entity-node.md
context/app/markdown/CHANGELOG.md
context/app/static/js/components/Detail/provenance/ProvGraph/ProvGraph.jsx
context/app/static/js/components/Detail/provenance/ProvGraph/ProvGraph.spec.js
context/app/static/js/components/Detail/provenance/ProvGraph/fixtures/donor_prov.js
context/app/static/js/components/Detail/provenance/ProvTabs/ProvTabs.jsx
context/app/static/js/components/Detail/provenance/ProvVis/ProvData.js
context/app/static/js/components/Detail/provenance/ProvVis/ProvVis.jsx
context/package-lock.json
context/package.json

For now we are reverting changes to remove donor registration node in provenance graphs on donor entity nodes. We'll keep the changes in effect for other entity types. I'll create an issue and add an item to the UI agenda in regards to thinking about the path forward. I probably didn't need to pass the `entity_type` down through all of the components and could have checked if `Object.keys(this.prov.activity).length === 1` instead, but this seems more sure. 
Donor
Sample
Also, merges changes missed from an error with `push.sh`.

John conroy/fix donor prov

---

CHANGELOG-commons.md
context/requirements.txt

bump commons.

---

CHANGELOG-prov-node-tooltip.md
context/app/static/js/components/Detail/provenance/NodeElement/NodeElement.jsx

Replacing the existing buggy tooltip.

John conroy/prov node tooltip

---

CHANGELOG-distinguish-page-node.md
CHANGELOG-prov-node-tooltip.md
context/app/static/js/components/Detail/provenance/NodeElement/NodeElement.jsx
context/app/static/js/components/Detail/provenance/NodeElement/index.js
context/app/static/js/components/Detail/provenance/NodeElement/style.js
context/app/static/js/components/Detail/provenance/ProvGraph/ProvGraph.jsx
context/app/static/js/components/Detail/provenance/ProvGraph/ProvGraph.spec.js
context/app/static/js/components/Detail/provenance/ProvGraph/style.js
context/app/static/js/components/Detail/provenance/ProvTabs/ProvTabs.jsx
context/app/static/js/components/Detail/provenance/ProvVis/ProvVis.jsx
context/app/static/js/stores/useProvenanceStore.js

Fix #1606.
I added some text to the detail pane to explain the asterisk. Please let me know if you have any thoughts as to what it should say.

John conroy/distinguish page node

---

CHANGELOG-collection-missing-doi.md
context/app/static/js/pages/Collection/Collection.jsx

Will ping @shirey to see if this is a data problem, or really a valid state... but it any case, it's there on prod now, so the page shouldn't error. Fix #1676.

handle missing doi_url

---

CHANGELOG-fix-login-prop-types.md
context/app/static/js/components/Header/Dropdown/Dropdown.jsx

Fix login prop types error

---

CHANGELOG-homepage-revision-route.md
context/app/routes_main.py
context/app/static/js/components/Routes/Routes.jsx
context/app/static/js/pages/Home/HomeRevision.jsx

Adding a temporary route for the home page revision.

John conroy/homepage revision route

---

CHANGELOG-filebrowser-proptype.md
context/app/static/js/components/files/FileBrowser/FileBrowser.jsx

Fix proptype error

---

CHANGELOG-attribution-lower.md
context/app/static/js/pages/Dataset/Dataset.jsx
context/app/static/js/pages/Donor/Donor.jsx
context/app/static/js/pages/Sample/Sample.jsx

Fix #1632. @tsliaw -- I'm not seeing a "Contributors" section ... Am I missing something obvious?

Move attribution to bottom

---

CHANGELOG-hide-nested-object.md
context/app/static/js/components/Detail/MetadataTable/MetadataTable.jsx

Fix #1694 (Follow-up from https://github.com/hubmapconsortium/search-api/pull/271 ... bigger story is about letting us find Donors and Samples with metadata in dev-search.)

Hide nested metadata

---

CHANGELOG-info-to-error.md
context/app/api/client.py
context/app/api/vitessce_confs/base_confs.py

- @ilan-gold : Can you confirm that all of these are in fact errors? Or if they aren't serious, or the false positive rate is too high, perhaps not needed?
- @shirey : Is there log monitoring in place? I think we would want to know if these were being hit... Can your log monitor aggregate errors and send them to us once a day, or something like that?

Louder python errors

---

context/app/static/js/components/home-revision/AssayTypeBarChartContainer/style.js
context/app/static/js/components/home-revision/AssayTypeBarChartContainer/utils.js

Do we want to check on something more specific than the presence of a single bracket? Wanted to avoid regex, but maybe we should be more restrictive.

John conroy/filter out processed datasets

---

CHANGELOG-fix-vis-lifting.md
context/app/api/client.py

Fix vis-lifting bug

---

context/app/static/js/components/home-revision/EntityCount/EntityCount.jsx
context/app/static/js/components/home-revision/EntityCount/index.js
context/app/static/js/components/home-revision/EntityCount/style.js
context/app/static/js/components/home-revision/EntityCounts/EntityCounts.jsx
context/app/static/js/components/home-revision/EntityCounts/index.js
context/app/static/js/components/home-revision/EntityCounts/style.js
context/app/static/js/pages/Home/HomeRevision.jsx
context/app/static/js/pages/Home/homeRevisionStyle.js
context/app/static/js/shared-styles/icons/index.js

[Design](https://www.figma.com/file/cEZdI2tOMByTBW8RQ2kuAm/Home-Page?node-id=555%3A1). No cells yet. I'm also using MUI's [skeleton](https://material-ui.com/components/skeleton/) for the first time. Again, I'd check this out locally on different screen sizes and maybe use responsive to check resizing.
desktop/laptop
desktop/laptop hover
mobile
This last layout is only visible on a narrow range of screen widths between mobile and desktop/laptop.

John conroy/home revision counts

---

CHANGELOG-upgrade-vitessce-018.md
context/package-lock.json
context/package.json

Upgrade Vitessce to 1.1.8

---

context/app/static/js/components/home-revision/Title/style.js
context/app/static/js/pages/Home/HomeRevision.jsx
context/app/static/js/pages/Home/homeRevisionStyle.js

Removes above the fold styling, so now whatever can fit will show and modifies spacing.
The spacing around the bar chart will be fixed in a later PR.

John conroy/remove above the fold styling

---

CHANGELOG-collections-contributors.md
context/app/static/js/pages/Collection/Collection.jsx

Fix #1755. Not sure whether there are mock-ups which should be changed to keep things in sync?

Relabel Collections "contributors"

---

CHANGELOG-fix-twitter-timeline-safari.md
context/app/static/js/pages/Home/homeRevisionStyle.js

John conroy/fix twitter timeline safari

---

CHANGELOG-darker-counts.md
context/app/static/js/components/Search/Search.scss

Facet counts as dark as labels

---

CHANGELOG-no-items-saved.md
context/app/static/js/components/savedLists/NoItemsSaved/NoItemsSaved.jsx
context/app/static/js/components/savedLists/NoItemsSaved/index.js
context/app/static/js/pages/SavedList/SavedList.jsx
context/app/static/js/pages/SavedLists/SavedLists.jsx

This is somewhat gratuitous, but noticed it doing the audit for Support.

Tidy up my-lists copy-and-paste

---

CHANGELOG-mylist-nan.md
context/app/static/js/components/savedLists/SavedListPanel/SavedListPanel.jsx

Show correct count for Support entities

---

CHANGELOG-dev-start.md
copy-app-conf.sh

Fix dev-start

---

CHANGELOG-fix-sprm-variables-label.md
context/app/api/vitessce_confs/base_confs.py
context/app/api/vitessce_confs/fixtures/output_expected/cytokit_anndata_conf.json
context/app/api/vitessce_confs/fixtures/output_expected/cytokit_json_conf.json
context/app/api/vitessce_confs/fixtures/output_expected/sprm_anndata_conf.json
context/app/api/vitessce_confs/fixtures/output_expected/sprm_conf.json

The proper label for the variables in Vitessce for SPRM is "antigen" not "gene."

Fix SPRM Variables Label

---

CHANGELOG-document-image-pipeline.md
README.md
context/app/static/js/components/home-revision/CarouselImage/Carouselmage.jsx
context/app/static/js/components/home-revision/ImageCarouselContainer/ImageCarouselContainer.jsx

Fix #1740. I kept it pretty minimal, let me know if more information (perhaps regarding using srcset) would be useful.

John conroy/document image pipeline

---

CHANGELOG-remove-publication-status-from-search.md
context/app/static/js/components/home/FacetSearch/FacetSearch.jsx
context/app/static/js/components/home/FacetSearchEntityListItems/FacetSearchEntityListItems.jsx
context/app/static/js/components/home/FacetSearchEntityListItems/FacetSearchEntityListItems.spec.js

John conroy/remove publication status from search

---

CHANGELOG-add-info-button-to-citation.md
context/app/static/js/components/Detail/Citation/Citation.jsx
context/app/static/js/components/Detail/Citation/style.js

citation button

---

CHANGELOG-cells-api-demo.md
context/app/routes_cells.py
context/app/static/js/pages/CellsAPIDemo/CellCountsForDatasets.jsx
context/app/static/js/pages/CellsAPIDemo/CellExpressionInDataset.jsx
context/app/static/js/pages/CellsAPIDemo/CellsAPIDemo.jsx
context/app/static/js/pages/CellsAPIDemo/DatasetsSelectedByGene.jsx
context/app/static/js/pages/CellsAPIDemo/ResultsTable.jsx

Will fix #1774
@tsliaw , Can you confirm that the forms and and the flask endpoints have the right parameters for the questions you'll want to support?
cc @SFD5311

More cells api demo

---

CHANGELOG-bar-chart-links.md
context/app/static/js/components/home/AssayTypeBarChart/AssayTypeBarChart.jsx
context/app/static/js/components/home/AssayTypeBarChartContainer/AssayTypeBarChartContainer.jsx

John conroy/bar chart links

---

CHANGELOG-rename-bar-chart.md
context/app/static/js/pages/Home/Home.jsx

John conroy/rename bar chart

---

CHANGELOG-fix-new-sprm-vitessce.md
context/app/api/vitessce_confs/base_confs.py
context/app/api/vitessce_confs/fixtures/output_expected/cytokit_anndata_conf.json
context/app/api/vitessce_confs/fixtures/output_expected/sprm_anndata_conf.json

The offsets are wrong in the generated data but something should show now regardless
`06589a380ca45237eddd0d9ea7ad2c9f` on TEST if you'd like to test should work now whereas before it would have no visualization

Fix SPRM Stitched

---

CHANGELOG-donor-metadata-query.md
context/app/static/js/pages/search/DevSearch.jsx

Will help find examples to demonstrate that https://github.com/hubmapconsortium/search-api/issues/321 is really fixed.

Add donor queries

---

CHANGELOG-restart-prod-stage.md
redeploy.sh

To fix portal.stage and portal-prod.stage being switched.
Due to PR https://github.com/hubmapconsortium/portal-ui/pull/1659 doesn't really address the issue.

Restart hubmap-auth for STAGE redeploy

---

CHANGELOG-cells.md
context/app/routes_cells.py
context/app/static/js/pages/CellsAPIDemo/CellExpressionInDataset.jsx
context/app/static/js/pages/CellsAPIDemo/CellPercentagesForDatasets.jsx
context/app/static/js/pages/CellsAPIDemo/CellsAPIDemo.jsx
context/app/static/js/pages/CellsAPIDemo/DatasetsSelectedByGene.jsx
context/app/static/js/pages/CellsAPIDemo/ResultsTable.jsx
context/requirements.txt

@tsliaw and @SFD5311: I would like you two to work together to make sure these queries have the right semantics, and to gather a couple sets of input values which produce good outputs. ("good" = "subject matter expert might be persuaded that this is doing something useful.")
I've tweaked the first query to get something that at least runs, but I'm not sure the semantics are correct.
I would like to minimize my involvement: Please make the commits that are needed on this PR, so we have something to show Nils and Ziv.

Use the latest cells API

---

CHANGELOG-remove-support-counts-from-tiles.md
context/app/static/js/components/Detail/provenance/ProvTableTile/ProvTableTile.jsx

John conroy/remove support counts from tiles

---

CHANGELOG-mobilemenu.md
context/app/static/js/components/Header/Menu/Menu.jsx

Mobile Menu change

---

CHANGELOG-file-descriptions.md
context/app/static/js/components/files/FileBrowserFile/FileBrowserFile.jsx

Handle missing descriptions

---

CHANGELOG-cells-sliders.md
context/app/static/js/pages/CellsAPIDemo/DatasetsSelectedByGene.jsx

@john-conroy : Code review
@tsliaw : Design review: Are sliders that look like this ok? (Would like to keep to the defaults where possible.) Width/positioning will change when the whole page is handled.

Cells Sliders

---

CHANGELOG-cells-service.md
context/app/static/js/pages/CellsAPIDemo/CellExpressionInDataset.jsx
context/app/static/js/pages/CellsAPIDemo/CellPercentagesForDatasets.jsx
context/app/static/js/pages/CellsAPIDemo/CellsService.js
context/app/static/js/pages/CellsAPIDemo/DatasetsSelectedByGene.jsx
context/app/static/js/pages/CellsAPIDemo/SearchBySubstring.jsx

Fix #1945. Factoring out all the urls to a single location, as I think you suggested. Down the road, the API calls being made from python might even be moved up to here, but that's not happening soon.

CellsService

---

CHANGELOG-python-vitessce-class-docstrings.md
context/app/api/vitessce_confs/assay_confs.py
context/app/api/vitessce_confs/base_confs.py

Fixes #1951 and following up on [this comment](https://github.com/hubmapconsortium/portal-ui/pull/1950#pullrequestreview-693951261)
Maybe you could go through Chuck and tell me if this is clear/helpful?  And where to improve?

Add Docstrings/Comments to Vitessce Classes

---

CHANGELOG-fix-ci.md
test.sh

Skip changelog check if github refs are github refs are empty

---

CHANGELOG-slider-marks.md
context/app/static/js/pages/CellsAPIDemo/DatasetsSelectedByExpression.jsx

Constrain to marks. Actually getting the mark values requires API work

---

.github/workflows/chromatic.yml
README.md
context/package-lock.json
context/package.json

Fix #1919.
If you log into `https://www.chromatic.com/` via GitHub, you should have access to manage chromatic. Access should mirror that of this repo. Let me know if you'd prefer to register through another means.

John conroy/deploy to chromatic

---

CHANGELOG-localstorage.md
README-deploy-qa.md

Fix #1964, but more general: Just clear all of local storage when we QA... This will also clear lists, but that seems ok to me?

Clear localstorage during QA

---

CHANGELOG-saveor.md
context/app/static/js/components/savedLists/NoItemsSaved/NoItemsSaved.jsx

Fix missing space in conditional message

---

CHANGELOG-list-uuids.md
context/app/routes_cells.py
context/app/static/js/pages/CellsAPIDemo/AllIndexedUUIDs.jsx
context/app/static/js/pages/CellsAPIDemo/CellsAPIDemo.jsx
context/app/static/js/pages/CellsAPIDemo/CellsService.js

Fix #1975. @tsliaw -- I believe it's in your court to think about how this information would be used in the UI?

list indexed datasets

---

CHANGELOG-orcid.md
context/app/static/js/components/Detail/CollectionsAffiliationsTable/CollectionsAffiliationsTable.jsx
context/app/static/js/components/Detail/CollectionsAffiliationsTable/style.js

Just "ORCID", add icon

---

CHANGELOG-keys.md
context/app/static/js/components/Detail/MetadataTable/MetadataTable.jsx
context/app/static/js/components/Detail/derivedEntities/DerivedEntitiesTabs/DerivedEntitiesTabs.jsx
context/app/static/js/components/Detail/provenance/ProvVis/ProvVis.jsx
context/app/static/js/components/home/ImageCarouselContainer/ImageCarouselContainer.jsx
context/app/static/js/pages/search/Search.jsx
context/app/static/js/shared-styles/sections/SectionButtonRow/SectionButtonRow.jsx

Silence some react warnings. We don't see these once it's deployed, and I just haven't taken the time before to click around the site and to find them.

Stop crying wolf

---

CHANGELOG-unused-props-login-button.md
context/app/static/js/components/Header/LoginButton/LoginButton.jsx

John conroy/unused props login button

---

CHANGELOG-fix-vitessce-carousel.md
context/app/api/vitessce_confs/fixtures/output_expected/atac_conf.json
context/app/api/vitessce_confs/fixtures/output_expected/cytokit_anndata_conf.json
context/app/api/vitessce_confs/fixtures/output_expected/cytokit_json_conf.json
context/app/api/vitessce_confs/fixtures/output_expected/image_pyramid_conf.json
context/app/api/vitessce_confs/fixtures/output_expected/ims_conf.json
context/app/api/vitessce_confs/fixtures/output_expected/rna_conf.json
context/app/api/vitessce_confs/fixtures/output_expected/rna_zarr_conf.json
context/app/api/vitessce_confs/fixtures/output_expected/seqfish_conf.json
context/app/api/vitessce_confs/fixtures/output_expected/sprm_anndata_conf.json
context/app/api/vitessce_confs/fixtures/output_expected/sprm_conf.json
context/package-lock.json
context/package.json
context/requirements.txt

Upgrades Vitessce + python package to fix the bug with the carousel Codex view config without code changes, ensuring backwards compatibility
Fixed #2023

Upgrade Vitessce to 1.1.12

---

CHANGELOG-upgrade-caniuse.md
context/package-lock.json

This is really just procrastination. Something to think about would be how to approach housekeeping tasks... Maybe we'd     set a reminder to do this every _n_ sprints?

upgrade caniuse

---

context/app/static/js/pages/Vis/DemographicsChartVertical.jsx
context/app/static/js/pages/Vis/DonorChart.jsx
context/app/static/js/pages/Vis/Vis.jsx
context/app/static/js/pages/Vis/style.js

Here's the styling we went over on Zoom. I also added example label axes to the vertical bar chart (add the titles for each axis as props). Let me know if you have any questions.

John conroy/roselkis style starter

---

CHANGELOG-move-submodule-init.md
README.md
dev-start.sh

Move submodule init

---

context/app/routes_main.py
context/app/static/js/components/Routes/Routes.jsx
context/app/static/js/pages/Vis/DonorChart.jsx
context/app/static/js/pages/Vis/ProjectAttribution.jsx
context/app/static/js/pages/Vis/Vis.jsx
context/app/static/js/pages/Vis/style.js
context/app/static/js/pages/Vis/utils.js

Here's the additional styling/changes we went over.

John conroy/more styling for roselkis

---

context/app/api/vitessce_confs/base_confs.py
context/app/api/vitessce_confs/fixtures/output_expected/cytokit_anndata_conf.json
context/app/api/vitessce_confs/fixtures/output_expected/sprm_anndata_conf.json

For the first point here: #2069.  `cf5cf2de8fb34dd35734756c0e7cf0a1` on TEST is the test data.

Add TSNE Features to SPRM Viz

---

CHANGELOG-hotfix-for-deprecated-assays.md
context/app/api/vitessce_confs/assay_confs.py

Fix for IMC Data Type Deprecation.

---

CHANGELOG-s-v-agreement.md
context/app/static/js/components/files/GlobusLinkMessage/GlobusLinkMessage.jsx
context/app/static/js/components/files/GlobusLinkMessage/GlobusLinkMessage.spec.js

Subject-verb agreement

---

CHANGELOG-link-to-diversity.md
context/app/static/js/components/Footer/Footer.jsx

Link to diversity. 

---

CHANGELOG-403.md
context/app/static/js/components/files/GlobusLink/GlobusLink.jsx

softer warning from entities API

---

context/app/static/js/pages/Home/Home.jsx

Removes the `useEffect` and handles everything in the callback.

Simplify home page anchor link

---

CHANGELOG-home-page-ids.md
context/app/static/js/pages/Home/Home.jsx
context/app/static/js/pages/Home/style.js

We need to add a hook to handle external anchor links. The `useCallback`  is necessary to avoid a race condition. We could also add a timeout or set `behavior: 'auto'` to `behavior: 'smooth'` to provide a smooth transition.
http://localhost:5001#hubmap-datasets should link directly to the bar chart.

John conroy/home page ids

---

CHANGELOG-vitessce-1114.md
context/app/static/js/components/Detail/visualization/Visualization/Visualization.jsx
context/package-lock.json
context/package.json

~~Feedback needed for new warning message.~~  Other than that, just new features.

Upgrade Vitessce to 1.1.14

---

context/app/static/js/pages/CellsAPIDemo/CellExpressionHistogram/CellExpressionHistogram.jsx
context/app/static/js/pages/CellsAPIDemo/CellExpressionHistogram/index.js
context/app/static/js/pages/CellsAPIDemo/DatasetClusterChart/DatasetClusterChart.jsx
context/app/static/js/pages/CellsAPIDemo/DatasetTableRow/DatasetTableRow.jsx
context/app/static/js/shared-styles/charts/Histogram/Histogram.jsx
context/app/static/js/shared-styles/charts/Histogram/Histogram.stories.js
context/app/static/js/shared-styles/charts/Histogram/index.js
context/package-lock.json
context/package.json

Adds a very basic histogram component to shared styles and a histogram of gene expression for cells in a dataset to the cells UI. Moves diagnostic info into the histogram component for simplicity.

John conroy/cell expression histogram

---

context/app/static/js/pages/CellsAPIDemo/CellExpressionHistogram/CellExpressionHistogram.jsx
context/app/static/js/pages/CellsAPIDemo/CellExpressionHistogram/index.js
context/app/static/js/pages/CellsAPIDemo/DatasetClusterChart/DatasetClusterChart.jsx
context/app/static/js/pages/CellsAPIDemo/DatasetTableRow/DatasetTableRow.jsx
context/app/static/js/shared-styles/charts/Histogram/Histogram.jsx
context/app/static/js/shared-styles/charts/Histogram/Histogram.stories.js
context/app/static/js/shared-styles/charts/Histogram/index.js
context/app/static/js/shared-styles/charts/VerticalStackedBarChart/VerticalStackedBarChart.jsx
context/package-lock.json
context/package.json

Adds a dropdown to allow users to select a cluster method. Still a little rough.

John conroy/cluster dropdown

---

CHANGELOG-publications-note.md
context/app/static/js/pages/Publications/Publications.jsx
context/app/static/js/pages/Services/Services.jsx

Add publications description

---

CHANGELOG-tsne-name-change.md
context/app/api/vitessce_confs/base_confs.py
context/app/api/vitessce_confs/fixtures/output_expected/cytokit_anndata_conf.json
context/app/api/vitessce_confs/fixtures/output_expected/sprm_anndata_conf.json

`TSNE` -> `t-SNE` in SPRM

---

CHANGELOG-all-lineup-columns.md
context/app/api/client.py

I filed https://github.com/lineupjs/lineupjsx/issues/27 in error -- pretty sure the root cause is on our side.

get all columns in lineup

---

CHANGELOG-created-timestamp.md
context/app/static/js/components/Detail/Citation/Citation.jsx
context/app/static/js/components/Detail/Citation/Citation.spec.js
context/app/static/js/components/Detail/Citation/Citation.stories.js
context/app/static/js/components/Detail/Summary/Summary.jsx
context/app/static/js/components/Detail/Summary/Summary.stories.js
context/app/static/js/components/Detail/SummaryBody/SummaryBody.jsx
context/app/static/js/components/Detail/SummaryBody/SummaryBody.stories.js
context/app/static/js/pages/SavedList/SavedList.jsx

No change in behavior, but this will make me more confident that the schema change Zhao is working on will not break anything.
Fix #2151

search and replace create(d)-timestamp

---

CHANGELOG-firefox-warning.md
context/app/static/js/components/Detail/visualization/Visualization/Visualization.jsx

Carried over from the new Cytokit datasets, we needed Nils' input on the message but now have it.

New Firefox Warning

---

CHANGELOG-slide-seq.md
context/app/api/client.py
context/app/api/vitessce_confs/__init__.py
context/app/api/vitessce_confs/assay_confs.py
context/app/api/vitessce_confs/base_confs.py
context/app/api/vitessce_confs/fixtures/input_entity/malformed_spatial_rna_zarr_entity.json
context/app/api/vitessce_confs/fixtures/input_entity/spatial_rna_zarr_entity.json
context/app/api/vitessce_confs/fixtures/output_expected/spatial_rna_zarr_conf.json
context/app/api/vitessce_confs/test_confs.py

This PR adds an `_is_spatial` option to the `RNASeqAnnDataZarrViewConfBuilder` class (and its descendants) for enabling visualization of spatially resolved data, including but not limited SlideSeq.

Add Slide-Seq Visualization

---

CHANGELOG-regen-organs.md
push.sh

Small change, and it shouldn't really change the process, but wanted you to be aware of it.
fix #2175

Update organs as part of push.sh

---

context/app/routes_cells.py
context/app/static/js/components/cells/CellExpressionHistogram/CellExpressionHistogram.jsx
context/app/static/js/components/cells/CellsService.js
context/app/static/js/components/cells/DatasetClusterChart/DatasetClusterChart.jsx
context/app/static/js/components/cells/DatasetTableRow/DatasetTableRow.jsx
context/app/static/js/components/cells/DatasetsSelectedByExpression/DatasetsSelectedByExpression.jsx
context/app/static/js/components/cells/DatasetsTable/DatasetsTable.jsx
context/app/static/js/components/cells/QuerySelect/style.js
context/app/static/js/pages/Cells/Cells.jsx

Requested changes to #2150. I'll move the accordion steps to children in a later PR once everything else is merged.

John conroy/protein queries suggestions

---

CHANGELOG-fix-organ-page-requests.md
context/app/static/js/components/organ/Samples/Samples.jsx

Fix organ page request loop in samples table.

John conroy/fix organ page requests

---

CHANGELOG-missing-key.md
context/app/static/js/components/Header/Dropdown/Dropdown.jsx
context/app/static/js/components/Header/LoginButton/LoginButton.jsx
context/app/static/js/components/Header/Menu/Menu.jsx

Adding the key seems clear enough. Removing the ID seems reasonable... unless there's a reason we really do need an ID on all of them, in which case I can add them.

Add key, remove required prop

---

CHANGELOG-fix-hubmap-commons-install.md
context/requirements.txt

John conroy/fix hubmap commons install

---

CHANGELOG-fix_maldi.md
context/app/api/vitessce_confs/assay_confs.py
context/app/api/vitessce_confs/assays.py

See: https://hubmapconsortium.slack.com/archives/C011RF3NQ23/p1637456389187900

Fix MALDI Visualization

---

CHANGELOG-cells-api-info.md
context/app/static/js/components/ServiceStatusTable/ServiceStatusTable.jsx

more info about cells service

---

CHANGELOG-commons.md
context/requirements.txt

use commons from pypi

---

CHANGELOG-retracted-details-page.md
context/app/static/js/components/detailPage/StatusIcon/StatusIcon.jsx
context/app/static/js/pages/Dataset/Dataset.jsx

Towards #2167 (Still need to exclude from search results.)

handle retracted on details

---

CHANGELOG-revisions-changes.md
context/app/static/js/components/detailPage/VersionSelect/VersionSelect.jsx
context/app/static/js/components/detailPage/VersionSelect/utils.js
context/app/static/js/components/detailPage/VersionSelect/utils.spec.js

Filed #2301. The update should be on DEV shortly.

John conroy/revisions changes

---

CHANGELOG-simplify-view-conf.md
context/app/api/client.py

I don't think it hurts anything if the constructor is called with arguments? But you may know better.

get rid of `isinstance`

---

CHANGELOG-timestamp-local-docker.md
docker.sh

- `--follow` is always what I want.
- `--timestamp` is useful, too.

tweak docker.sh

---

CHANGELOG-link-to-issue.md
context/app/test_routes_api.py

Just comments: Comfortable with self merge.

link to issue

---

CHANGELOG-description-facet.md
context/app/static/js/pages/search/DevSearch.jsx

When merged, this will get you example values that should guide your design... Off the bat, I think that dealing with the large number of possible file descriptions, even when constrained to a particular assay type, is going to be a challenge: I don't think we should give the user a list of 50+ check boxes.
<details><summary>Example: CODEX [Cytokit + SPRM]</summary>
| description | datasets |
| --- | --- |
| A list of byte-offsets of a TIFF file for quick access in visualization. | 89 |
| JSON-formatted information about each cell segmented and analyzed in SPRM. | 89 |
| JSON-formatted information about each cell's cluster. | 89 |
| JSON-formatted information about each cell's expression level. | 89 |
| JSON-formatted information for a heatmap of each cell's expression level. | 89 |
| …

descriptions facet

---

.vscode/portal-ui.code-snippets
context/app/static/js/components/organ/Samples/Samples.jsx
context/app/static/js/components/savedLists/SavedEntitiesTable/SavedEntitiesTable.jsx
context/app/static/js/helpers/__tests__/getArrayRange.spec.js
context/app/static/js/helpers/__tests__/getIDsQuery.spec.js
context/app/static/js/helpers/__tests__/getSearchHitsEntityCounts.spec.js
context/app/static/js/helpers/functions.js
context/app/static/js/shared-styles/tables/LoadingTableRows/LoadingTableRows.jsx
context/app/static/js/shared-styles/tables/LoadingTableRows/LoadingTableRows.spec.js
context/app/static/js/shared-styles/tables/LoadingTableRows/LoadingTableRows.stories.js
context/app/static/js/shared-styles/tables/SelectableHeaderCell/SelectableHeaderCell.jsx
context/app/static/js/shared-styles/tables/SelectableRowCell/SelectableRowCell.jsx
context/app/static/js/shared-styles/tables/SelectableTableProvider/SelectableTable.spec.js
context/app/static/js/shared-styles/tables/SelectableTableProvider/SelectableTableProvider.jsx
context/app/static/js/shared-styles/tables/SelectableTableProvider/SelectableTableProvider.stories.js
context/app/static/js/shared-styles/tables/SelectableTableProvider/store.spec.js

John conroy/organ samples polish stories tests

---

CHANGELOG-diagram.md
README.md

Could add more information about what kind of dependency each is... but that could get complicated, and even this partial picture may be useful.

Update README diagram

---

CHANGELOG-release-readme.md
README-deploy-qa.md

@tsliaw -- I think you and I can just take alternating weeks, if that works for you.

Update release protocol

---

CHANGELOG-pass-get_assay-to-builder.md
context/app/api/client.py

Replaces PR #2401, which has an unhappy submodule hash. Same code changes, which were already approved by @john-conroy .

apply changes from earlier pr

---

CHANGELOG-vitessce.md
context/package-lock.json
context/package.json

Fix #2419
With Chrome, http://localhost:5001/browse/dataset/b6eba6afe660a8a85c2648e368b0cf9f loads in 3d without error.

upgrade vitessce

---

CHANGELOG-keep-query.md
context/app/main.py
context/app/test_routes_main.py

preserve query after redirect

---

CHANGELOG-dont-link-to-supports.md
context/app/static/js/components/home/HuBMAPDatasetsChart/HuBMAPDatasetsChart.jsx
context/app/static/js/components/organ/OrganDatasetsChart/OrganDatasetsChart.jsx
context/app/static/js/helpers/__tests__/combineQueryClauses.spec.js
context/app/static/js/helpers/functions.js
context/app/static/js/helpers/queries.js

John conroy/dont link to supports

---

CHANGELOG-revert-timeout.md
context/portal.nginx.conf

revert to default nginx timeout

---

.gitignore
CHANGELOG-query-portal-logs.md
README.md
query-portal-logs.py

Fix #2328. I created an IAM role one can assume to run the script and right now I'm the only one who has the access to assume that role. I think that's fine for now, but if you would like access let me know.
It seems like we're exceeding the response size limit ( at least for the last week). I might bump it up to 500.

John conroy/query portal logs

---

CHANGELOG-tile-thumbnails.md
context/.dockerignore
context/.storybook/preview.js
context/app/static/js/components/detailPage/provenance/ProvGraph/ProvGraph.spec.js
context/app/static/js/components/entity-tile/EntityTile/EntityTile.jsx
context/app/static/js/components/entity-tile/EntityTile/EntityTile.stories.js
context/app/static/js/components/entity-tile/EntityTile/style.js
context/app/static/js/components/entity-tile/EntityTileBody/EntityTileBody.jsx
context/app/static/js/components/entity-tile/EntityTileBody/style.js
context/app/static/js/components/searchPage/ResultsTiles/style.js
context/app/static/js/components/searchPage/config.js
context/app/static/storybook-public/mockServiceWorker.js
context/package-lock.json
context/package.json

Fix #2442.
Default
Inverted Colors 
With Overflow

John conroy/tile thumbnails

---

CHANGELOG-requirements-list.md
grab-dependencies.sh

shorter list of python dependencies

---

CHANGELOG-data-use-to-data-sharing.md
context/app/static/js/components/Footer/Footer.jsx

change link to Data Sharing Policy

---

CHANGELOG-hra.md
context/app/static/js/components/Header/AtlasToolsLinks/AtlasToolsLinks.jsx

Fix #2613 from Bruce. I have not reviewed the content: I don't think that is my responsibility.

Add three HRA links

---

CHANGELOG-remove-date-metadata-fields.md
context/app/static/js/components/entity-search/sidebar/ConfigureSearchTable/ConfigureSearchTable.jsx
context/app/static/js/components/entity-search/sidebar/ConfigureSearchTable/utils.js
context/app/static/js/components/entity-search/sidebar/ConfigureSearchTable/utils.spec.js
context/app/static/js/components/entity-search/sidebar/DatasetConfigureSearchTable/hooks.js

Removes date fields from configure search table while we work to resolve #2630.

John conroy/remove date metadata fields

---

CHANGELOG-fix-configure-facet-bug.md
CHANGELOG-search-pagination.md
context/app/static/js/components/entity-search/Search/Search.jsx
context/app/static/js/components/entity-search/Search/style.js
context/app/static/js/components/entity-search/SearchWrapper/SearchWrapper.jsx
context/app/static/js/components/entity-search/facets/Facets/hooks.js
context/app/static/js/components/entity-search/results/Pagination/Pagination.jsx
context/app/static/js/components/entity-search/results/Pagination/index.js
context/app/static/js/components/entity-search/results/Pagination/style.js
context/app/static/js/components/entity-search/results/ResultsFound/ResultsFound.jsx
context/app/static/js/components/entity-search/results/ResultsFound/index.js
context/app/static/js/components/entity-search/results/ResultsFound/style.js

The pagination components do not have the same appearances as the pagination on our existing search ui, but before investing more time I want to confirm the design with Tiffany. I'd like to merge with the default styling and revisit it once Tiffany is back from the conference.

John conroy/search pagination

---

.github/workflows/cypress-ci.yml
.github/workflows/python-ci.yml
CHANGELOG-python-39.md
README.md
context/Dockerfile

No particular reason to do it now, but at some point we'll need to.

Mccalluc/bump to 3.9

---

CHANGELOG-search-url-sync.md
context/app/static/js/components/entity-search/Search/Search.jsx
context/app/static/js/components/entity-search/SearchWrapper/SearchWrapper.jsx
context/app/static/js/components/entity-search/searchkit-modifications/routeToState.js

The url will now be updated as queries and filters are modified, but additional configuration will be needed for the url to state relationship. Adding to the UI agenda.

John conroy/search url sync

---

CHANGELOG-do-not-limit-cells-at-10.md
context/app/static/js/components/cells/DatasetsSelectedByExpression/DatasetsSelectedByExpression.jsx

Increase ES size for cells query

---

CHANGELOG-scroll-shadows.md
context/app/static/js/components/entity-search/facets/select/SelectFacet/style.js
context/app/static/js/components/entity-search/sidebar/ConfigureSearchTable/ConfigureSearchTable.jsx
context/app/static/js/components/entity-search/sidebar/ConfigureSearchTable/hooks.js
context/app/static/js/components/entity-search/sidebar/ConfigureSearchTable/style.js
context/app/static/js/components/entity-search/sidebar/DataTypesSelect/style.js
context/app/static/js/shared-styles/scrollShadows.js
context/package-lock.json
context/package.json

If this looks good, I'll open an issue to add scroll shadows to our existing tables and lists. 
@tsliaw Do we want horizontal scroll shadows for the main search table when columns are added?

John conroy/scroll shadows

---

CHANGELOG-add-organ-to-tsv.md
context/app/routes_api.py

Add organ to TSV download

---

CHANGELOG-more-auth-logging.md
context/app/routes_auth.py

- Towards #2518
- Any information you would add?
- I haven't run docker locally to confirm the logic works.

log more details of the auth process

---

CHANGELOG-first-cells-dataset-open.md
context/app/static/js/components/cells/DatasetTableRow/DatasetTableRow.jsx
context/app/static/js/components/cells/DatasetsTable/DatasetsTable.jsx
context/app/static/js/shared-styles/tables/ExpandableRow/ExpandableRow.jsx
context/app/static/js/shared-styles/tables/ExpandableRow/store.js

John conroy/first cells dataset open

---

CHANGELOG-cells-top-of-page.md
context/app/static/js/pages/Cells/Cells.jsx

change cells title; add description

---

CHANGELOG-fix-script-path.md
scripts/dev/organ-utils/make_organ_dir.py

- Follow-up to #2811.
Correct path for new location.

fix script path

---

CHANGELOG-separate-cells-plots.md
context/app/static/js/components/cells/CellsCharts/CellsCharts.jsx
context/app/static/js/components/cells/CellsCharts/style.js
context/app/static/js/shared-styles/tables/ExpandableRow/style.js

John conroy/separate cells plots

---

CHANGELOG-consolidate-cells-hooks.md
context/app/static/js/components/cells/DatasetsSelectedByExpression/DatasetsSelectedByExpression.jsx
context/app/static/js/components/cells/DatasetsSelectedByExpression/hooks.js

It was getting cluttered and it's good practice to have a single hook per component.

John conroy/consolidate cells hooks

---

CHANGELOG-consolidate-cells-hooks.md
CHANGELOG-fix-empty-cells-charts.md
context/app/static/js/components/cells/CellsCharts/CellsCharts.jsx
context/app/static/js/components/cells/DatasetsSelectedByExpression/DatasetsSelectedByExpression.jsx
context/app/static/js/components/cells/DatasetsSelectedByExpression/hooks.js
context/app/static/js/stores/useCellsChartLoadingStore.js

Like we discussed in stand-up, I believe we were unintentionally relying on a component dismount to reset the store. The recent refactors disrupted the store reset.

John conroy/fix empty cells charts

---

CHANGELOG-datasets-in-new-tab.md
context/app/static/js/components/cells/DatasetTableRow/DatasetTableRow.jsx

open in new tab

---

context/app/static/assets/svg/workspaces.svg
context/app/static/js/components/Providers.jsx
context/app/static/js/pages/Dataset/Dataset.jsx

Hope this helps. I'm not sure why you used `type='submit'` before?
@tsliaw FYI the default disabled state for icon buttons is a transparent background and a grey icon. If you'd like it to be something else, let me know.

John conroy/workspaces icon

---

CHANGELOG-fix-homepage-spacing.md
context/app/static/js/components/home/TwitterTimeline/style.js

Towards #2856.
Fixes overflow, but scrolling no longer works. Waiting for more dust to settle with Twitter's widget changes before investing more time.

John conroy/fix homepage spacing

---

CHANGELOG-organs-link-homepage.md
context/app/routes_file_based.py
context/app/routes_main.py
context/app/static/js/components/Routes/Routes.jsx
context/app/static/js/components/home/EntityCount/EntityCount.jsx
context/app/static/js/components/home/EntityCount/style.js
context/app/static/js/components/home/EntityCounts/EntityCounts.jsx
context/app/static/js/components/home/EntityCounts/hooks.js
context/app/static/js/components/home/EntityCounts/style.js
context/app/static/js/components/organ/OrganTile/OrganTile.jsx
context/app/static/js/components/organ/OrganTile/style.js
context/app/static/js/pages/Home/Home.jsx
context/app/static/js/shared-styles/icons/URLSvgIcon/URLSvgIcon.jsx
context/app/static/js/shared-styles/icons/URLSvgIcon/index.js
context/app/static/js/shared-styles/icons/URLSvgIcon/style.js
context/app/utils.py

John conroy/organs link homepage

---

CHANGELOG-link-type.md
context/app/static/js/helpers/trackers.js
context/app/static/js/shared-styles/Links/iconLinks/EmailIconLink/EmailIconLink.jsx

- Fix #2722
GA isn't getting precisely the same value as it had in the past, but I think this suffices... but push back, if you disagree: It wouldn't be that much more complicated.

record type of link

---

CHANGELOG-symlink-dir-to-workspace.md
context/app/routes_notebooks.py

- Fix #2883
Particularly looking for confirmation that the text is sufficient, and we don't need to conditionally generate the notebook, depending on how it will be used.

symlink works

---

CHANGELOG-edit-preview-2.md
context/app/preview/liver-map.md
context/app/preview/multimodal-mass-spectrometry-imaging-data.md
context/app/static/js/components/Header/ResourceLinks/ResourceLinks.jsx

This PR adds two additional vitessce configs, updates the preview name, and comments out the remaining TODO statements to make it merge-able while we are still waiting for a longer description.

Add config to preview

---

CHANGELOG-fix-home-organ-link.md
context/app/static/js/components/home/EntityCounts/EntityCounts.jsx

John conroy/fix home organ link

---

CHANGELOG-check-ws-states.md
context/app/static/js/components/workspaces/WorkspacesList.jsx
context/app/static/js/components/workspaces/statusCodes.js
context/app/static/js/components/workspaces/utils.js
context/app/static/js/components/workspaces/utils.spec.js

Filing as draft for now:
- These lists are incomplete: Can use help from @jpuerto-psc to fill them out
- The prod API right now is returning "Pending" as a status: that is just a bug
When that's resolved:
- When this is fleshed out and merged, it should unblock #2877

Error if unexpected Workspace and Job statuses are seen

---

CHANGELOG-new-preview.md
context/app/static/js/components/Header/ResourceLinks/ResourceLinks.jsx

The preview looks great to me! Can we put it up? If you don't think you can give the thumbs up, can you say who should, or what is blocking? Thanks!

Add preview link to menu

---

CHANGELOG-organ-info-data.md
context/app/static/js/pages/Iframe/Iframe.jsx
context/app/templates/special-pages/organ.html

See related issue in CCF-UI: <https://github.com/hubmapconsortium/ccf-ui/issues/948>

Limit organ-info datasets to HRA-mapped HuBMAP data only

---

CHANGELOG-citing-hubmap.md
context/app/static/js/components/Footer/Footer.jsx

Make "citing HuBMAP" an outbound link

---

CHANGELOG-ingest-api.md
context/app/static/js/components/ServiceStatusTable/ServiceStatusTable.jsx

ingest ui -> api

---

CHANGELOG-sync-facets-filters.md
context/app/static/js/components/entity-search/SearchWrapper/store.js
context/app/static/js/components/entity-search/searchkit-modifications/withSearchkitRouting.js

Adds filters defined in url as facets. Filters defined in url which weren't included as default facets would previously error.

John conroy/sync facets filters

---

CHANGELOG-bump-portal-vis.md
CHANGELOG-bump-portal-viz.md
context/requirements.in
context/requirements.txt

- Bump portal vis to 0.0.8 to handle search api v3.

John conroy/bump portal viz

---

CHANGELOG-add-nils-to-workspaces.md
context/app/static/js/components/Providers.jsx

Add Nils to workspaces allow list and remove Chuck.

John conroy/add nils workspaces

---

CHANGELOG-fix-workspaces-list-updates.md
context/app/static/js/components/workspaces/WorkspacesList.jsx
context/app/static/js/components/workspaces/hooks.js
context/app/static/js/components/workspaces/utils.js

Towards #2799. Update workspaces list after workspace create and delete so users no longer have to refresh the page for updates.

John conroy/fix workspaces list updates

---

CHANGELOG-fix-workspace-jupyter-path.md
context/app/routes_notebooks.py
context/app/static/js/components/workspaces/WorkspaceDetails/WorkspaceDetails.jsx
context/app/static/js/pages/WorkspacePleaseWait/WorkspacePleaseWait.jsx

John conroy/fix workspace jupyter path

---

CHANGELOG-launch-dataset-workbook-in-new-tab.md
context/app/static/js/pages/Dataset/Dataset.jsx

Launch dataset workspace notebook in new tab.

John conroy/launch dataset notebook in new tab

---

CHANGELOG-handle-stopping-workspaces.md
CHANGELOG-pass-job-types-id-on-start.md
context/app/static/js/components/workspaces/statusCodes.js
context/app/static/js/components/workspaces/utils.js

Handles stopping status for workspace jobs

John conroy/handle stopping workspaces

---

CHANGELOG-search-select-results.md
context/app/static/js/components/entity-search/ResultsTable/ResultsTable.jsx
context/app/static/js/components/entity-search/Search/Search.jsx
context/app/static/js/components/entity-search/Search/hooks.js
context/app/static/js/components/entity-search/SearchWrapper/SearchWrapper.jsx
context/app/static/js/components/entity-search/results/Results/Results.jsx
context/app/static/js/components/entity-search/searchkit-modifications/useSearchkitSDK.js

Enable users to select results in new search UI. Downloaded TSV and notebooks will now only include selections.

John conroy/search select results

---

CHANGELOG-fix-protein-measurement.md
context/app/static/js/components/cells/AutocompleteEntity/AutocompleteEntity.jsx
context/app/static/js/components/cells/CellExpressionHistogram/CellExpressionHistogram.jsx
context/app/static/js/components/cells/DatasetsSelectedByExpression/DatasetsSelectedByExpression.jsx
context/app/static/js/components/cells/QuerySelect/QuerySelect.jsx
context/app/static/js/components/cells/queryTypes.js
context/app/static/js/pages/Cells/Cells.jsx

John conroy/fix protein measurement

---

CHANGELOG-update-cells-disclaimer.md
context/app/static/js/pages/Cells/Cells.jsx

John conroy/update cells disclaimer

---

CHANGELOG-hra-preview-updates.md
context/app/static/js/components/Header/AtlasToolsLinks/AtlasToolsLinks.jsx

- Added three more HRA previews
- Updated the CCF Portal to the HRA Portal and it's new home, humanatlas.io

Update Atlas Menu

---

CHANGELOG-add-gesina-workspaces.md
context/app/static/js/components/Providers.jsx

Add Gesina to workspaces allow list.

John conroy/add gesina workspaces

---

CHANGELOG-fix-organ-page-toc-names.md
context/app/static/js/components/organ/HumanReferenceAtlas/HumanReferenceAtlas.jsx
context/app/static/js/components/organ/HumanReferenceAtlas/index.js
context/app/static/js/components/organ/OrganInfo/index.js
context/app/static/js/pages/Organ/Organ.jsx
context/app/static/js/shared-styles/sections/TableOfContents/style.js

John conroy/fix organ page toc names

---

CHANGELOG-fix-entity-counts-iframe.md
context/app/routes_main.py
context/app/static/js/pages/Iframe/Iframe.jsx

Pass organs count to entity counts iframe.

John conroy/fix entity counts iframe

---

CHANGELOG-fix-organ-page-sample-table.md
context/app/static/js/components/organ/Samples/Samples.jsx

- Fix organ page table to show all samples belonging to the organ.

John conroy/fix organ page sample table

---

CHANGELOG-publication-tabs.md
context/app/static/js/pages/Publications/Publications.jsx
context/app/static/js/pages/Publications/hooks.js
context/app/static/js/pages/Publications/style.js
context/app/static/js/pages/Publications/utils.js
context/app/static/js/pages/Publications/utils.spec.js
context/app/static/js/shared-styles/panels/PanelList/style.js

Towards #3035.
Separate publications on publications page by status.

John conroy/publications tabs

---

CHANGELOG-add-testers-workspaces-allow-list.md
context/app/static/js/components/Providers.jsx

Add testers and @thomcsmits to workspace allow list.

John conroy/add testers workspace allow list

---

CHANGELOG-fix-cells-dataset-versions.md
context/app/static/js/components/cells/DatasetsSelectedByExpression/hooks.js

Fix bug in cells ui caused by multiple versions of the dataset returned by the cells api.

John conroy/fix cells dataset versions

---

CHANGELOG-fix-publication-supports.md
context/app/static/js/components/publications/PublicationRelatedEntities/hooks.js

Fix publications hook to handle support entities.

John conroy/fix publication supports

---

CHANGELOG-fix-preprint-publications.md
context/app/static/js/pages/Publications/hooks.js

Fix bug when separating publications by publication status resulting in preprints not being listed.

John conroy/fix preprint publications

---

CHANGELOG-fix-viz-notebook.md
context/app/static/js/components/detailPage/visualization/VisualizationNotebookButton/VisualizationNotebookButton.jsx
context/app/static/js/components/entity-search/MetadataMenu/MetadataMenu.jsx
context/app/static/js/components/searchPage/MetadataMenu/MetadataMenu.jsx
context/app/static/js/helpers/postAndDownloadFile.js

Fix download visualization notebook button in vitessce section.

John conroy/fix viz download notebook

---

CHANGELOG-cells-beta-labels.md
context/app/static/js/components/Header/OtherLinks/OtherLinks.jsx
context/app/static/js/pages/Cells/Cells.jsx

John conroy/cells beta labels

---

CHANGELOG-publication-provenance.md
context/app/static/js/components/detailPage/provenance/ProvTabs/ProvTabs.jsx
context/app/static/js/pages/Publication/Publication.jsx

Towards #3035. Add provenance section to publication page.

John conroy/publication provenance

---

CHANGELOG-publication-sidebar.md
context/app/static/js/components/detailPage/ContributorsTable/ContributorsTable.jsx
context/app/static/js/components/publications/PublicationRelatedEntities/PublicationRelatedEntities.jsx
context/app/static/js/pages/Publication/Publication.jsx

Towards #3035. Add table of contents sidebar to publication page.

John conroy/publication sidebar

---

CHANGELOG-publication-details.md
context/app/static/js/components/publications/AggsList/AggsList.jsx
context/app/static/js/components/publications/AggsList/hooks.js
context/app/static/js/components/publications/AggsList/index.js
context/app/static/js/components/publications/CorrespondingAuthorsList/CorrespondingAuthorsList.jsx
context/app/static/js/components/publications/CorrespondingAuthorsList/index.js
context/app/static/js/components/publications/PublicationCitation/PublicationCitation.jsx
context/app/static/js/components/publications/PublicationCitation/index.js
context/app/static/js/components/publications/PublicationRelatedEntities/hooks.js
context/app/static/js/components/publications/PublicationSummary/PublicationSummary.jsx
context/app/static/js/components/publications/PublicationSummary/index.js
context/app/static/js/components/publications/PublicationVisualizationsSection/PublicationsVisualizationSection.jsx
context/app/static/js/helpers/queries.js
context/app/static/js/pages/Publication/Publication.jsx
context/app/static/js/shared-styles/lists/bulleted-lists/BulletedList/BulletedList.jsx
context/app/static/js/shared-styles/lists/bulleted-lists/BulletedList/index.js
context/app/static/js/shared-styles/lists/bulleted-lists/BulletedList/style.js
context/app/static/js/shared-styles/lists/bulleted-lists/BulletedListItem/BulletedListItem.jsx
context/app/static/js/shared-styles/lists/bulleted-lists/BulletedListItem/index.js
context/app/static/js/shared-styles/lists/bulleted-lists/BulletedListItem/style.js

Towards #3035. Add details to summary on publication page. Filed #3070.

John conroy/publication details

---

CHANGELOG-fix-homepage-organ-icon-hover.md
context/app/static/js/components/home/EntityCount/style.js

John conroy/fix homepage organ icon hover

---

CHANGELOG-fix-collection-title.md
context/app/static/js/pages/Collection/Collection.jsx

John conroy/fix collections title

---

CHANGELOG-portal-team-workspace-allow-list.md
context/app/static/js/components/Providers.jsx

Add entire portal ui team to workspace allow list. Filed #3080.

John conroy/portal team workspace allow list

---

CHANGELOG-handle-hubmap-request-redirect.md
context/app/api/client.py
context/app/api/test_client.py
context/app/test_routes_api.py
context/app/test_routes_main.py

Handles redirect to S3 from HuBMAP APIs behind API Gateway in our flask code.

John conroy/handle hubmap request redirect [HMP-60]

---

CHANGELOG-add-publication-link.md
context/app/static/js/components/Header/OtherLinks/OtherLinks.jsx

Add link to publications landing page in 'Other' dropdown menu.

John conroy/add publications link HMP-139

---

CHANGELOG-hmp-122-setup-context-flaskdata.md
context/app/static/js/components/App.jsx
context/app/static/js/components/Contexts.jsx
context/app/static/js/components/Providers.jsx
context/app/static/js/components/Routes/Routes.jsx
context/app/static/js/components/detailPage/Attribution/Attribution.jsx
context/app/static/js/components/detailPage/MetadataTable/MetadataTable.jsx
context/app/static/js/components/detailPage/derivedEntities/DerivedEntitiesSection/DerivedEntitiesSection.jsx
context/app/static/js/components/detailPage/provenance/ProvSection/ProvSection.jsx
context/app/static/js/components/detailPage/provenance/ProvTable/ProvTable.jsx
context/app/static/js/components/detailPage/provenance/ProvTabs/ProvTabs.jsx
context/app/static/js/components/detailPage/related-entities/RelatedEntitiesTable/RelatedEntitiesTable.jsx
context/app/static/js/components/detailPage/related-entities/RelatedEntitiesTabs/RelatedEntitiesTabs.jsx
context/app/static/js/components/detailPage/summary/Summary/Summary.jsx
context/app/static/js/pages/Donor/Donor.jsx

Set up context to replace prop drilling and implemented it for Donor page.

Kevin yoo/setup context flaskdata

---

CHANGELOG-hmp-147-refactor-appContext.md
context/app/static/js/components/Contexts.jsx
context/app/static/js/components/Header/HeaderContent/HeaderContent.jsx
context/app/static/js/components/Header/UserLinks/UserLinks.jsx
context/app/static/js/components/Providers.jsx
context/app/static/js/components/Routes/Routes.jsx
context/app/static/js/components/cells/DatasetsSelectedByExpression/hooks.js
context/app/static/js/components/detailPage/VersionSelect/VersionSelect.jsx
context/app/static/js/components/detailPage/files/FileBrowserFile/FileBrowserFile.jsx
context/app/static/js/components/detailPage/files/GlobusLink/GlobusLink.jsx
context/app/static/js/components/detailPage/provenance/ProvSection/ProvSection.jsx
context/app/static/js/components/detailPage/provenance/ShowDerivedEntitiesButton/ShowDerivedEntitiesButton.jsx
context/app/static/js/components/entity-search/Search/hooks.js
context/app/static/js/components/entity-tile/EntityTileThumbnail/EntityTileThumbnail.jsx
context/app/static/js/components/publications/PublicationVignette/PublicationVignette.jsx
context/app/static/js/components/workspaces/WorkspacesAuthenticated.jsx
context/app/static/js/components/workspaces/hooks.js
context/app/static/js/hooks/useSearchData.js
context/app/static/js/pages/Dataset/Dataset.jsx
context/app/static/js/pages/Services/Services.jsx
context/app/static/js/pages/WorkspacePleaseWait/hooks.js
context/app/static/js/pages/Workspaces/Workspaces.jsx
context/app/static/js/pages/search/CellsSearch.jsx
context/app/static/js/pages/search/DevSearch.jsx
context/app/static/js/pages/search/Search.jsx

Went through all files using App Context and refactored to use UseAppFactor from Context.js

Kevin yoo/refactor app context

---

context/app/routes_api.py
context/app/static/js/components/home/FacetSearch/FacetSearch.jsx
context/app/static/js/components/organ/OrganDatasetsChart/OrganDatasetsChart.jsx
context/app/static/js/components/organ/Samples/Samples.jsx
context/app/static/js/components/organ/utils.js
context/app/static/js/components/organ/utils.spec.js
context/app/static/js/components/searchPage/ResultsTable/utils.js
context/app/static/js/components/searchPage/config.js
context/app/static/js/pages/Dataset/Dataset.jsx
context/app/static/js/pages/Sample/Sample.jsx
context/app/static/js/pages/utils/entity-utils.js
context/app/static/js/pages/utils/entity-utils.spec.js
context/app/static/js/schema.org.js
context/app/static/js/schema.org.spec.js
etc/dev/organ-utils/make_organ_dir.py

Follow up to #3120. Didn't want the original to PR to get too big. There is no logical divide between the two.

John conroy/remove origin sample dependencies followup

---

CHANGELOG-hmp-182-lineup.md
context/app/routes_api.py
context/app/static/js/pages/LineUpPage/LineUpPage.jsx

This PR adjusts the lineup pages to catch cases where entities are missing data keys. 
- After the initial removal of `undefined` and `null` properties from the entities, an additional check is performed to make sure that all the entities conform to the schema of the first one
- Entities with missing keys have their UUID's and the missing key printed in the browser console to help identify/remediate these data issues and allow the data to be displayed.
Since this operation involves multiple iterations over an array up to 10,000 items long, I put the related calculations into a `useMemo` call.
Bad entities:
```
Entity fe2babe40b7f17034776ff3031ca0cb5 is missing key origin_samples_unique_mapped_organs
Entity f2d4cf63e8080d4d2c2821c85d3ff9d6 is missing key origin_samples_unique_mapped_organs …
```

HMP-182 Fix Lineup pages

---

CHANGELOG-error-display.md
context/app/static/js/components/detailPage/visualization/VisualizationWrapper/VisualizationError.jsx
context/app/static/js/components/detailPage/visualization/VisualizationWrapper/VisualizationWrapper.jsx
context/app/static/js/components/detailPage/visualization/VisualizationWrapper/style.js
context/app/static/js/pages/Error/style.js
context/build-utils/webpack.dev.js

This was a change made while diagnosing HMP-151 (which has since been traced to an internal vitessce issue, so any further changes related to this will be made there and will be accompanied with a dependency version bump here)
One of the issues identified for this ticket was that the error message overflows its container due to the length of the URL, so this PR is to correct this issue.

NickAkhmetov / Fix error page overflow

---

CHANGELOG-fix-provenance.
context/app/static/js/components/detailPage/provenance/ProvTabs/ProvTabs.jsx

Fix flask data context destructuring to restore provenance features.

John conroy/fix provenance HMP-213 HMP-206

---

CHANGELOG-hmp-156-update-text-for-access-permissions-for-workspaces.md
context/app/static/js/pages/Workspaces/Workspaces.jsx

Hello team, I think I did it the way we discussed during the call. Feel free to give any additional suggestions :)

Kevin yoo/hmp 156 update text for access permissions for workspaces

---

CHANGELOG-fix-provenance.
CHANGELOG-fix-provenance.md
CHANGELOG-hotfix.md

This PR fixes the Changelog file extension for the changes in #3146

NickAkhmetov/Rename CHANGELOG-fix-provenance. to CHANGELOG-fix-provenance.md

---

CHANGELOG-publication-associated-collection.md
context/app/static/js/components/detailPage/related-entities/RelatedEntitiesSectionHeader/RelatedEntitiesSectionHeader.jsx
context/app/static/js/components/detailPage/related-entities/RelatedEntitiesSectionWrapper/RelatedEntitiesSectionWrapper.jsx
context/app/static/js/components/detailPage/related-entities/RelatedEntitiesSectionWrapper/style.js
context/app/static/js/components/publications/PublicationCollections/PublicationCollections.jsx
context/app/static/js/components/publications/PublicationCollections/styles.js
context/app/static/js/components/publications/PublicationRelatedEntities/PublicationRelatedEntities.jsx
context/app/static/js/components/publications/PublicationsDataSection/PublicationsDataSection.jsx
context/app/static/js/hooks/useDatasetsCollections.js
context/app/static/js/pages/Publication/Publication.jsx

Feels a bit messy, but it works.
Publication with datasets
Publication with collection

John conroy/publication associated collection HMP-256

---

CHANGELOG-remove-internet-pub-citation.md
context/app/static/js/components/publications/PublicationCitation/PublicationCitation.jsx

John conroy/remove internet pub citation HMP-272

---

CHANGELOG-derived-entities-spacing.md
context/app/static/js/components/detailPage/related-entities/RelatedEntitiesSectionWrapper/RelatedEntitiesSectionWrapper.jsx

John conroy/derived entities spacing HMP-274

---

CHANGELOG-fix-collection-datasets-links.md
context/app/static/js/components/detailPage/CollectionDatasetsTable/hooks.js

John conroy/fix collection datasets links HMP-277

---

context/app/static/js/components/detailPage/BulkDataTransfer/hooks.js
context/app/static/js/components/detailPage/BulkDataTransfer/usePanelSet.jsx

There's lots of room for refactoring and we've filed https://hms-dbmi.atlassian.net/jira/software/projects/HMP/issues/HMP-279 to do so, but this felt like the quickest way to get this in given the deadline.

Handle entity api failure for globus link

---

context/app/static/js/components/detailPage/BulkDataTransfer/BulkDataTransferPanel.jsx

Fix bulk data icon color

---

CHANGELOG-fix-globus-tooltip.md
context/app/static/js/components/detailPage/BulkDataTransfer/usePanelSet.jsx

Update tooltips and public data title to reflect design.

John conroy/fix globus tooltip HMP-291

---

CHANGELOG-HMP-255-rename-lightbluelink-to-internallink.md
context/app/static/js/components/Footer/Footer.jsx
context/app/static/js/components/cells/DatasetTableRow/DatasetTableRow.jsx
context/app/static/js/components/detailPage/BulkDataTransfer/usePanelSet.jsx
context/app/static/js/components/detailPage/SampleTissue/SampleTissue.jsx
context/app/static/js/components/detailPage/SupportAlert/SupportAlert.jsx
context/app/static/js/components/detailPage/files/FilesConditionalLink/style.js
context/app/static/js/components/detailPage/provenance/ProvGraph/ProvGraph.jsx
context/app/static/js/components/detailPage/related-entities/RelatedEntitiesTable/RelatedEntitiesTable.jsx
context/app/static/js/components/entity-search/ResultsTable/ResultsTable.jsx
context/app/static/js/components/error/ErrorBody/ErrorBody.jsx
context/app/static/js/components/organ/Assays/Assays.jsx
context/app/static/js/components/organ/Samples/Samples.jsx
context/app/static/js/components/savedLists/EditSavedStatusDialog/EditSavedStatusDialog.jsx
context/app/static/js/components/savedLists/NoItemsSaved/NoItemsSaved.jsx
context/app/static/js/components/savedLists/SavedEntitiesTable/SavedEntitiesTable.jsx
context/app/static/js/components/searchPage/ResultsTable/ResultsTable.jsx
context/app/static/js/components/searchPage/SearchNote.jsx
context/app/static/js/pages/Dataset/Dataset.jsx
context/app/static/js/pages/Publications/Publications.jsx
context/app/static/js/pages/Sample/Sample.jsx
context/app/static/js/pages/Services/Services.jsx
context/app/static/js/pages/Workspaces/Workspaces.jsx
context/app/static/js/shared-styles/Links/OutboundLink.jsx
context/app/static/js/shared-styles/Links/iconLinks/IconLink/IconLink.jsx
context/app/static/js/shared-styles/Links/iconLinks/IconLink/style.js
context/app/static/js/shared-styles/Links/index.js
context/app/static/js/shared-styles/buttons/LinkButton/LinkButton.jsx
context/app/static/js/shared-styles/panels/Panel/style.js
context/app/static/js/shared-styles/panels/index.js

Made sure to check all the files where the name change is taking place. 
Also changed 2 files that had custom style "FlexLightblueLink" to "FlexInternalLink".

kevin-yoo/hmp-255-rename lightbluelink to internallink

---

CHANGELOG-fix-publication-swr.md
context/app/static/js/components/publications/PublicationVignette/hooks.ts

Sorry I introduced this in #3200. It got through our type checks, tests and QA which is troubling.

John conroy/fix publication swr

---

context/app/static/js/components/entity-search/MetadataMenu/MetadataMenu.jsx
context/app/static/js/components/entity-search/MetadataMenu/hooks.js
context/app/static/js/components/entity-search/Search/Search.jsx
context/app/static/js/components/entity-search/Search/hooks.js
context/app/static/js/components/entity-search/SearchWrapper/utils.js
context/app/static/js/components/organ/Samples/Samples.jsx
context/app/static/js/components/workspaces/CreateWorkspaceDialog/CreateWorkspaceDialog.jsx
context/app/static/js/helpers/queries.js
context/app/static/js/pages/Workspaces/Workspaces.jsx
context/app/static/js/shared-styles/DialogModal/DialogModal.jsx
context/app/static/js/shared-styles/alerts/index.js

This branch is chained from https://github.com/hubmapconsortium/portal-ui/pull/3215 (hmp 157 kevin-yoo/add-error-message). Alignment has also been fixed. 
Second scenario is when we have selected protected datasets
Third scenario when both error conditions are met

Kevin yoo/implement error message for protected datasets v2

---

CHANGELOG-hmp-330-fix.md
context/app/static/js/components/cells/AutocompleteEntity/AutocompleteEntity.jsx

This PR fixes the display of selected genes in the molecular data search page.

NickAkhmetov/HMP-330 Fix display of selected genes

---

CHANGELOG-revert-matomo-tracking-changes.md
context/app/routes_auth.py
context/app/static/js/helpers/trackers.js
context/app/test_routes_main.py
context/requirements.in
context/requirements.txt

This reverts commit abfe2d8344370b6191c54fb4a9307cf37fb806e2 to address login issue.

Revert "NickAkhmetov/HMP-350 Matomo tracking improvements (#3234)"

---

CHANGELOG-HMP-441.md
context/app/static/js/components/workspaces/hooks.js

This PR introduces a hook we will be able to use to implement the designs for HMP-441. Given we have a few workspaces-related PR's currently in progress, I am adding this separately to minimize the odds of any serious merge conflicts.

NickAkhmetov/HMP-441 `useHasRunningWorkspaces` hook

---

CHANGELOG-HMP-302-Implement-icons-for-entity-headers-and-tables-Swedlow-feedback-response.MD
CHANGELOG-fix-dependencies-in-push.md
context/app/markdown/dependencies.md
etc/build/push.sh

Fix push script to once again stage changes to dependencies markdown. Remove un-merged changelog due to `.MD` extension.

John conroy/fix dependencies in push

---

CHANGELOG-fix-chart-legend-alignment.md
context/app/static/js/shared-styles/charts/ChartWrapper/ChartWrapper.jsx

John conroy/fix chart legend alignment HMP-477

---

CHANGELOG-ws-dialog-tables.md
context/app/static/js/components/organ/Samples/Samples.tsx
context/app/static/js/components/workspaces/NewWorkspaceDialog/NewWorkspaceDialog.tsx
context/app/static/js/components/workspaces/NewWorkspaceDialog/NewWorkspaceDialogFromSelections.tsx
context/app/static/js/components/workspaces/WorkspaceDatasetsTable/WorkspaceDatasetsTable.tsx
context/app/static/js/components/workspaces/WorkspaceDatasetsTable/index.ts
context/app/static/js/shared-styles/buttons/TooltipButton/TooltipIconButton.tsx
context/app/static/js/shared-styles/buttons/TooltipButton/index.ts
context/app/static/js/shared-styles/tables/SelectableTableProvider/SelectableTableProvider.tsx
context/app/static/js/shared-styles/tables/actions.tsx
context/app/static/js/shared-styles/tables/columns.tsx
context/app/static/js/typings/search.ts

Towards HMP-398. Introduces the datasets table to the dialog.

John conroy/ws dialog tables

---

CHANGELOG-workspace-detail-auth.md
context/app/static/js/components/workspaces/WorkspacesAuthGuard/WorkspacesAuthGuard.tsx
context/app/static/js/components/workspaces/WorkspacesAuthGuard/index.ts
context/app/static/js/pages/Workspace/Workspace.tsx
context/app/static/js/pages/Workspaces/Workspaces.jsx
context/app/static/js/pages/Workspaces/style.js
context/app/static/js/shared-styles/sections/Description/Description.jsx
context/app/static/js/shared-styles/sections/Description/style.js

- Add authentication guard to workspace page.

John conroy/workspace detail auth

---

CHANGELOG-hide-templates.md
context/app/static/js/components/workspaces/NewWorkspaceDialog/hooks.ts
context/app/static/js/components/workspaces/types.ts

Do not display workspace templates with designated `is_hidden` bool.

John conroy/hide templates HMP-507

---

CHANGELOG-inconsistent-workspace-files.md
context/app/static/js/components/workspaces/types.ts
context/app/static/js/components/workspaces/utils.ts
context/app/static/js/pages/Workspace/Workspace.tsx

Temp fix until we narrow down file structure with Juan.

John conroy/inconsistent workspace files

---

CHANGELOG-fusion-link.md
context/app/static/js/components/Header/DropdownLink/DropdownLink.tsx
context/app/static/js/components/Header/staticLinks/staticLinks.tsx
context/app/static/js/hooks/useTrackOutboundLink.ts
context/app/static/js/shared-styles/Links/OutboundLink.tsx
context/app/static/js/shared-styles/Links/OutboundLinkButton.tsx

John conroy/fusion link HMP-539

---

CHANGELOG-icon-link-alignment.md
context/app/static/js/shared-styles/Links/InternalLink.tsx

John conroy/icon link alignment HMP-541

---

CHANGELOG-fix-missing-viz.md
CHANGELOG-viz-lift-with-hints.md
context/app/api/client.py
context/app/api/test_client.py

Determine support entity to 'viz-lift' by presence of `is_support` in `vitessce-hints`.

John conroy/viz lift with hints CAT-153

---

CHANGELOG-fix-dev-search-hierarchical.md
context/app/static/js/components/searchPage/filters/AccordionFilter/AccordionFilter.jsx
context/app/static/js/components/searchPage/utils.js
context/app/static/js/pages/search/DevSearch.jsx

Fix hierarchical facets on dev search.

John conroy/fix dev search hierarchical

---

CHANGELOG-fix-hierarchical-size-and-order.md
context/app/static/js/components/searchPage/HierarchicalMenuFilter/HierarchicalFacetAccessor.js

@tsliaw You might want to take a look at this locally. The list is a bit longer now especially with multiple options expanded.

John conroy/fix hierarchical size and order

---

.github/workflows/codeql-analysis.yml
.github/workflows/cypress-maintenance-ci.yml
.github/workflows/cypress-portal-ci.yml
.github/workflows/misc-ci.yaml
.github/workflows/node-ci.yml
.github/workflows/python-ci.yml
CHANGELOG-fix-flake8.md
context/app/routes_cell_types.py

Remove unused import to resolve flake8 failure in Python CI workflow step.

Remove unused import to resolve flake8 failure.

---

CHANGELOG-fix-publication-test.md
CHANGELOG-multi-assay-provenance.md
context/app/static/js/components/Contexts.tsx
context/app/static/js/components/detailPage/multi-assay/MultiAssayProvenance/MultiAssayProvenance.tsx
context/app/static/js/components/detailPage/multi-assay/MultiAssayProvenance/index.ts
context/app/static/js/components/detailPage/multi-assay/useRelatedMultiAssayDatasets.ts
context/app/static/js/components/detailPage/provenance/ProvTabs/ProvTabs.jsx
context/app/static/js/components/detailPage/provenance/ProvTabs/filterTabsToDisplay.spec.ts
context/app/static/js/components/detailPage/provenance/ProvTabs/filterTabsToDisplay.ts
end-to-end/cypress/e2e/portal/publication-page.cy.js

I am deferring adding the processed dataset icon for the time being.

John conroy/multi assay provenance CAT-594 CAT-584

---

CHANGELOG-container-arch.md
CHANGELOG-fix-build.md
context/Dockerfile
context/app/markdown/CHANGELOG.md

Explicitly sets the container image architecture to amd64.

Explicitly set container image architecture.

---

CHANGELOG-fix-ws-create-errors.md
context/app/static/js/components/workspaces/NewWorkspaceDialog/hooks.ts
context/app/static/js/components/workspaces/hooks.ts
context/app/static/js/helpers/swr/errors.ts
context/app/static/js/helpers/swr/fetchers.ts

Fix unhandled errors if any of the parallel requests to the templates API fail. Filed a ticket to make toasts a stack.

John conroy/fix ws create errors

---

CHANGELOG-spatial-data-preview.md
context/app/preview/3d-maps.md
context/app/static/js/components/Header/staticLinks/staticLinks.tsx
context/package-lock.json
context/package.json

This PR adds the 3D spatial data preview and updates Vitessce to 3.4.2.

NickAkhmetov/CAT-637 Add 3D maps preview, bump vitessce

---

CHANGELOG-3d-tissue-maps.md
context/app/preview/3d-tissue-maps.md
context/app/static/js/components/Header/staticLinks/staticLinks.tsx
context/app/static/js/components/detailPage/visualization/Visualization/Visualization.jsx
context/package-lock.json
context/package.json
context/requirements.in
context/requirements.txt

This PR:
- Fixes spatial view scrolling
- Adjusts titles/page names based on Nils's feedback
- Updates the version of the cells API client
I'm waiting for the Vitessce v3.4.3 release to come out to update that version as well in order to fix a selection bug in the preview.

NickAkhmetov/HOTFIX - Iterations for 3d tissue maps preview, fix cell client being missing

---

CHANGELOG-vitessce-3.4.5.md
context/package-lock.json
context/package.json

This PR bumps Vitessce to v3.4.5, which fixes some visual bugs in the 3D spatial data preview.

NickAkhmetov/Bump Vitessce to 3.4.5

---

CHANGELOG-fix-xs-templates-grid.md
context/app/static/js/components/workspaces/TemplateGrid/TemplateGrid.tsx

John conroy/fix xs templates grid CAT-654

---

CHANGELOG-fix-searchkit-source.md
context/app/static/js/components/searchPage/SearchWrapper.jsx

Will fix underlying request issue in follow-up PR.

John conroy/fix searchkit source

---

CHANGELOG-large-request-s3.md
context/app/static/js/components/searchPage/SearchTransport.ts
context/app/static/js/components/searchPage/SearchWrapper.jsx
context/app/static/js/helpers/swr/fetchers.ts
context/app/static/js/hooks/useSearchData.js
context/app/static/js/pages/search/CellsSearch.jsx
context/app/static/js/pages/search/DevSearch.jsx
context/app/static/js/pages/search/Search.jsx

Update search hooks to handle 303s to s3.

John conroy/large request s3

---

CHANGELOG-fix-entity-tiles.md
context/app/static/js/components/entity-tile/EntityTile/EntityTile.tsx
context/app/static/js/components/entity-tile/EntityTileBody/EntityTileBody.tsx
context/app/static/js/components/types.ts

Updated the type for the entity passed to the variants of `checkEntityType` so this should be caught in the future.

John conroy/fix entity tiles

---

CHANGELOG-workspaces-hackathon-fixes.md
context/app/static/js/components/workspaces/AdvancedConfigOptions/AdvancedConfigOptions.tsx
context/app/static/js/components/workspaces/NewWorkspaceDialog/NewWorkspaceDialogFromExample.tsx
context/app/static/js/components/workspaces/NewWorkspaceDialog/hooks.ts
context/app/static/js/components/workspaces/SelectableTemplateGrid/SelectableTemplateGrid.tsx
context/app/static/js/components/workspaces/TemplateGrid/TemplateGrid.tsx
context/app/static/js/components/workspaces/TemplateSelectStep/TemplateSelectStep.tsx
context/app/static/js/components/workspaces/types.ts
context/app/static/js/hooks/useCopyText.ts
context/app/static/js/pages/Template/Template.tsx

[CAT-906](https://hms-dbmi.atlassian.net/browse/CAT-906?atlOrigin=eyJpIjoiYWZhMDA0YzYwMzgwNDlmMTkzZmNkMjQxM2FiYTIzYzQiLCJwIjoiaiJ9): Broken "Copy HuBMAP IDs button"
[CAT-909](https://hms-dbmi.atlassian.net/browse/CAT-909?atlOrigin=eyJpIjoiMTRjZDQwMTI3MTM3NGQzM2JhZmEyZWU0ZjJiNmY3OWUiLCJwIjoiaiJ9): Too many marks on Advanced Config slider
**Before:**
**After:**
[CAT-910](https://hms-dbmi.atlassian.net/browse/CAT-910?atlOrigin=eyJpIjoiNDNkY2JjMzIyNGRhNDEyNWI3ODViNjhmMWVkYTM5YTMiLCJwIjoiaiJ9): Unnecessary tooltip on template grid
**Before:**
**After:**
[CAT-911](https://hms-dbmi.atlassian.net/browse/CAT-911?atlOrigin=eyJpIjoiN2Q5NWNmZjM3YzczNDMyN2E0ZDI5OGZiMTEwMjA3MWQiLCJwIjoiaiJ9): Incorrect job type for template example
**Before:**
**After:**
[CAT-906]: …

Austenem/Workspaces hackathon fixes (CAT-906, CAT-909, CAT-910, & CAT-911) 

---

CHANGELOG-fix-donors.md
context/app/static/js/components/detailPage/entityHeader/EntityHeaderContent/EntityHeaderContent.tsx
context/app/static/js/components/detailPage/utils.ts

Fix bug reported by Brendan where donor pages for donors without metadata are erroring.

John conroy/fix donors

---

context/app/static/js/components/search/Facets/FilterChips.tsx
context/app/static/js/components/search/Facets/TermFacet.tsx
context/app/static/js/components/search/Search.tsx
context/app/static/js/components/search/store.ts
context/app/static/js/components/search/useScrollSearchHits.ts

Adds button to reset filters on the search page.

John conroy/reset all filters

---

context/app/static/js/components/search/Facets/DateRangeFacet.tsx
context/app/static/js/components/search/Facets/Facets.tsx
context/app/static/js/components/search/Facets/FilterChips.tsx
context/app/static/js/components/search/Facets/RangeFacet.tsx
context/app/static/js/components/search/Facets/TermFacet.tsx
context/app/static/js/components/search/Results/ResultsTable.tsx
context/app/static/js/components/search/Search.tsx
context/app/static/js/components/search/fieldConfigurations.ts
context/app/static/js/components/search/store.ts
context/app/static/js/components/search/utils.ts
context/app/static/js/pages/search/S.tsx
context/jest.config.js
context/package-lock.json
context/package.json

-  Adds date facets to search pages.
- Replaces `last_modified_timestamp` with `created_timestamp` for samples and donors.
- Replaces `last_modified_timestamp` with `published_timestamp` for non-HuBMAP users.
- Shows both `last_modified_timestamp` and `published_timestamp` facets for HuBMAP users.

John conroy/date facets CAT-971

---

CHANGELOG-fix-missing-publication-dates.md
context/app/static/js/components/publications/PublicationRelatedEntities/hooks.ts

Fixes missing publication dates for datasets on Publication pages.
[CAT-1044 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-1044?atlOrigin=eyJpIjoiOTQ0ZDk4ZDY0MmQ4NDQxN2EyOGRjNWJiNTBlNDIwNzQiLCJwIjoiaiJ9)
Prod:
Local:

Austenem/CAT-1044 Fix missing publication dates

---

CHANGELOG-update-workspace-instructions.md
context/app/static/js/shared-styles/alerts/LoginAlert.tsx

Update Workspaces feature access instructions to include help desk link.
[CAT-1057 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-1057?atlOrigin=eyJpIjoiMWFjZDE1NDlkNGVhNGM1OGI1MGVjY2U2ZDgyNTczNzYiLCJwIjoiaiJ9)

Austenem/CAT-1057 Update workspace instructions

---

CHANGELOG-upgrade-portal-viz-0.3.3.md
context/requirements.in
context/requirements.txt

- Update portal-visualization to 0.3.3 which replaces calls to ingest-api with calls to search-api.

John conroy/upgrade portal viz 0.3.3

---

CHANGELOG-update-portal-vis.md
context/requirements.in
context/requirements.txt

This PR updates the portal-viz version to address the image scaling issue.
[CAT-1102](https://hms-dbmi.atlassian.net/browse/CAT-1102)
Manually tested with various dev datasets.
[CAT-1102]: https://hms-dbmi.atlassian.net/browse/CAT-1102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Updated portal-viz version to address scaling issue

---

CHANGELOG-update-vitessce.md
context/package-lock.json

There was an infinite loop error with EPIC segmentation mask visualization and updating the vitessce package worked. This was done in a previous PR as well, but somehow the changes did not get merged. Is this the right way to update the package 
I did `npm update vitessce` inside context directory.
Link to any design documents, diagrams, or JIRA tickets relevant to this feature.
Describe how the feature has been tested, including both automated and manual testing strategies.
Before
After

Updated vitessce

---

CHANGELOG-update-files-section.md
context/app/static/js/components/detailPage/ProcessedData/HelperPanel/HelperPanel.tsx
context/app/static/js/components/detailPage/ProcessedData/ProcessedDataset/ProcessedDataset.tsx
context/app/static/js/shared-styles/sections/SectionDescription.tsx

Updates processed dataset files section with link to Bulk Data Transfer section. Also updates title of helper panel button from "Bulk Download" to "Bulk Data Transfer".
[CAT-860 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-860?atlOrigin=eyJpIjoiMWNhOTBkNTA4NGMzNDk3NDkzODk4OTJkZjE0YWE1MjQiLCJwIjoiaiJ9)
Local:
Prod:

Austenem/CAT-860 Update files section

---

CHANGELOG-fix-donor-blood-charts.md
context/app/static/js/pages/Diversity/Diversity.jsx
context/app/static/js/pages/Diversity/DonorChart.jsx
context/app/static/js/pages/Diversity/utils.js
context/package-lock.json
context/package.json

- Use new `abo_blood_group_system` field in donor charts.

John conroy/fix blood key CAT-1177

---

CHANGELOG-update-my-lists-language.md
context/app/static/js/components/savedLists/SavedListsDescription/SavedListsDescription.tsx

Updates description on My Lists page for non-HuBMAP users.
[CAT-1184 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-1184?atlOrigin=eyJpIjoiMzc3YTkwMTEwNGE5NDE5ZjkzZWRhOWRmZTUxOGVkMTciLCJwIjoiaiJ9)
Logged out users:
Non-HuBMAP logged in users:
HuBMAP logged in users:

Austenem/CAT-1184 Update my lists language

---

CHANGELOG-cat-1141.md
context/app/static/js/components/home/Hero/const.tsx

This PR updates the items in the homepage news section.
https://hms-dbmi.atlassian.net/wiki/spaces/GL/pages/3536748545/Homepage+Latest+Changes+Entries
Manual testing
I omitted the day of month for the sake of consistency, since all the other dates do not include the day of month. Adding the day also makes the text wrap.

NickAkhmetov/CAT-1411 Update homepage items

---

CHANGELOG-lateral-organs-data-products.md
context/app/static/js/pages/Organ/Organ.tsx
context/app/static/js/pages/Organ/hooks.ts

Show data products for organ pages with laterality.
[CAT-1193 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-1193?atlOrigin=eyJpIjoiNzFlZGIyZTEzZmU4NGE5MzgwOWIwZWY5OGZhN2U3YjkiLCJwIjoiaiJ9)
Checked for lateral and non-lateral organs and for pages with and without data products.
Local:

Austenem/CAT-1193 Lateral organs data products

---

CHANGELOG-update-toggle-color.md
context/app/static/js/shared-styles/switches/PrimarySwitch.tsx

Updates toggle color in Advanced Config and Bulk Download dialogs for clarity.
[CAT-1047 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-1047?atlOrigin=eyJpIjoiMGQwMWE1ZDMyY2M5NDViNTg0ZTZhOTFiMWU0YzA1MmYiLCJwIjoiaiJ9)

Austenem/CAT-1047 Update toggle color

---

CHANGELOG-fix-snareseq2-banner.md
context/app/static/js/components/detailPage/multi-assay/SnareSeq2Alert/SnareSeq2Alert.tsx

Fixes text on SnareSeq2 info banners.
[CAT-1244 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-1244?atlOrigin=eyJpIjoiNDcxNWI3NjZiOTg5NDIzZDkzZjQyYzMyMjhlM2RjZWQiLCJwIjoiaiJ9)
Describe how the feature has been tested, including both automated and manual testing strategies.

Austenem/CAT-1244 Fix SnareSeq2 banner

---

CHANGELOG-minor-fixes.md
context/app/routes_main.py
context/app/static/js/components/detailPage/BulkDataTransfer/BulkDataTransferSection.tsx
context/app/static/js/components/home/Title/Title.tsx

Three minor updates/bug fixes are addressed in this PR:
- Updated homepage description language.
- Updated tab styling in Bulk Data Transfer section to only be scrollable when necessary.
- Added collections landing page metadata description.
[CAT-1211](https://hms-dbmi.atlassian.net/browse/CAT-1211?atlOrigin=eyJpIjoiMzgzNjU0YWZiOTIzNDEwMmE5OTA0NjMzZDZhNDA0OGMiLCJwIjoiaiJ9): Homepage description
[CAT-1245](https://hms-dbmi.atlassian.net/browse/CAT-1245?atlOrigin=eyJpIjoiYTAyMDkxMzRkODRjNDIzMmI4MGMxNDI2ZDYxMjA1NDMiLCJwIjoiaiJ9): Tab styling
[CAT-1246](https://hms-dbmi.atlassian.net/browse/CAT-1246?atlOrigin=eyJpIjoiNDRhMGFlZDRiZDBjNDljZjljYzYxZGQ5MTNjMjg2NTAiLCJwIjoiaiJ9): Collections metadata
Homepage description:
Tab styling (local):
Tab styling (on prod):
[CAT-1211]: …

Austenem/CAT-1245 Minor fixes

---

CHANGELOG-update-whats-new.md
context/app/static/js/components/home/Hero/const.tsx
context/app/static/js/components/search/store.ts

Update "What's New" section of the homepage for March and April.
[CAT-1255 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-1255?atlOrigin=eyJpIjoiNzI1YjI2NWI3OGM2NDQwZWE0YTA4NDZmZGE1ODE4NWMiLCJwIjoiaiJ9)
[Homepage Latest Changes](https://hms-dbmi.atlassian.net/wiki/spaces/GL/pages/3536748545/Homepage+Latest+Changes+Entries)

Austenem/CAT-1255 Update What's New

---

CHANGELOG-enhance-sitemap.md
context/app/routes_browse.py

Updates portal sitemap to include all relevant landing and detail pages.
[CAT-1186 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-1186?atlOrigin=eyJpIjoiMTE0MDRlMjk2N2Q0NDg0ZmFlYWEzYmM0NTcxZDhlNDciLCJwIjoiaiJ9)
[CAT-1196 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-1196?atlOrigin=eyJpIjoiNDJkMTBiZGFmMGRlNGU3NmI5MmVlM2FkZTFlM2ZhYjYiLCJwIjoiaiJ9)
Check http://localhost:5001/sitemap.txt

Austenem/CAT-1186 Enhance sitemap

---

CHANGELOG-update-publication-headers.md
context/app/static/js/components/detailPage/DetailPageSection/CollapsibleDetailPageSection.tsx
context/app/static/js/components/detailPage/summary/SummaryData/SummaryData.tsx
context/app/static/js/components/detailPage/summary/SummaryData/style.ts
context/app/static/js/components/detailPage/summary/SummaryTitle/SummaryTitle.tsx

Update publication header tags for SEO.
[CAT-1215 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-1215?atlOrigin=eyJpIjoiNDUxNTFmNjU5N2EyNGQyZWE0Njk3ODg5ZDQ3Yzg2NDQiLCJwIjoiaiJ9)

Austenem/CAT-1215 Update publication headers

---

CHANGELOG-okn-fixes.md
context/app/static/js/components/OpenKeyNavInitializer.jsx
context/app/static/js/components/Providers.jsx
context/app/static/js/components/profile/MyPreferences.tsx
context/app/static/js/components/profile/Summary/Summary.tsx
context/app/static/js/components/profile/Summary/Title.tsx
context/app/static/js/fonts.tsx
context/app/static/js/pages/Profile/Profile.tsx
context/app/static/js/shared-styles/alerts/Alert.tsx
context/app/static/js/shared-styles/alerts/LoginAlert.tsx
context/app/static/js/stores/useOpenKeyNavStore.ts
context/package-lock.json
context/package.json

Address bugs related to OpenKeyNav integration.

John conroy/okn fixes CAT-650 CAT-1283 CAT-1284

---

CHANGELOG-EUI-release-fix.md
CHANGELOG-update-eui.md
context/app/static/js/hooks/useScript.ts
context/app/templates/special-pages/ccf-eui.html
context/app/templates/special-pages/organ.html

Minor update to fix EUI on production 
Link to any design documents, diagrams, or JIRA tickets relevant to this feature.
Describe how the feature has been tested, including both automated and manual testing strategies.

🚨Fix to update the EUI to the latest version

---

CHANGELOG-update-portal-viz.md
context/requirements.in
context/requirements.txt

This PR updates portal-viz to reflect the support for multi-level annotations from the Pan-Azimuth pipeline
[CAT-1289](https://hms-dbmi.atlassian.net/browse/CAT-1289)
Tested when building the config using portal-viz
Dataset on Sennet: https://data.dev.sennetconsortium.org/dataset?uuid=2312f4ee323e1778135c3ec74165cc36/
[CAT-1289]: https://hms-dbmi.atlassian.net/browse/CAT-1289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Updated portal-viz version

---

CHANGELOG-cat-1342.md
context/app/static/js/components/detailPage/visualization/VisualizationTracker/hooks.ts
context/app/static/js/components/organ/CellPop/hooks.ts
context/app/static/js/helpers/trackers.js

This PR disables matomo tracking for vitessce and matomo.
N/A

NickAkhmetov/CAT-1342 Remove matomo tracking for cellpop/vitessce

---

CHANGELOG-scfind-uuid-support.md
context/app/static/js/api/scfind/useFindDatasetForCellTypes.ts
context/app/static/js/api/scfind/useFindDatasetForGenes.ts
context/app/static/js/api/scfind/utils.ts
context/app/static/js/components/biomarkers/BiomarkersPanelItem.tsx
context/app/static/js/components/biomarkers/BiomarkersPanelList.tsx
context/app/static/js/components/cell-types-landing/CellTypesPanelItem.tsx
context/app/static/js/components/cell-types/hooks.tsx
context/app/static/js/components/cells/CellsCharts/CellTypesChart.tsx
context/app/static/js/components/cells/SCFindResults/SCFindCellTypeQueryResults.tsx
context/app/static/js/components/cells/SCFindResults/SCFindGeneQueryResults.tsx
context/app/static/js/components/genes/CellTypes/GeneCellTypes.tsx
context/app/static/js/components/organ/OrganCellTypes/IndexedDatasetsSummary.tsx
context/app/static/js/components/organ/OrganCellTypes/ViewIndexedDatasetsButton.tsx
context/app/static/js/components/organ/hooks.ts
context/app/static/js/components/organ/utils.ts
context/app/static/js/components/search/Facets/FilterChips.tsx
context/app/static/js/components/search/Search.tsx
context/app/static/js/components/search/store.ts
context/app/static/js/helpers/swr/fetchers.ts
context/app/static/js/pages/Biomarkers/Biomarkers.tsx
context/app/static/js/pages/Organ/hooks.ts
context/app/static/js/shared-styles/tables/columns.tsx

This PR
* Updates the handling for all scFind endpoint inputs and outputs to use UUIDs instead of HBM IDs
* Sets the current scFind index version to the UUID-based one as a hard-coded default until all indices are identically formatted with capitalized organ names and UUIDs instead of HBM IDs
* Adds a multi-value filter chip and appropriate messaging to clarify what users are viewing if they are linked from an scFind "view datasets" link
https://hms-dbmi.atlassian.net/browse/CAT-1339
Manually tested landing/detail pages for organs, genes, and cell types. Manually tested search page by linking out to it from existing functionalities.
<details><summary>Search page when viewing all 162 scFind-indexed datasets</summary>
<p>
</p>
</details> 
<details><summary>Search page when viewing B Cell …

CAT-1339 NickAkhmetov/SCFind index update/search improvements

---

CHANGELOG-update-whats-new.md
context/app/static/js/components/home/Hero/const.tsx

Update What's New homepage section with July changes.
[CAT-1335 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-1335?atlOrigin=eyJpIjoiMjU0ZjFmNTRmNTBiNDdhOWFjNzllYjlmZjk4Yzc2N2QiLCJwIjoiaiJ9)

Austenem/CAT-1335 Update What's New

---

CHANGELOG-portal-vis.md
context/requirements.in
context/requirements.txt

see https://github.com/hubmapconsortium/portal-visualization/pull/131

NickAkhmetov/CAT-1419 Bump portal-visualization
