hubmapconsortium/portal-ui

CHANGELOG.md
README.md
compose/README.md
compose/base.yml
compose/dev.yml
context/app/routes_auth.py
example-app.conf

@mccalluc I finally got a chance to checkout the modifications you made based on PR #77 and thanks for incorporating the deployment changes. I like the idea of pulling from DockerHub image for testing deployment with docker-compose. This way, you'll have control to make all the code changes and push the updated image (with a release version/tag) to DockerHub. Then I'll just pull the updated docker-compose files for deployment on testing server.
My PR includes:
- fix to the volume mount path for `app.conf`. Since you moved the docker-compose yaml files to its own directory 'compose/', the path to `app.conf` needs to be updated as well.
- due to the error with globus settings, I couldn't use either port 5001 or 8686 for local dev compose settings, so I changed to port 5000, which is in the …

Docker compose fix

---

CHANGELOG.md
README.md
compose/README.md
compose/base.yml
compose/dev-volumes/nginx/nginx.conf
compose/dev.yml
compose/test.yml
example-app.conf
push.sh

Fix #89
The important part is `proxy_set_header  Host $http_host;` in the nginx config: No changes required in the flask code.
I've also changed dev to build from source rather than relying on image. Conceivably, you could do this for test, too, but I think the docker images make things more predictable.
I'll go ahead and merge, but will ping you and Bill on Slack: It'd be really nice to have this up on your infrastructure by Friday morning.

fix compose

---

context/app/api/client.py
context/app/default_config.py
context/app/routes_main.py
context/app/templates/pages/search.html
context/app/test_routes_main.py
context/requirements.txt
example-app.conf

With this, elastic search is being used for detail pages. It's a little confusing but the faceted search goes straight to ES, while the details page uses a python client. It took me a little white to figure out the mocking... not sure I'm using it the best way. This fixes #138, but #113 is still waiting: ES is not yet in the gateway.

Elastic search used for detail pages

---

CHANGELOG.md

Updated release to v0.0.11. Merged release branch early. Here is the current example-app.conf for reference:
```
SECRET_KEY = 'abc123!'
APP_CLIENT_ID = 'TODO'
APP_CLIENT_SECRET = 'TODO'
GROUP_ID = '5777527e-ec11-11e8-ab41-0af86edb4424'
ELASTICSEARCH_ENDPOINT = 'https://search-api.dev.hubmapconsortium.org/search'
IS_MOCK = True
```

Release branch

---

CHANGELOG.md
context/app/default_config.py
example-app.conf

@yuanzhou : I think the change in default_config.py is what you wanted? Fix #172. Merge if it looks good to you.

Remove active API url from default config

---

CHANGELOG.md
context/app/static/js/App.jsx
context/app/static/js/components/NoticeAlert.jsx
context/app/static/js/header.jsx

There was a bug in NoticeAlert that was causing a null error so that content would not load in the react version since if the url for the error did not exist it was failing. This push should fix these issues: #177 and #176. I also changed the 'Assays' in the header to say 'Datasets' instead.

Fixed React

---

CHANGELOG.md
context/app/routes_main.py
context/app/test_routes_main.py

Fix #92. @ilan-gold, besides the code, does this seem like the right thing to do?
- Not a replacement for pointing people to the right url from search (#184 / #178), but seems like good thing in its own right.
- Just above the added lines, there's still a 404 if the entity type is unrecognized... Should I get rid of that? 
- Default is 302... but we could send a 301... But permanent redirects can be very annoying, if you ever get them wrong.

Redirect to the right type, if we are on the wrong one

---

CHANGELOG.md
context/app/templates/pages/search.html

Fix #184. Fix #178. In time, this can be moved into the webpacked code, but not needed for this one issue.
@tsliaw : Let me know if you have questions about how you would use this to fill in the details for different types, or if it's good, approve.

Allow different filters and columns depending on type

---

CHANGELOG.md
context/app/static/js/components/PortalSearch/PortalSearch.jsx

Really just removes wrapping element. Seems to work fine without it.
Before and after:

Remove <Layout> to get rid of border. Fix #264

---

CHANGELOG.md
context/app/routes_main.py

Started flask without `FLASK_ENV=development` and there are no warnings ... start it with the envvar, and there are warnings. Fix #271

only validate in development mode

---

CHANGELOG.md
context/app/static/js/components/Search/utils.js
context/webpack.config.js

That definitions.yaml is really the only thing in that repo that we'll need to reference, so just alias directly to it. Not clear that there's an established naming convention for aliases.

Webpack alias to tidy-up long relative path

---

CHANGELOG-fix-short-circuit.md
context/app/static/js/components/DatasetDetail.jsx
context/app/static/js/components/Detail/DetailLayout.jsx
context/app/static/js/components/SampleDetail.jsx

string.length is falsy and can cause a 0 to be displayed when used in a short circuit check. I'll further clean up the conditionals in the later refactoring PR. Fixes #367 .

John conroy/fix short circuit

---

CHANGELOG-use-es-id.md
context/app/api/client.py

This follows-up on the work they did for https://github.com/hubmapconsortium/search-api/issues/23. There should be an even simpler [get interface](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-get.html), but it seems they haven't white-listed it:
```
curl 'https://search-api.test.hubmapconsortium.org/search/_doc/2397fa14a6608ed31bfc57426d962c26'  -H 'Authorization: Bearer ...'
<html>
<head><title>401 Authorization Required</title></head>
<body>
<center><h1>401 Authorization Required</h1></center>
<hr><center>nginx/1.19.0</center>
```
I have been frustrated by the wrapper they've put on ES, but I think we need to pick our battles... but if you think this will cause more confusion in the long run, opening an issue isn't unreasonable.

Use _id field

---

CHANGELOG-pk-md.md
context/app/markdown/about.md

- This would be at `/about` ... Ok, or do you want something different?
- Should there be a link to this somewhere? Suggest speccing that in a separate issue, but could also be part of this PR: Your call.

Add docs from PK

---

CHANGELOG-oom.md
context/Dockerfile

- The first hits in google involve CLI options either to Node or NPM: These did not work for me, and I'm not sure why.
- I'm also not sure why we didn't get travis errors before this, which is disconcerting.

Fix #456: Node OOM during build

---

CHANGELOG-vitessce-z-index-expand-bug.md
context/app/static/js/components/Detail/Visualization/style.js

This should fix the z-index bug when Vitessce has been expanded.

Fix z-index bug when Vitessce expanded

---

CHANGELOG-search-css.md
context/app/static/js/components/Search/Search.css

I'm not sure why I had trouble seeing where the margin was coming from the first time I looked at it. Easy fix.

Less space at top of search page. Fix #265

---

CHANGELOG-showcase-dropdown-z-index.md
context/app/static/js/components/Header/ShowcaseDropdown/ShowcaseDropdown.jsx
context/app/static/js/components/Header/ShowcaseDropdown/style.js

Fixes #593 by adding a z-index of `5` to the ShowcaseDropdown popper component. Changes the direction of the arrow icon.

Fix ShowcaseDropdown bugs

---

CHANGELOG-readable-showcase-dataset-ids.md
context/app/showcase/satija.md

This pull request changes the `Satija` showcase dropdown option strings to HuBMAP IDs rather than Globus IDs to improve readability.
Towards #611

Use HuBMAP ID rather than Globus ID in dataset dropdown in showcase

---

context/app/markdown/docs.md
context/app/markdown/docs/faq.md

The actual FAQ is written by a cross-consortium team and will be delivered by the end of July 2020.

Create placeholder for FAQ and link from documentation overview

---

CHANGELOG-w-wo-metadata.md
context/app/markdown/docs/dev-tools.md
context/app/static/js/components/Search/Search.jsx
context/app/static/js/components/Search/utils.js

Revive ideas from #645, and add a docs page that helps you find items with or without metadata. (Possible to make a custom report like the one in slack, but that would be more work.)
Fix #757, I think.

Search for items with or without metadata

---

CHANGELOG-vitessce-please-wait.md
context/app/static/js/components/Detail/Visualization/style.js

This fixes the bug where the Vitessce "Please wait" modal is hidden when the Vitessce component is inline / not full-window.
I have a separate pull request in  Vitessce to change the modal to an animated loading spinner https://github.com/hubmapconsortium/vitessce/pull/651 (but this PR does not necessarily depend on that one)

Update styles to fix please wait bug

---

CHANGELOG-upgrade-lodash.md
context/package-lock.json
context/package.json

We're getting security warnings from Github urging us to upgrade lodash. There are no breaking changes.

John conroy/upgrade lodash

---

CHANGELOG-vitessce-imaging-generic.md
context/app/api/test_vitessce.py
context/app/api/vitessce.py

This should give us a generic view configuration for image pyramids that will allow users (especially Ivan) to spot check runs immediately.  This also cleans up the CODEX stuff a bit to match more what we have now for pyramids.
Here are some uuids to check that the view config works:
AF: ec27c2b6b5f177c0ca6387120d8736b0 (should work)
CODEX: 53f19f543429a03af5a6c0e333f593de (getting a 403 and not sure why, but the configuration looks right)
PAS: 2ce183e38a31ff1d836675d3b75654b0 (part of the image is cutoff, a known bug, and the colors are wrong which is because we don't have rgb handling yet in vitessce)

Image Pyramids

---

CHANGELOG-alert-no-prov.md
context/app/static/js/components/Detail/Dataset/Dataset.jsx
context/app/static/js/components/Detail/Donor/Donor.jsx
context/app/static/js/components/Detail/ProvSection/ProvSection.jsx
context/app/static/js/components/Detail/ProvSection/index.js
context/app/static/js/components/Detail/ProvTabs/ProvTabs.jsx
context/app/static/js/components/Detail/Sample/Sample.jsx
context/app/static/js/hooks/useProvData.js

Fixes #838.
- Used a guard clause instead of adding a short-circuit inside `ProvSection` jsx.
- Added `useProvData` hook which keeps state for both `provData` and `isLoading`. Is this an improvement to you? If so, we could probably create another hook, something like `useAsyncData`, to extract common code for hooks used to fetch data.
- I chose not to display a progress loader while data is loading, but could if you think it makes sense.

John conroy/alert no prov

---

CHANGELOG-help-404.md
context/app/static/js/components/Header/Menu/Menu.jsx

Remove bad link. If this could have been done with just CSS, that might have been good, but not something to worry about now.

Remove bad link. Fix #830

---

CHANGELOG-single_cell_viz.md
context/app/api/vitessce.py

As per our call earlier today, we only have output data for `SCRNA_SEQ_10X`, `SCRNA_SEQ_SCI`, `SCRNA_SEQ_SNARE`, and `SCATAC_SEQ_SNARE` but I got the rest of the names from Matt so they can be ready when he has run the pipelines (which have identical outputs).
Some examples:
http://localhost:5001/browse/dataset/1cc5eea18dd72ccb0b298d89a6d3d0ce
http://localhost:5001/browse/dataset/3a1ae519d4d92cc0b1bfc78f5360b93e
http://localhost:5001/browse/dataset/70cb9d3f6edbacefdb0917f244e57689
http://localhost:5001/browse/dataset/18c14ef9165c978a14256674158cc181
I know one of these has a not-so-great initial view but I would like to wait to see more data before making any decisions about that.

More Single Cell Assays

---

context/app/markdown/docs/submission.md

The HELP page will just show the contact info for those seeking help.

Moved text on submission instructions from HELP to SUBMISSION document

---

CHANGELOG-auto-open-link-after-dua-agree.md
context/app/static/js/components/Detail/FileBrowserFile/FileBrowserFile.jsx
context/app/static/js/components/Detail/Files/Files.jsx
context/app/static/js/components/Detail/GlobusLinkMessage/GlobusLinkMessage.jsx

Fix #916 .
Automatically opens the link in a new window/tab (controlled by browser) after the user agrees to the DUA. Could be blocked by pop-up blockers. I couldn't find a better alternative or new practice.

John conroy/auto open link after dua agree

---

CHANGELOG-auto-open-link-after-dua-agree.md
CHANGELOG-dua-typography.md
context/app/static/js/components/Detail/FileBrowserDUA/FileBrowserDUA.jsx
context/app/static/js/components/Detail/FileBrowserDUA/style.js
context/app/static/js/components/Detail/FileBrowserFile/FileBrowserFile.jsx
context/app/static/js/components/Detail/Files/Files.jsx
context/app/static/js/components/Detail/GlobusLinkMessage/GlobusLinkMessage.jsx

`DialogContentText` is just a paragraph element with some default styles so we were getting a number of DOM nesting errors because we were placing headers inside of a paragraph.  Switched to using typography components to get font styles from the theme. I also opted to use our main text color instead of the secondary gray from our palette because the new font weights heightened the contrast issues discussed in #914 .

John conroy/dua typography

---

CHANGELOG-auto-open-link-after-dua-agree.md
CHANGELOG-dua-before-globus.md
CHANGELOG-dua-typography.md
context/app/static/js/components/Detail/FileBrowser/FileBrowser.jsx
context/app/static/js/components/Detail/FileBrowserConditionalLink/FileBrowserConditionalLink.jsx
context/app/static/js/components/Detail/FileBrowserConditionalLink/index.js
context/app/static/js/components/Detail/FileBrowserConditionalLink/style.js
context/app/static/js/components/Detail/FileBrowserDUA/FileBrowserDUA.jsx
context/app/static/js/components/Detail/FileBrowserDUA/style.js
context/app/static/js/components/Detail/FileBrowserFile/FileBrowserFile.jsx
context/app/static/js/components/Detail/FileBrowserNode/FileBrowserNode.jsx
context/app/static/js/components/Detail/Files/Files.jsx
context/app/static/js/components/Detail/Files/context.js
context/app/static/js/components/Detail/FilesConditionalLink/FilesConditionalLink.jsx
context/app/static/js/components/Detail/FilesConditionalLink/index.js
context/app/static/js/components/Detail/FilesConditionalLink/style.js
context/app/static/js/components/Detail/GlobusLinkMessage/GlobusLinkMessage.jsx

Fixes #915.
I opted to pass DUA variables by context instead of props, context providers which aren't updated shouldn't negatively impact performance and are cleaner than passing props to far away children.
A link without an href isn't keyboard accessible. Reading around many believe using a void or similar href is bad practice. I opted to use a button although the component names are now a little confusing. Any thoughts on the subject?
Example with file browser and globus link: http://localhost:5001/browse/dataset/63a35af025a3662cb368eb3999fe2948

John conroy/dua before globus

---

CHANGELOG-results-table.md
context/app/static/js/components/Search/Search.scss
context/app/static/js/components/Search/SearchWrapper.jsx

Fix #701, and perhaps another one I can't find now: I have this memory that someone was really frustrated that the different "links" all went to the same place.  This is an ad-hoc solution, and may be replaced.

Tweak results table so more clear the whole thing is the result, not separate links

---

CHANGELOG-ccf-version.md
context/app/templates/pages/ccf-eui.html

We have changed our method of delivering CCF EUI releases to use a tagged versioning system. This PR just updates the base href it needs to point to.

Update ccf-eui base href

---

CHANGELOG-vitessce-warning-snackbar.md
context/app/static/js/components/Detail/Visualization/Visualization.jsx
context/app/static/js/components/Detail/Visualization/style.js
test.sh

This pull request adds a close-able `<Snackbar/>` component for displaying warning messages from Vitessce, such as `Error HTTP status fetching cells.` or `Error while validating cells.`  These messages are emitted from the `onWarn` callback on the `<Vitessce/>` component. Right now these warnings only appear in the console.
This PR can be tested by temporarily changing line 411 of vitessce.py https://github.com/hubmapconsortium/portal-ui/blob/971e0ee9e82d674fb9acc6a54d5dd6ed6f0fca9a/context/app/api/vitessce.py#L411
to `base_url = urllib.parse.urljoin(assets_endpoint, f"{self.uuid}/{rel_path}_BAD_URL")`
(I also saw that there is now an ErrorBoundary component. I tried throwing the warning as an error, but it did not seem to trigger that error handler, but maybe I was doing something wrong. …

Add snackbar to show warning messages emitted from Vitessce

---

CHANGELOG-update-footer.md
context/app/static/js/components/Collections/Collections/style.js
context/app/static/js/components/Detail/DetailLayout/style.js
context/app/static/js/components/Footer/Footer.jsx
context/app/static/js/components/Footer/style.js
context/app/static/js/index.css
context/app/static/js/shared-styles/Links/index.js
context/app/static/js/theme.jsx

Fix #936. Fix #919. 
- Footer is now below the fold for collections page.
- No link exists for 'Citing HuBMAP' in footer.

John conroy/update footer

---

CHANGELOG-no-selected-filters-at-top.md
context/app/static/js/components/Search/SearchWrapper.jsx

Fix #951 
@tsliaw : I won't block, but I am really uncomfortable with this. It's going to be so easy for the user to loose track of what filters are applied. If there is some replacement that you and Nils are envisaging, I would like to get that in now rather than leaving it in this state.

No more currently selected filters at top

---

CHANGELOG-access-group.md
context/app/static/js/components/Search/config.js

Fix #946
Would you like the facet values to be capitalized? That's what we do with the other facets. Would be done in `search-api`, not here, but it's easy.

Add access group facet

---

CHANGELOG-no-access-group-facet.md
context/app/static/js/components/Search/config.js

Fix #999. @ngehlenborg : Datasets (and datasets only) have the distinct `mapped_data_access_level` facet: This is correct?

Remove access group facet

---

context/CHANGELOG-sample-tissue-tests.md
context/app/static/js/components/Detail/SampleTissue/SampleTissue.spec.js

Add tests for sample tissue component.
- There's some refactoring that could be done between `SampleTissue` and `DonorMetadata`, but I don't think it's a pressing issue. 
- Do we want to continue to include `Tissue Location` even though it's still not present in the data?

John conroy/sample tissue tests

---

context/CHANGELOG-max-width.md
context/app/static/js/components/Preview/style.js

Fix preview for IU

---

CHANGELOG-token-cookie-session-cookie.md
context/app/routes_auth.py

Towards the problem that #927 was filed for. With a session cookie, we won't have the weird case where search acts like you're logged in, but you can't actually get the details.

session cookie

---

CHANGELOG-sex-instead-of-gender.md
context/app/static/js/components/Detail/DonorMetadata/DonorMetadata.jsx
context/app/static/js/components/Detail/DonorMetadata/DonorMetadata.spec.js
context/app/static/js/components/Search/config.js
context/app/static/js/components/entity-tile/EntityTileTopText/EntityTileTopText.jsx

This complements the indexing changes in search-api: https://github.com/hubmapconsortium/search-api/pull/144
- @john-conroy : Code review... just a search and replace, so hopefully I didn't find a way to mess this up.
- @ngehlenborg : When should this be merged? I think it's ok as long as the production environment has `sex`... but if the other environments have not caught up, the facet will not be available there. I think that's ok, but wanted to confirm.
(Separately from this, we want a tabular display of Donor metadata, but I don't think that more involved change should be crammed into this PR.)

Replace gender with sex

---

.vscode/portal-ui.code-snippets
context/app/static/js/components/App.jsx
context/app/static/js/components/Footer/Footer.jsx
context/app/static/js/components/Header/Header/Header.jsx
context/app/static/js/components/Header/HeaderAppBar/HeaderAppBar.jsx
context/app/static/js/components/Header/HeaderAppBar/index.js
context/app/static/js/components/Header/HeaderAppBar/style.js
context/app/static/js/components/Header/HeaderContent/HeaderContent.jsx
context/app/static/js/components/Header/HeaderContent/index.js
context/app/static/js/components/Header/HeaderContent/style.js
context/app/static/js/components/Header/index.js
context/app/static/js/index.css
context/app/static/js/maintenance/App.jsx
context/app/static/js/maintenance/MaintenanceError.jsx
context/app/static/js/maintenance/MaintenanceFooter.jsx
context/app/static/js/maintenance/MaintenanceHeader.jsx
context/app/static/js/maintenance/index.css
context/app/static/js/maintenance/index.html
context/app/static/js/maintenance/index.jsx
context/app/static/js/pages/Error/Error.jsx
context/app/static/js/pages/Error/style.js
context/build-utils/webpack.maintenance.js

Towards #1035. 
As mentioned in #1067, I'm going to handle the extra margin between the header and error page in the next PR before merging to master. Favicon won't work on maintenance dev-server, but should work in production maintenance mode.
Added another vscode snippet to import styled components.

John conroy/update maintenance page

---

CHANGELOG-readme.md
README.md

- Remove clearly outdated material (`prov-vis`).
- Move the docker demo and the webpack analyze to a "Understanding the build" section at the bottom.
- Link to redeploy standard operating procedure.
- Combine linting and pre-commit sections; put under testing.
@tsliaw : Since you're somewhat removed from day-to-day development, you'd probably have the clearest sense of whether this would be a clear introduction to a new developer.

Cleanup readme

---

CHANGELOG-fix-seq-vitessce-views.md
context/app/api/test_vitessce.py
context/app/api/vitessce.py

On PROD, http://localhost:5001/browse/dataset/eec6f3356dc3078c957baaa740849fcc is a new data type, "salmon_sn_rnaseq_10x" and Joel has informed me that the "sc_atac_seq_sn" should be "sn_atac_seq" to match https://github.com/hubmapconsortium/search-api/blob/master/src/search-schema/data/definitions/enums/assay_types.yaml

Fix Data Types For Vitesse Sequencing Viz

---

CHANGELOG-upgrade-vitessce-024.md
context/package-lock.json
context/package.json

There should be no changes except that when you open any `[Image Pyramid]` or `CODEX` datatype, the sliders should be set to make the image appear brighter than they were previously in the portal - this will be especially noticeable for CODEX and Autofluorescence datasets.

Upgrade Vitessce to 0.2.4

---

CHANGELOG-remove-collections-from-nav.md
context/app/static/js/components/Header/HeaderContent/HeaderContent.jsx
context/app/static/js/components/Header/Menu/Menu.jsx

Removes collections from navigation, but keeps it as an available route.

John conroy/remove collections from nav

---

CHANGELOG-disable-prov-table-for-snare.md
context/app/static/js/components/Detail/ProvTabs/ProvTabs.jsx
context/app/static/js/components/Detail/ProvTabs/utils.js
context/app/static/js/components/Detail/ProvTabs/utils.spec.js

Disables the provenance table for datasets which include `snare_lab` or `TMT-LC-MS` in its `data_types` array. It's working as expected for the `TMT-LC-MS` dataset in test, but there isn't a `snare_lab` example to check.

John conroy/disable prov table for snare

---

CHANGELOG-fix-sample-ccf-link.md
context/app/static/js/components/Detail/SampleTissue/SampleTissue.jsx
context/app/static/js/components/Detail/SampleTissue/SampleTissue.spec.js

Fix #1159. We can remove `target="_blank" rel="noopener noreferrer"`, right?

John conroy/fix sample ccf link

---

CHANGELOG-search-id-link.md
context/app/static/js/components/Search/ResultsTable.jsx
context/app/static/js/components/Search/styleForTable.js

Link to detail page in each row's HuBMAP ID cell not the entire row in search table. The row and highlight should look the same, but will no longer link to the detail page.

John conroy/search id link

---

CHANGELOG-fix-viz-tile-selector.md
context/app/static/js/components/Detail/visualization/Visualization/Visualization.jsx

Change placement of visualization tile selector and close upon selection per @tsliaw's suggestion.

John conroy/fix viz tile selector

---

CHANGELOG-fix-header-elevation.md
context/app/static/js/components/Header/Header/Header.jsx

Fix bug where header elevation was incorrect on entity detail pages when subheader was not displaying.
> Ah, I see what happens. John Conroy on pages that support the subheader the header no longer has a dropshadow after the subheader appears and then disappears.
Filed #1266 which I will look into tomorrow.

John conroy/fix header elevation

---

CHANGELOG-fix-header-dropdown-z-index.md
context/app/static/js/components/Header/Dropdown/style.js

Fix main header dropdown menus' z-index to be above the subheader.

John conroy/fix header dropdown z index

---

CHANGELOG-fix-preview-fullscreen.md
context/app/static/js/components/Detail/visualization/Visualization/style.js

Fix #1288. I could handle this with a prop instead of `window.location.pathname` if we think that is cleaner?

John conroy/fix preview fullscreen

---

CHANGELOG-standardize-icon-buttons.md
context/app/static/js/components/Detail/SummaryData/SummaryData.jsx
context/app/static/js/components/Detail/SummaryData/style.js
context/app/static/js/components/Detail/entityHeader/EntityHeader/EntityHeader.jsx
context/app/static/js/components/Detail/entityHeader/EntityHeader/style.js
context/app/static/js/components/Detail/entityHeader/EntityHeaderContent/EntityHeaderContent.jsx
context/app/static/js/components/Detail/visualization/Visualization/style.js
context/app/static/js/components/Detail/visualization/VisualizationCollapseButton/VisualizationCollapseButton.jsx
context/app/static/js/components/Detail/visualization/VisualizationCollapseButton/style.js
context/app/static/js/components/Detail/visualization/VisualizationThemeSwitch/VisualizationThemeSwitch.jsx
context/app/static/js/shared-styles/buttons/index.js

Fix bug regarding visualization collapse button placement in safari. All icon buttons now have a uniform height, width and svg icon size.

John conroy/standardize icon buttons

---

CHANGELOG-disable-prov-table-snare-rna.md
context/app/static/js/components/Detail/provenance/ProvTabs/ProvTabs.jsx

Fix #1294. This was the value in the `data_types` array for the example provided in the issue. Would we want to be more broad and disable the table for any data types which include the words `snare` and `rna` or similar?

John conroy/disable prov table snare rna

---

context/app/static/js/components/Search/Search.scss

Since search styles aren't in styled-components we don't get vendor prefixes for free. Fixes the sidebar height in Firefox.

John conroy/search sidebar vendor prefixes

---

CHANGELOG-dev-search-validation-errors.md
context/app/static/js/pages/search/DevSearch.jsx

Under /dev-search, we can now see where validation errors are coming from:
I recognize that we're not on the same page about some aspects of the architecture, but I think we do agree that there should be clean, usable, reliable APIs, and one part of that is documenting the API responses. One step on that path is moving the current entity-api responses closer to the schema... or the schema closer to the api. These facets show what part of the documents are in violation, and what part of the schema they are violating. I hope this will be useful.

Facet schema violation errors

---

CHANGELOG-redeploy.md
compose/hubmap.stage.yml
redeploy.sh

This is to replace PR #1344 (causes strange 502 error, probably due to orphan container) by handling the `portal-ui-prod` container in the same project.
- changes only apply to STAGE redeployment
- there are two docker compose yaml files now: `hubmap.yml` (only one `portal-ui` container for DEV/TEST/PROD) and `hubmap.stage.yml` (one `portal-ui` and one `portal-ui-prod` containers for STAGE only)
- the `portal-ui-prod` container will require `context/instance/app.prod.conf` to make calls against the PROD API services
@mccalluc you may need to tweak the `test.sh`. Feel free to tweak the `redeploy.sh` too.
I've tested the redeploy script with a modified script without the ssh section on STAGE and it works well. Please give it a try by running this script from your local.

Portal prod.stage zhou

---

CHANGELOG-search-pagination-position.md
context/app/static/js/components/Search/Search.scss

Fix #1350. Works on Chrome and FF.

Remove one CSS rule to fix pagination position

---

CHANGELOG-software-footer.md
context/app/static/js/components/Footer/Footer.jsx

New footer section. Fix  #1192

"software" in footer

---

CHANGELOG-table-height.md
context/app/static/js/components/Detail/CollectionCreatorsTable/CollectionCreatorsTable.jsx
context/app/static/js/components/Detail/CollectionDatasetsTable/CollectionDatasetsTable.jsx
context/app/static/js/components/Detail/MetadataTable/MetadataTable.jsx
context/app/static/js/shared-styles/Table/index.js

Fix #1263. @tsliaw - We had tabled this, but I still find myself wondering where the rest of the metadata is. I believe that a half-obscured row is a clear way to suggest that it can be scrolled. Need Nils' approval before merging, but what's your first impression?

Tweak table height

---

CHANGELOG-fix-css-injection-order.md
context/app/static/js/components/App.jsx
context/app/static/js/components/Search/SearchWrapper.jsx

Fix #1355. Since we code split the search page, the searchkit stylesheet and our modifications were being injected after and taking precedence over our styled components.
We chose this option out of the three solutions proposed below.
1. Increase styled components specificity globally.
2. Import the stylesheet in `App.js` so our styled components will be injected last. (This solution).
3. Specify style-loader to inject css/scss styles in a specific location.
Closing #1357 as we did not choose to increase specificity.

John conroy/fix css injection order

---

CHANGELOG-ccf-analytics.md
context/app/templates/pages/ccf-eui.html

The long term fix is to have CCF-EUI delivered as a webcomponent, or something like that, so I don't think it's worth investing time on machinery that would keep this in sync. It shouldn't be changing going forward, in any case.

Update CCF analytics key

---

CHANGELOG-change-expand-icon.md
context/app/static/js/components/Detail/visualization/Visualization/Visualization.jsx

We could possibly make the icon a little larger?

John conroy/change expand icon

---

context/app/static/js/components/files/FileBrowser/FileBrowser.jsx
context/app/static/js/components/files/FileBrowser/FileBrowser.spec.js
context/app/static/js/components/files/FileBrowser/style.js
context/app/static/js/components/files/FileBrowserDirectory/FileBrowserDirectory.jsx
context/app/static/js/components/files/FileBrowserDirectory/FileBrowserDirectory.spec.js
context/app/static/js/components/files/FileBrowserDirectory/style.js
context/app/static/js/components/files/FileBrowserFile/FileBrowserFile.jsx
context/app/static/js/components/files/FileBrowserFile/FileBrowserFile.spec.js
context/app/static/js/components/files/FileBrowserFile/style.js
context/app/static/js/components/files/FileBrowserNode/FileBrowserNode.jsx
context/app/static/js/components/files/FileBrowserNode/style.js
context/app/static/js/components/files/Files/Files.jsx
context/app/static/js/stores/useFilesStore.js

Fix #1009. Arrow icons to be added in #1375. Tests to be added in #1376. May be worthwhile to run this locally.
@tsliaw the 'QA' chip in each row is a little farther to the right than in your mockup, but this is how the table positions it by default and leaves a little more room for longer file/dir names.

John conroy/qa files

---

CHANGELOG-compression.md
context/build-utils/webpack.prod.js
context/package-lock.json
context/package.json
context/portal.nginx.conf

Fix #711. Compresses webpack assets with gzip and updates the nginx config to serve gzipped files. We should ultimately use both brotli and gzip with preference for brotli where browser compatible, but that requires installing a nginx module. 
I used [this article](https://itnext.io/nginx-create-react-app-gzip-tripple-your-lighthouse-performance-score-in-5-minutes-627465c3f445) as a resource. It explains some of the settings. We could possibly trim the types or add a `gzip_min_length` setting. We could also probably remove the ie6 setting since our application wouldn't work there anyways.
You can test this by running the docker container and looking for `content-encoding: gzip` in the response headers for our webpack assets.

John conroy/compression

---

CHANGELOG-lazy-load-vitessce-share-button.md
context/app/static/js/components/Detail/entityHeader/EntityHeaderContent/EntityHeaderContent.jsx
context/app/static/js/components/Detail/entityHeader/VisualizationShareButtonWrapper/VisualizationShareButtonWrapper.jsx
context/app/static/js/components/Detail/entityHeader/VisualizationShareButtonWrapper/index.js

Fixes #1394.
@ilan-gold I decided to go ahead and just lazy load the share button so I can evaluate the application's performance with gzip and the other changes we're making. This removes Vitessce from our bundle's entry points. Once Vitessce is tree-shakeable, we can remove the wrapper component. 
@tsliaw It should only show the disabled button while Vitessce is loading. Once Vitessce is loaded, it will display the regular share button.

John conroy/lazy load vitessce share button

---

CHANGELOG-proxy-http-version-for-gzip.md
compose/nginx.conf

Gzip should work once this change is made to the real nginx configuration for deployment. 
`gzip_http_version` sets the minimum HTTP version of a request required to compress a response to 1.1 by default. `proxy_http_version` defaults to 1.0 so by upgrading the version, the portal-ui will serve gzipped files when possible. Alternatively we could set `gzip_http_version` to 1.0.

John conroy/proxy http version for gzip

---

.github/workflows/portal-ci.yml
CHANGELOG-pin-ubuntu.md

Noticed a warning that the `latest` version is going to change. In general, a preference for pinning version numbers... but this might be an exception: One more thing to worry about, and if it ever did break, we could handle the problem then. I'm ambivalent. Thoughts?

pin ubuntu version

---

CHANGELOG-docker-config-logging.md
context/prestart.sh

Fix  #1430
Using docker.sh locally, and `docker logs`, confirmed that the config is in there.
- @john-conroy : code review
- @yuanzhou : Is this what you need? Is there anything else you'd like recorded?
I think the security on the logs is the same as the security on the config itself, but we could use `grep -v SECRET` instead of `cat`, if anyone would prefer?

Log config during docker startup

---

CHANGELOG-login-text.md
context/app/static/js/components/Header/LoginButton/LoginButton.jsx
context/app/static/js/components/Header/LoginButton/LoginButton.spec.js

"HuBMAP Member Login" would linewrap, and just look weird. Is this sufficient to fix #1393?

"login" -> "Member Login"

---

CHANGELOG-hierarchical-facets.md
context/app/static/js/components/Search/Search.scss
context/app/static/js/components/Search/__tests__/accordionFilters.spec.js
context/app/static/js/components/Search/accordionFilters.jsx
context/app/static/js/components/Search/config.js
context/app/static/js/components/Search/utils.js

Demo hierarchical facets by combining the existing status and access level facets. 
Note that this UI does not include checkboxes, and that unlike the other facets, only one option can be selected at a time. There is a separate [HierarchicalRefinementFilter](http://searchkit.github.io/searchkit/stable/components/navigation/hierarchical-refinement-filter.html) that can handle multiple values... but it also requires a significantly different index structure.
questions, mostly for Tiffany:
- Do you think this will be sufficient? or should we prioritize the indexing work for `HierarchicalRefinementFilter`? Or maybe we use this for now, while not excluding a change to the index in the future...
- For demo, does it make sense to treat the status as a hierarchy? Or maybe something in dev-search? …

hierarchical facets

---

CHANGELOG-dev-search-toggle.md
context/app/static/js/components/Search/DevResults/DevResults.jsx
context/app/static/js/components/Search/Results/Results.jsx
context/app/static/js/components/Search/ResultsCCF/ResultsCCF.jsx
context/app/static/js/components/Search/ResultsCCF/index.js
context/app/static/js/components/Search/SearchBarLayout/SearchBarLayout.jsx
context/app/static/js/components/Search/SearchBarLayout/SearchViewSwitch.jsx
context/app/static/js/components/Search/SearchViewSwitch/SearchViewSwitch.jsx
context/app/static/js/components/Search/SearchViewSwitch/index.js
context/app/static/js/components/Search/SearchWrapper.jsx
context/app/static/js/components/Search/config.js
context/app/static/js/pages/search/DevSearch.jsx
context/package-lock.json
context/package.json

- Provide two different view toggles, one for the main search, and one for dev.
- For the dev search, provide a stub where a CCF view could be filled in.
On dev-search, we now have this:
@tsliaw : Only question for you right now is whether that is a good button for CCF view?
@bherr2 : I'm thinking that you will be responsible for filling in the React in `ResultsCCF.jsx`... Does that sound ok to you, or do we need to provide some intermediate wrapper that will handle an interface that you'll specify?
@john-conroy : Code review; As usual, there may be some questionable decisions here. There are now two `SearchViewSwitch` exports:
```
export { SearchViewSwitch as default, DevSearchViewSwitch };
```
Both of these components are created with a factory function, and separating them into two …

dev search view toggle

---

context/app/static/js/components/Detail/SaveEditEntityButton/SaveEditEntityButton.jsx
context/app/static/js/components/savedLists/EditSavedStatusButton/EditSavedStatusButton.jsx
context/app/static/js/components/savedLists/EditSavedStatusDialog/EditSavedStatusDialog.jsx
context/app/static/js/stores/useSavedEntitiesStore.js

Checkboxes are now checked once you open the dialog based on whether the list already contains the entity. Clicking submit will add the entity to any checked lists and will remove the entity from unchecked lists. There is a lot of looping here, let me know if you can think of any alternatives to reduce it.

John conroy/remove from lists edit saved status

---

context/app/static/js/components/savedLists/CreateListDialog/CreateListDialog.jsx
context/app/static/js/components/savedLists/EditListDialog/EditListDialog.jsx
context/app/static/js/components/savedLists/SavedEntitiesTable/SavedEntitiesTable.jsx
context/app/static/js/components/savedLists/SavedEntitiesTableRow/SavedEntitiesTableRow.jsx
context/app/static/js/components/savedLists/SavedListScrollbox/SavedListScrollbox.jsx
context/app/static/js/components/savedLists/SavedListScrollbox/index.js
context/app/static/js/components/savedLists/SavedListScrollbox/style.js
context/app/static/js/pages/SavedLists/SavedLists.jsx
context/app/static/js/pages/SavedLists/style.js
context/app/static/js/shared-styles/DialogModal/DialogModal.jsx
context/app/static/js/shared-styles/panels/index.js

Adds links to table IDs and moves select row on click to the checkbox only. Moves link in saved list panels from entire panel to the title.
Do we want the panels used elsewhere (Collections page) to look and function the same way?

John conroy/fix saved list links

---

CHANGELOG-saved-list-route-tracking.md
context/app/static/js/components/Routes/Routes.jsx
context/app/static/js/components/Routes/useSendPageView.js

Fix page view tracking to track visits to a saved list page together instead of separating by uuid. Visits to any saved list page should show as `/my-lists/saved-list` instead of `/my-lists/{uuid}`.

John conroy/saved list route tracking

---

CHANGELOG-track-web-vitals.md
context/app/static/js/components/Routes/Route/Route.jsx
context/app/static/js/components/Routes/useSendWebVitals.js
context/package-lock.json
context/package.json

Fix #1511.
Adds tracking to each route for the four big web vitals metrics. The event will be linked to a page view but it will be the full path not the simplified path we use (so uuids will be included), if you think it makes sense I could add the simplified page view to one of the fields we send over.
@tsliaw you may want to look at the information you get for the events eventually and see if there's anything else you'd like me to add.

John conroy/track web vitals

---

CHANGELOG-fix-description.md
context/app/static/js/components/Detail/SampleTissue/SampleTissue.jsx
context/app/static/js/components/savedLists/LocalStorageDescription/LocalStorageDescription.jsx
context/app/static/js/pages/Collections/Collections.jsx
context/app/static/js/pages/Collections/style.js
context/app/static/js/pages/Preview/Preview.jsx
context/app/static/js/pages/Preview/style.js
context/app/static/js/pages/SavedList/SavedList.jsx
context/app/static/js/pages/SavedLists/SavedLists.jsx
context/app/static/js/shared-styles/sections/Description/Description.jsx
context/app/static/js/shared-styles/sections/Description/index.js
context/app/static/js/shared-styles/sections/SectionContainer.jsx

Fix #1555. Revises description into a single component. The component with `SectionContainer` was only needed on detail pages with the table of contents sidebar to fix anchor tag positioning. That's no longer needed for these description components. The new margin styles are only used to keep a similar appearance to what already existed.
Also fixes a prettier error from a code review suggestion from an earlier PR. These keep popping up, should we make prettier fail our ci to catch these earlier?

John conroy/fix description

---

CHANGELOG-fix-detail-anchor-link-locations.md
context/app/static/js/shared-styles/sections/SectionContainer.jsx

Just noticed this now. The offset wasn't updated to handle the entity header.

John conroy/fix detail anchor link locations

---

context/app/static/js/components/Detail/provenance/ProvGraph/ProvGraph.jsx
context/app/static/js/stores/useProvenanceStore.js

Disables the 'Show Derived Entities' button if new steps don't exist. Since `steps` is in the dependency array for the `useEffect` which creates the steps from provenance data and determines if the steps don't exist in the current graph, the `useEffect` would be run an additional time after the steps have first been updated. Probably not a big deal, but I could rework things to avoid it if needed.

John conroy/disable descendant prov button

---

context/app/static/js/components/Detail/provenance/ProvGraph/ProvGraph.jsx
context/app/static/js/components/Detail/provenance/ProvGraph/style.js
context/app/static/js/components/Detail/provenance/ProvVis/ProvData.js
context/app/static/js/components/Detail/provenance/ProvVis/ProvVis.jsx
context/app/static/js/components/Detail/provenance/ProvVis/__tests__/ProvData.spec.js
context/app/static/js/components/Detail/provenance/ShowDerivedEntitiesButton/ShowDerivedEntitiesButton.jsx
context/app/static/js/components/Detail/provenance/ShowDerivedEntitiesButton/index.js

Still getting the below prop-types warnings when opening the provenance graph, but the other warnings and code style issues identified in #1593 have been addressed. The code in `ShowDerivedEntitiesButton` isn't new and was taken from `renderDetailPane` in `ProvGraph`. Filed #1602.
> Warning: Failed prop type: The prop `nodes` is marked as required in `Graph`, but its value is `undefined`.
> Warning: Failed prop type: The prop `edges` is marked as required in `Graph`, but its value is `undefined`.

John conroy/refactor provenance

---

CHANGELOG-descendant-prov.md
context/app/static/js/components/Detail/provenance/ProvGraph/ProvGraph.jsx
context/app/static/js/components/Detail/provenance/ProvGraph/style.js
context/app/static/js/components/Detail/provenance/ProvTabs/ProvTabs.jsx
context/app/static/js/components/Detail/provenance/ProvVis/ProvData.js
context/app/static/js/components/Detail/provenance/ProvVis/ProvVis.jsx
context/app/static/js/components/Detail/provenance/ProvVis/__tests__/ProvData.spec.js
context/app/static/js/components/Detail/provenance/ShowDerivedEntitiesButton/ShowDerivedEntitiesButton.jsx
context/app/static/js/components/Detail/provenance/ShowDerivedEntitiesButton/index.js
context/app/static/js/hooks/useImmediateDescendantProv.js
context/app/static/js/stores/useProvenanceStore.js

Fix #1595.
Adds a 'Show Descendants' button to show descendants of entity in provenance graph detail pane. This has worked for both simple cases such as this donor `190aec1937701a97952b34cfac5529a3` where the resulting provenance matches its only descendant sample `14e44841842d639b28bfdf9188a95a86` and sample `d1fe368864b494e4cace64d68c7c60ed` where multiple descendants exist. Incrementally revealing descendants seems to work, but it is hard to verify (such as instances where paths diverge only to converge later, but I haven't been able to find an example of this if it could exist).
We probably won't want to merge this to master until I add some tests and we do some manual testing.
Likely follow-ups:
- Fetch immediate descendants when detail pane is opened and disable the button if no …

John conroy/descendant prov

---

CHANGELOG-vitessce-backend-bug.md
context/app/api/client.py
context/app/api/vitessce_confs/assay_confs.py
context/app/api/vitessce_confs/base_confs.py

Replace #1615. Fixes #1614.
- Consistent return types are good: whatever is returned, you can call the method.
- Give a default value for is_mock.
Are there public datasets that would have triggered this, or is there something special about the private datasets that the bug was reported for? Is the plan to keep in communication with IEC so as new types come along, we'll get new visualizations up?

Mccalluc/ilan gold/nonetype assays

---

CHANGELOG-prettier-should-fail-ci.md
test.sh

Fix #1565. Add linting, which includes prettier, to test script. I think we previously got this from dev-start when it was in the test script, but lost it when it was removed.

John conroy/prettier should fail ci

---

CHANGELOG-fix-rna-seq-issue.md
context/app/api/vitessce_confs/base_confs.py

Fixes #1638 separate from #1637.  `self.conf` does not exist on the class.
For example: https://portal.test.hubmapconsortium.org/browse/dataset/a598609e8a6c8ba6d0ca52b3e567040d on TEST should work now with this PR

Fix RNA-Seq Nonetype Issue

---

CHANGELOG-no-asct-preview.md
context/app/static/js/components/Header/PreviewLinks/PreviewLinks.jsx

Is this still needed if you have it in the other menu? The underlying document is still there, so links won't break.

Remove from ASCT+B from menu

---

CHANGELOG-container-names.md
compose/hubmap.stage.yml

Issue: https://portal-prod.stage.hubmapconsortium.org/ uses the PROD search-api configuration, but sometimes this domain returns results from the actual STAGE search-api. 
Fix: in case the gateway nginx confuses `portal-ui` with `portal-ui-prod` hostnames due to name-based matching rule when forwarding the domain to the container, I'm changing the hostname to be totally unique to nginx.
Will make the corresponding changes in gateway nginx configuration.

Change container name to prod-portal-ui

---

CHANGELOG-prev.md
context/app/static/js/pages/search/DevSearch.jsx

I don't know how long this example on dev will stay around, but: https://portal.dev.hubmapconsortium.org/browse/dataset/8f528475e216c283851e6941841d7173.json
```
"previous_revision_uuid": "8f528475e216c283851e6941841d7173"
```
Can you confirm that this doubly-linked list structure works with your designs, and then put the implementation issues in the v0.15 milestone? Thanks!
(Related back-end issue: https://github.com/hubmapconsortium/search-api/issues/233)

"previous" should be spelled out

---

CHANGELOG-prevent-cors-preflight.md
context/app/api/vitessce_confs/assay_confs.py
context/app/api/vitessce_confs/base_confs.py
context/app/api/vitessce_confs/fixtures/input_entity/atac_entity.json
context/app/api/vitessce_confs/fixtures/input_entity/codex_entity.json
context/app/api/vitessce_confs/fixtures/input_entity/image_pyramid_entity.json
context/app/api/vitessce_confs/fixtures/input_entity/ims_entity.json
context/app/api/vitessce_confs/fixtures/input_entity/malformed_atac_entity.json
context/app/api/vitessce_confs/fixtures/input_entity/malformed_codex_entity.json
context/app/api/vitessce_confs/fixtures/input_entity/malformed_image_pyramid_entity.json
context/app/api/vitessce_confs/fixtures/input_entity/malformed_ims_entity.json
context/app/api/vitessce_confs/fixtures/input_entity/malformed_rna_entity.json
context/app/api/vitessce_confs/fixtures/input_entity/malformed_rna_zarr_entity.json
context/app/api/vitessce_confs/fixtures/input_entity/malformed_seqfish_entity.json
context/app/api/vitessce_confs/fixtures/input_entity/malformed_sprm_entity.json
context/app/api/vitessce_confs/fixtures/input_entity/rna_entity.json
context/app/api/vitessce_confs/fixtures/input_entity/rna_zarr_entity.json
context/app/api/vitessce_confs/fixtures/input_entity/seqfish_entity.json
context/app/api/vitessce_confs/fixtures/input_entity/sprm_entity.json

For published datasets, the `assets` API should not need to authenticate requests (and in fact when people are not signed in, cannot).  Authenticating requests via a header (needed for zarr stores) causes pre-flight `OPTIONS` requests to be sent out: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests (You can see this by opening the network tab on a zarr-backed AnnData RNA-seq dataset).
This PR takes away the header for published datasets as it is unnecessary, which should give us a nice performance bump.
This also fixes an issue where an empty auth header returns a 401 regardless of whether or not the dataset is published (which can happen for people who are not signed in but datasets which are "Published").  I don' t think it's a bug with `assets`, but it does cause …

Prevent Unnecessary Auth for Published Zarr Stores

---

CHANGELOG-donor-metadata.md
context/app/static/js/components/Detail/MetadataTable/MetadataTable.jsx
context/app/static/js/pages/Donor/Donor.jsx

Fix #1713.
Note: for purposes of indexing and search, if you only have a single value for a field, Elasticsearch doesn't care whether you represent it as `"key": "value"` or `"key": ["value"]`. In fact, I don't think you could distinguish between these two at search time even if you wanted to. However, when it returns the source document, the original structure is preserved. For whatever reason, the donor metadata values are all single element lists.
(I introduced this bug when I added the filter to hide objects... and that itself was kludge, to give us something at `metadata.metadata` for all entity types, so that "Has metadata?" would work in dev-search.)

Fix empty donor metadata

---

CHANGELOG-donor-missing.md
context/app/static/js/schema.org.js
context/app/static/js/schema.org.spec.js

Fix #1675. Don't worry over the details too much: For #1723 , the IEC is committed to providing good descriptions on datasets, so this will all be moot.

Supply metadata for spiders, even when donor is missing

---

CHANGELOG-friendlier-401.md
context/app/static/js/components/error/ErrorBody/ErrorBody.jsx
context/app/static/js/components/error/ErrorBody/ErrorBody.spec.js
context/app/templates/errors/401-no-hubmap-group.html

Fix #1607
I don't think the client-side error message is being shown right now... but understanding why not is a separate, low priority issue, and I think it makes sense to just keep the messages in sync for now.

Update client-side and server-side 401 messages

---

CHANGELOG-remove-unused-enums.md
context/app/api/vitessce_confs/constants.py

Prompted by the thread on slack. assay_confs.py now has:
```
from .assays import (
SEQFISH,
MALDI_IMS_NEG,
MALDI_IMS_POS,
)
from .paths import (
SCRNA_SEQ_DIR,
SCATAC_SEQ_DIR,
IMAGE_PYRAMID_DIR,
TILE_REGEX,
SEQFISH_HYB_CYCLE_REGEX,
SEQFISH_FILE_REGEX,
CODEX_TILE_DIR
)
```
so the enums aren't needed, I think?

Remove unused enums

---

CHANGELOG-eui-styles.md
context/app/templates/pages/ccf-eui.html

The EUI now uses Inter and includes outlined material icons. This commit aligns it with CCF-EUI v1.6.0.

Update the styles used in the EUI

---

CHANGELOG-derived-from-type.md
context/app/static/js/components/Search/AncestorNote.jsx

Fix #1802. If it's a Donor or Sample, there won't be anything in the slot, but extra spaces are collapsed when the browser renders it.
One small point: The assay types are capitalized, so maybe we don't need to lowercase the entity type? I don't care strongly.

Show type derived from

---

CHANGELOG-fix-submodule-pulls.md
push.sh

`portal-images` uses `main` not `master`.  We'll be migrating all of our repos now but for now this provides a hot-fix.

Fix Submodule Pulls for Deployment

---

CHANGELOG-make-vitessce-louder.md
context/app/api/client.py
context/app/api/vitessce_confs/assay_confs.py
context/app/api/vitessce_confs/base_confs.py
context/app/api/vitessce_confs/test_confs.py
context/app/static/js/pages/Dataset/Dataset.jsx

Fix #1645
- No longer return `{}` as a placeholder -- Semantics were ambiguous.
- If there is no visualization, return `None`
- If there is an error, raise it, and at `client.py:129` return a valid vitessce conf with a user-facing message.
- Remove `@return_empty_json_if_error`: Just let the error go up to `client.py:129`: This avoids needing to copy-and-paste boilerplate with new subclasses.
- In `Dataset.jsx` throw an error if we get and invalid vitessce conf. We do not expect to see `{}` any longer.
If this still doesn't seem right, please push back!

If there is a problem generating vitessce conf, show an error in the UI

---

CHANGELOG-fix-master-changelog-test.md
test.sh

Fixing `test.sh` issue introduced by a dependabot change causing master builds to fail without a changelog (should pass).

John conroy/fix master changelog test

---

CHANGELOG-always-show-search-term.md
context/app/static/js/components/Search/Search.scss

Fix #1476.
Also now uses our primary text color for the search input. There might be a better way to use theme vars with `Search.scss`.

John conroy/always show search term

---

CHANGELOG-fix-summary-date-alignment.md
context/app/static/js/components/Detail/DetailDescription/DetailDescription.jsx
context/app/static/js/components/Detail/DetailDescription/style.js
context/app/static/js/components/Detail/SectionItem.jsx

Fix #1869. Is this what you both were thinking it should look like? I opted to just pass props to the div to allow us to use `styled`, but I could expand using margin specific props.

John conroy/fix summary date alignment

---

CHANGELOG-fix-collection-title-text-overflow.md
context/app/static/js/shared-styles/panels/index.js

Fix #1862. Also applies to similar saved list panels.

John conroy/fix collection title text overflow

---

CHANGELOG-fix-bar-chart-responsiveness.md
context/app/static/js/components/home/AssayTypeBarChartContainer/style.js

Fix #1883. Adding `width: 0px` seems to be the fix and forces another dimensions recalc. Please take a look locally and let me know what you think.

John conroy/fix bar chart responsiveness

---

CHANGELOG-props.md
context/app/static/js/components/Routes/Routes.jsx

Sorry to let this get through. When we're doing QA, I'd like to try to keep an eye on console warnings -- Often, they are harmless, but if we can get rid of the false alarms, the console can help us identify real problems.

Fix proptypes warning

---

CHANGELOG-vitessce-1-1-11.md
context/app/api/vitessce_confs/assay_confs.py
context/app/api/vitessce_confs/base_confs.py
context/app/api/vitessce_confs/fixtures/output_expected/cytokit_json_conf.json
context/app/api/vitessce_confs/fixtures/output_expected/image_pyramid_conf.json
context/app/api/vitessce_confs/fixtures/output_expected/ims_conf.json
context/app/api/vitessce_confs/fixtures/output_expected/seqfish_conf.json
context/app/api/vitessce_confs/fixtures/output_expected/sprm_conf.json
context/package-lock.json
context/package.json

Closes 1673
To test:
- [Lightsheet](http://localhost:5001/search?mapped_data_types[0]=Lightsheet%20Microscopy&entity_type[0]=Dataset) should allow 3D and be functional
- [IMC](http://localhost:5001/search?mapped_data_types[0]=Imaging%20Mass%20Cytometry&entity_type[0]=Dataset) should be the same (both of the above, only the datasets in QA)
Other than that everything should look/work identical to what is on PROD right now with the exception of the small UI change of the z-slider placement (for example, for [seqFish](http://localhost:5001/browse/dataset/eaad5ed4b3aa2186bd87e05ff28b593e)) - importantly, there should be no visual cues for 3D outside of the above two data types even though the unstitched CODEX and seqFISH both do have z-stacks.

Vitessce 1.1.11

---

CHANGELOG-fix-offsets-file.md
context/app/api/vitessce_confs/base_confs.py
context/app/api/vitessce_confs/fixtures/output_expected/cytokit_anndata_conf.json
context/app/api/vitessce_confs/fixtures/output_expected/sprm_anndata_conf.json

I think my assumption that the `offsets.json` file is in the wrong place from #1904 was wrong, and based on the fact that the offsets file is in that place from the old SPRM which led me to believe it was run on the non-image pyramid, which was to be somewhat expected given that we hadn't seen a completely clean run yet.  To recap, the only runs we had seen included the incorrect offsets file, but in the right place, which led me to believe it was in the wrong place given past behavior.  Hopefully the change in test case behavior and the two different new `_get_ometiff_image_wrapper` (one for the old way, one for the new) functions highlight how this current change makes (more) sense.

Fix Offsets Location for Cytokit AnnData

---

CHANGELOG-docs.md

We haven't been updating docs. :(
```
git submodule foreach '
echo "was:" `git rev-parse HEAD`
git checkout master || git checkout main
git pull
echo "now:" `git rev-parse HEAD`
'
```
I think the problem is that even if github now is on `main`, developers may still have the `master` branch around... it just isn't getting any updates.
I think just getting rid of the `master` branch in your local checkout will fix this, but I'd like a more robust script, too.
(Docs people would like to see this new page out.)

docs update

---

CHANGELOG-marked.md
context/package-lock.json
context/package.json

In the 2.0.0 version, lines that only contain whitespace caused the adjoining markdown to be rendered verbatim. Fixed in this version, and /docs/technical looks good, without any changes in the submodule.

Upgrade marked

---

CHANGELOG-upgrade-flask.md
context/requirements.txt

Fix #1986. Python tests run without warnings. I've looked at their [release notes](https://flask.palletsprojects.com/en/2.0.x/changes/), and don't see anything that concerns me.

Upgrade flask

---

CHANGELOG-diversity-description-starter.md
context/app/routes_main.py
context/app/static/js/pages/Diversity/Diversity.jsx
context/app/static/js/pages/Diversity/DonorChart.jsx

- Descriptions should only display for charts if you pass in a description prop. 
- Removed the `Methodology` section and only retained descriptions for the two blood type charts and the page (which need to be replaced). 
- Renamed page to 'HuBMAP Donor Diversity'.

John conroy/diversity description starter

---

CHANGELOG-descendant_counts-fallback.md
context/app/static/js/components/Detail/provenance/ProvTable/ProvTable.jsx

@yuanzhou, if you log in, you can see that https://portal.hubmapconsortium.org/browse/sample/6de04b223f7a976ef1129f10816cd5cb.json just has 
```
"descendant_counts": {}
```
This change gets the portal working again...
We don't have a definitive schema, so I can't say this JSON is "wrong", but it does seem like something has changed. If you think the upstream code is doing what you want, we can accommodate it... but if you're not sure why this changed, I would prefer not to sweep it under the rug.
Involve Bill if needed?

`descendant_counts` fallback

---

CHANGELOG-reorg-routes.md
context/app/main.py
context/app/routes_auth.py
context/app/routes_browse.py
context/app/routes_cells.py
context/app/routes_main.py
context/app/routes_markdown.py
context/app/test_routes_errors.py
context/app/test_routes_main.py
context/app/utils.py

Moving out the `browse` routes cuts `routes_main` in half. Also delete some vestigial code, and cleanup.

Split browse routes to own file

---

CHANGELOG-flaskdata.md
context/app/static/js/components/App.jsx

Tripped over this working on publications: I jumped from `routes_main.py` to `Routes.jsx` and forget this was in the middle. Does it seem ok to strip out the destructuring/restructuring?

Simplify App.jsx

---

CHANGELOG-cells-dataset-rows.md
context/app/static/js/components/home/AssayTypeBarChartContainer/AssayTypeBarChartContainer.jsx
context/app/static/js/components/home/EntityCounts/EntityCounts.jsx
context/app/static/js/components/home/FacetSearch/FacetSearch.jsx
context/app/static/js/hooks/useDerivedEntitySearchHits.js
context/app/static/js/hooks/useSearchData.js
context/app/static/js/pages/CellsAPIDemo/DatasetsSelectedByExpression.jsx
context/app/static/js/pages/CellsAPIDemo/DatasetsTable.jsx
context/app/static/js/pages/Diversity/Diversity.jsx
context/app/static/js/pages/Diversity/DonorChart.jsx

Adds a follow up request to the search api to display datasets returned by cells gene expression query in rows with metadata. Also adds the app context providers directly in `useSearchData` and `useSearchHits`.

John conroy/cells dataset rows

---

CHANGELOG-donor-metadata.md
CHANGELOG-mock-client.md
context/app/api/client.py
context/app/api/mock_client.py
context/app/api/vitessce_confs/assay_confs.py
context/app/api/vitessce_confs/base_confs.py
context/app/main.py
context/app/markdown/README.markdown
context/app/markdown/apis.md
context/app/routes_api.py
context/app/routes_browse.py
context/app/routes_main.py
context/app/static/js/components/Footer/Footer.jsx
context/app/utils.py

Fix #2039: Metadata TSVs. Add an `/apis` link in the footer to a new page that describes the different APIs and data download options we have. (The url is not `/docs/apis` because we've entirely handed that directory off to PK, but I'd like to just get this described here.)
- @shirey : I would like your buy-in on this description of the existing APIs.
- @ngehlenborg : Confirmation that this is what you want.
- @john-conroy : Code review.
Current headers of `donors.tsv`:
```
uuid
hubmap_id
age_unit
age_value
blood_type
body_mass_index_unit
body_mass_index_value
cause_of_death
death_event
height_unit
height_value
kidney_donor_profile_index_unit
kidney_donor_profile_index_value
mechanism_of_injury
medical_history
race
rh_factor
sex
social_history
weight_unit
weight_value
```
Current headers …

Donors/Samples/Datasets TSVs

---

CHANGELOG-exclude-lineup-source-maps.md
context/build-utils/webpack.common.js

Fix #2145. This should handle `linupjs` and `lineupjsx`.

John conroy/exclude lineup source maps

---

CHANGELOG-svg-link-target.md
context/app/static/js/components/home/AssayTypeBarChart/AssayTypeBarChart.jsx

- Fix #2152 
@shirey -- Can you confirm that this is actually only a problem with the barchart iframe? Using `iframe-demo.html` I can confirm that on Chrome the links there open up inside the iframe, instead of on the top level... but the links in the entity-counts iframe seem to be working fine.
@john-conroy -- Code review. There definitely seems to be a difference between FF and Chrome here, but I haven't found anything which describes exactly this issue, so I think we should just try to accommodate both.

Add explicit target in SVG

---

CHANGELOG-cells-accordion.md
context/app/static/js/components/cells/DatasetsSelectedByExpression/DatasetsSelectedByExpression.jsx
context/app/static/js/components/cells/DatasetsSelectedByExpression/style.js
context/app/static/js/components/cells/DatasetsTable/DatasetsTable.jsx
context/app/static/js/pages/Cells/Cells.jsx
context/app/static/js/shared-styles/accordions/StepAccordion/StepAccordion.jsx
context/app/static/js/shared-styles/accordions/StepAccordion/StepAccordion.spec.js
context/app/static/js/shared-styles/accordions/StepAccordion/StepAccordion.stories.js
context/app/static/js/shared-styles/accordions/StepAccordion/index.js
context/app/static/js/shared-styles/accordions/StepAccordion/style.js

Towards #2142. Adds a reusable 'step' accordion component and separates the gene expression query and results each into an accordion. It still only handles single gene names, but should be expanded to multiple gene names and protein queries soon. Not worried about spacing here, it'll get fixed later down the road.
I don't think I need to worry about string overflow in the accordion summary, but if you feel like it's a risk, I could add styles to truncate the text with an ellipsis if needed.
I'd recommend checking this out locally and in the storybook.

John conroy/cells accordion

---

CHANGELOG-organ-pages.md
context/app/routes_file_based.py
context/app/static/js/components/Header/AtlasToolsLinks/AtlasToolsLinks.jsx
context/app/static/js/components/cells/DatasetsSelectedByExpression/DatasetsSelectedByExpression.jsx
context/app/static/js/components/organ/Assays/Assays.jsx
context/app/static/js/components/organ/Azimuth/Azimuth.jsx
context/app/static/js/components/organ/Description/Description.jsx
context/app/static/js/components/organ/OrganInfo/OrganInfo.jsx
context/app/static/js/components/organ/Samples/Samples.jsx
context/app/static/js/helpers/functions.js
context/app/static/js/hooks/useSearchData.js
context/app/static/js/pages/Organ/Organ.jsx
context/app/static/js/pages/search/CellsSearch.jsx
context/app/static/js/pages/search/Search.jsx

cc @ngehlenborg / @tsliaw 
For the work I know still needs to be done, I've filed 
- #2182
Suggest that that be reviewed in conjunction with this, and if anything is absolutely essential, bring it forward.
Note that this also adds a util function that excludes entities that are not the latest version. We'll be adding a clause to this soon to also excludes retracted entities. 
Note that this adds "Organs" to the "Atlas & Tools" Menu. If we want to have this up on Friday, it needs to be in this release.
- Fix #2177 
- Fix #2126
- Fix #2092
- Fix #2090
- Fix #1824

Organ pages good-enough and linked from Atlas menu

---

context/app/static/js/components/cells/CellExpressionHistogram/CellExpressionHistogram.jsx
context/app/static/js/components/cells/CellsCharts/CellsCharts.jsx
context/app/static/js/components/cells/DatasetClusterChart/DatasetClusterChart.jsx
context/app/static/js/components/cells/DatasetsTable/DatasetsTable.jsx
context/app/static/js/hooks/useExpand.js
context/app/static/js/hooks/useExpandTransition.js
context/app/static/js/shared-styles/Table/ExpandableRow/ExpandableRow.jsx
context/app/static/js/shared-styles/Table/ExpandableRow/ExpandableRow.spec.js
context/app/static/js/shared-styles/Table/ExpandableRow/ExpandableRow.stories.js
context/app/static/js/shared-styles/Table/ExpandableRow/style.js

- Hides/reveals not conditionally renders `ExpandableRow` content.
- Adds spring to `ExpandableRow` expand.
- Pulls expand transition/spring into reusable hooks.
Nils wanted the charts in the table to be preserved when closed/re-opened. To do that I decided to hide the expanded content instead of not rendering it similar to what MUI does with its accordions. I also added some logic to the chart fetch hooks to make sure the hook is only run on the initial expand. Using a ref instead of state ensures the component is not updated when the value is changed. I attempted to move that logic into a reusable hook, but couldn't manage it quickly and cleanly.

John conroy/fix loaders

---

CHANGELOG-track-search-bar.md
context/app/static/js/components/Search/SearchWrapper.jsx
context/app/static/js/components/Search/filters/AccordionFilter/AccordionFilter.jsx
context/app/static/js/components/Search/filters/Filters/Filters.jsx
context/app/static/js/pages/search/DevSearch.jsx
context/app/static/js/pages/search/Search.jsx

Towards #2217. Tracks free text searches. Only tracks new terms so searching the same terms n times in a row would only generate one event. Does not track undefined or empty searches. 
Here's the event there should be some example events on GA now.
```
ReactGA.event({
category: analyticsCategory,
action: 'Free Text Search',
label: newQueryString,
});
```
Where `analyticsCategory` is `${pageTitle}: Search Interactions` e.g. 'Datasets Search Interactions'.

John conroy/track search bar

---

CHANGELOG-fix-facet-alignment.md
context/app/static/js/components/Search/filters/CheckboxFilterItem/style.js

Fix checkbox facet alignment on search pages to match what it was before recent changes.

John conroy/fix facet alignment

---

CHANGELOG-publication-warnings.md
context/app/static/js/components/Routes/Routes.jsx
context/app/static/js/pages/Publication/Publication.jsx

Fix a couple warnings on the publication page... If we actually had multiple corresponding authors the UI would need work, but not inclined to worry about that since the data seems to be very slow in coming.

publication warnings

---

CHANGELOG-markdown-warning.md
context/app/static/js/components/Markdown/Markdown.jsx

Fix #1146. (Previously closed as won't fix.)

Fix element nesting error on markdown pages

---

CHANGELOG-pretty-500.md
context/app/main.py

Presently, if an error that we don't otherwise handle falls through, we'll get this:
(Screen shot from an error on the TEST the other day: When I pointed my local instance at TEST with the same path, I was dropped into the debug view.)
- This change makes no difference when `FLASK_ENV=development`: I've confirmed that we still get the flask debugger.
- In production, instead of the white error screen above, you'll get the pretty react error page: I've confirmed by removing `FLASK_ENV=development` from `dev-start.sh`; you still get a stack trace in the log.
- Going forward, if someone does get an unstyled error page we can say with high confidence that the error happened outside of our flask: either the NGINX in our container, or at the gateway.
- ... if we do get a 500, the root cause may …

Render react error page for all errors

---

CHANGELOG-nginx-timeout.md
context/portal.nginx.conf

Running the docker container locally, this prevented timeout errors. [Notes.](https://github.com/hubmapconsortium/portal-ui/blob/mccalluc/debug-cells/cells-lab-notebook.md)
John will do some work in the UI to prevent a single user from expanding multiple cells rows at the same time. 
- Issue: #2320
This is not a zero-risk change, but Nils is on board. Keeping as draft until Bill or Zhao can comment on whether we may also hit timeout errors from the gateway.

increase timeout

---

CHANGELOG-consortium-facet.md
context/app/static/js/components/searchPage/config.js

- Finally fix #1406
- Draft until https://github.com/hubmapconsortium/search-api/pull/427 is merged and reindex on production completes.

consortium facet

---

CHANGELOG-fix-fullscreen-vitessce.md
context/app/static/js/components/Header/Header/Header.jsx
context/app/static/js/components/detailPage/entityHeader/EntityHeaderContent/EntityHeaderContent.jsx
context/app/static/js/components/detailPage/visualization/Visualization/Visualization.jsx
context/app/static/js/components/detailPage/visualization/Visualization/style.js
context/app/static/js/theme.jsx

Fix #2400. Fix #2387.
#2400 was introduced by #2376. I've added back the necessary styles and made it more explicit that the `z-index` and `position:relative` is needed for fullscreen Vitessce only.
Since the header is no longer constrained to entity detail pages I believe a follow-up PR to rename the component to `Subheader` or similar and move it out of the `detail` directory. @mccalluc let me know if that makes sense to you.

John conroy/fix fullscreen vitessce

---

CHANGELOG-copy-viz-submodule-docker.md
context/Dockerfile

`docker.sh` is working locally, but our deployed container is not. We need to copy the new submodule as a part of the dockerfile.

John conroy/copy viz submodule docker

---

CHANGELOG-no-more-auto-increment-submodules.md
push.sh

I have archived https://github.com/hubmapconsortium/portal-docs, and when https://github.com/hubmapconsortium/software-docs/pull/25 is merged, portal-docs can be moved to the graveyard.
I don't believe the wait to merge the PR (now a month) should block other changes that follow from the decision in December to move documentation to that repo.

Stop auto-incrementing submodules

---

CHANGELOG-maintenance.md
context/build-utils/webpack.dev.maintenance.js
context/build-utils/webpack.maintenance.js
end-to-end/cypress/integration/maintenance.spec.js
test.sh

I think the maintenance build has been broken since 50b147ea4ac263f4d0ea9cac43ee7b93bb0c28f0.
Towards #2397

fix maintenance / add cypress test

---

CHANGELOG-diagram.md
README.md

Thought you both might be interested in an example. It's pretty opinionated, and is really designed to just support a few key types of diagrams. There are other tools in this space that try to translate arbitrary ascii-art-diagrams, and that's not what this does.
I worked on it in the [live editor](https://mermaid-js.github.io/mermaid-live-editor/edit/#pako:eNpdkU2OwyAMha8SsS4XyGJWnRPM7JouXOImlvgTmFZR1bsPlGRQ4pXf5wc25iWUG1H0Ygrg5-73PNguxwSMT1gGWyU7f_EuMGiZ6NpJ-dUpZ4yz8b9eobpnw549iDFGhat4HKqgabyQnTCy_Ahgclayczpe99453Qx4CZ6kX6TShJZrW9Q6Fr735zLxUvhHevK4dSq5JouHDhAjctyd2BsiQlDzwVAtJW9POrB1ecpZhtw2xO1UTLe6-XzluswSbfTG2nCNtXkaO2wD7ShOwmAwQGP-6FfBg-AZDQ6iz-mId0iaBzHYd7Ymn_8Av0diF0TPIeFJQGL3s1i16eo5E-ThTYXvP1rXvF4) and then pasted it here.

Use mermaid for the readme diagram

---

CHANGELOG-missing-contributors.md
context/app/static/js/pages/Dataset/Dataset.jsx

https://portal.test.hubmapconsortium.org/browse/dataset/550c5a19866fb79faf17ecb75ea6987f  is missing contributors. With this tweak, the page renders, but Vitessce still fails: I'm branch from this branch and make another PR for that.

Make datasets robust against missing contributors

---

CHANGELOG-email-link-icons.md
context/app/static/js/components/Footer/Footer.jsx
context/app/static/js/components/detailPage/Attribution/Attribution.jsx
context/app/static/js/components/detailPage/files/GlobusLinkMessage/GlobusLinkMessage.jsx
context/app/static/js/components/error/ErrorBody/ErrorBody.jsx
context/app/static/js/components/home/DataUseGuidelines/DataUseGuidelines.jsx
context/app/static/js/components/home/DataUseGuidelines/style.js
context/app/static/js/pages/Publication/Publication.jsx
context/app/static/js/shared-styles/Links/iconLinks/EmailIconLink/EmailIconLink.jsx
context/app/static/js/shared-styles/Links/iconLinks/EmailIconLink/index.js

Fix #2016.
I opted to add `mailto:` inside the `EmailLinkIcon` component. Should I use a proper name other than `href` to make this more clear?

John conroy/email link icons

---

CHANGELOG-create-publish.md
context/app/static/js/components/detailPage/Summary/Summary.jsx
context/app/static/js/components/detailPage/Summary/Summary.spec.js
context/app/static/js/components/detailPage/SummaryBody/SummaryBody.jsx
context/app/static/js/pages/Dataset/Dataset.jsx

- Fix #1754
@tsliaw , does this seem ok? If a Dataset is unpublished, giving the creation date is probably more useful than just showing "Undefined". Mostly, I want to avoid having a separate component for Datasets that isn't shared with Samples and Donors.

use publication date, if available

---

CHANGELOG-publications-readme.md
context/app/publication/README.markdown

Coming out of the UI meeting, the proposal was a google doc... but I think it would be more helpful to keep this documentation near the files. The authors will have a set of examples at hand, and if the structure needs to change, we're more like to keep everything in sync.
Is this everything we should provide?

end-user docs for publication pages

---

CHANGELOG-responsive-detail-summary.md
context/app/static/js/components/detailPage/summary/SummaryData/SummaryData.stories.js
context/app/static/js/components/detailPage/summary/SummaryData/style.js
context/app/static/js/shared-styles/sections/SectionButtonRow/style.js

The right hand text/buttons will wrap when needed as shown below, but otherwise will look as it has.

John conroy/responsive detail summary

---

CHANGELOG-colab-conflicts.md
context/app/routes_notebooks.py

Filing as draft until submodule PR is merged, and the submodule reference here can be updated:
- https://github.com/hubmapconsortium/portal-visualization/pull/36

fix colab conflicts

---

CHANGELOG-default-icon-size.md
context/app/static/js/components/Footer/Footer.jsx
context/app/static/js/components/detailPage/Citation/Citation.jsx
context/app/static/js/components/detailPage/ContributorsTable/ContributorsTable.jsx
context/app/static/js/components/detailPage/Protocol/Protocol.jsx
context/app/static/js/components/detailPage/files/GlobusLinkMessage/GlobusLinkMessage.jsx
context/app/static/js/components/detailPage/visualization/Visualization/Visualization.jsx
context/app/static/js/components/error/ErrorBody/ErrorBody.jsx
context/app/static/js/components/organ/Description/Description.jsx
context/app/static/js/pages/Collection/Collection.jsx
context/app/static/js/pages/Publication/Publication.jsx
context/app/static/js/shared-styles/icons/index.js

- Fix #2504
- Only real change is removing the prop: Larger diff because line wrapping isn't needed any longer.
- I verified that everything still looked good only for the first few that I changed.
- Three instances of `iconFontSize="1.1rem"` remain: `Attribution.jsx`, `DataUseGuidelines.jsx`, `Dataset.jsx`... Maybe they should change too?

Default link icon size

---

CHANGELOG-pin-werkzeug.md
context/requirements.txt

Pin werkzeug version to 2.03 to fix CI errors seen in https://github.com/hubmapconsortium/portal-ui/runs/5738927912?check_suite_focus=true.
From: https://werkzeug.palletsprojects.com/en/2.1.x/test/#werkzeug.test.Client.open
> Changed in version 2.1: Removed the as_tuple parameter.

John conroy/pin werkzeug

---

CHANGELOG-registered-by.md
context/app/static/js/components/detailPage/Attribution/Attribution.jsx
context/app/static/js/components/detailPage/Attribution/Attribution.spec.js
context/app/static/js/components/searchPage/config.js

- Fix #2521 
This also changes the Preview pages... but I'd prefer not to add tons of special cases: My sense is that Bill plans to add the _actual_ creator to the ES documents, and at that point the label may change again.

"Creator" -> "Registered by"

---

CHANGELOG-dev-search-assay-filters.md
context/app/static/js/pages/search/DevSearch.jsx

- Follow-up to  https://github.com/hubmapconsortium/ingest-validation-tools/issues/1062
- Fix #2563
There are some weird analyte values.... I think the original roadmap was to ask NIH if this would be useful. If it looks like it still could be useful, but we want to understand the data first, do you want to file an issue for that?

Two new filters on dev-search

---

CHANGELOG-clear-mocks.md
context/jest.config.js

I'm going to be mocking the console to silence warnings, but it seems good to restore mocks for each test to avoid side-effects. I'm surprised it's not the default.
I think [`restoreMocks`](https://jestjs.io/docs/configuration#restoremocks-boolean) ("This will lead to any mocks having their fake implementations removed and restores their initial implementation") is better here than `clearMocks` ("This does not remove any mock implementation that may have been provided.") or `resetMocks` ("This will lead to any mocks having their fake implementations removed but does not restore their initial implementation.")

restore mocks

---

CHANGELOG-sort-configure-table.md
context/app/static/js/components/entity-search/SearchWrapper/utils.js
context/app/static/js/components/entity-search/SearchWrapper/utils.spec.js
context/app/static/js/components/entity-search/sidebar/ConfigureSearchTable/ConfigureSearchTable.jsx
context/app/static/js/components/entity-search/sidebar/ConfigureSearchTable/hooks.js
context/app/static/js/components/entity-search/sidebar/ConfigureSearchTable/utils.js
context/app/static/js/components/entity-search/sidebar/ConfigureSearchTable/utils.spec.js
context/app/static/js/components/entity-search/sidebar/DatasetConfigureSearchTable/hooks.js

Sorts the configure table by 'General' non-metadata fields then entity type primarily and alphabetically secondarily. 
@mccalluc I removed 'version' from the available fields, do you know of other fields that we might not want available?

John conroy/sort configure table

---

CHANGELOG-fix-source-sample-access.md
context/app/static/js/components/entity-search/ResultsTable/ResultsTable.jsx
context/app/static/js/components/entity-search/ResultsTable/utils.js
context/app/static/js/components/entity-search/ResultsTable/utils.spec.js
context/app/static/js/components/entity-search/SearchWrapper/metadataDocumentPaths.js
context/app/static/js/components/entity-search/SearchWrapper/utils.js

As we discussed, `source_sample` inside dataset es documents are arrays and must be handled differently.

John conroy/fix source sample access

---

CHANGELOG-fix-configure-facet-bug.md
context/app/static/js/components/entity-search/facets/Facets/hooks.js

State would update before results causing an error.

John conroy/fix configure facet bug

---

CHANGELOG-update-matomo-id.md
context/app/static/js/helpers/trackers.js

Before merging this, we should confirm that it's logging events correctly. To do that, we need to add localhost to the list: I don't have privs. When setting up sites in the dashboard, Matomo only cares about the integer ID: The mapping from hostname to integer ID happens in our code.
- @ngehlenborg, please add websites `2` (localhost) and `3` (other) at https://hubmap.matomo.cloud/index.php?module=SitesManager.
- I think you'll also need to add John, Tiffany, and myself as users on each site. (Permissions go site by site.)
- @john-conroy, when that's done, checkout this branch, load http://localhost:5001 in one window, and look at https://hubmap.matomo.cloud/index.php in the other: You should see events being logged.

update matomo host

---

CHANGELOG-add-more-default-filters.md
context/app/static/js/components/entity-search/SearchWrapper/SearchWrapper.jsx
context/app/static/js/components/entity-search/searchkit-modifications/getDefaultFilters.js

Adds default filters to remove entities with `sub_status` and `next_revision_uuid`. The results should now match the existing search page.

John conroy/add more default filters

---

CHANGELOG-add-more-default-filters.md
CHANGELOG-default-sort.md
context/app/static/js/components/entity-search/Search/Search.jsx
context/app/static/js/components/entity-search/SearchWrapper/SearchWrapper.jsx
context/app/static/js/components/entity-search/searchkit-modifications/getDefaultFilters.js
context/app/static/js/components/entity-search/searchkit-modifications/useSearchkitSDK.js

Alternatively I could modify the `buildField` and `buildSortPairs` utils to build `mapped_last_modified_timestamp.keyword.desc`, but I think it's better to keep things simple as this is unlikely to change.

John conroy/default sort

---

CHANGELOG-workspace-header-plural.md
context/app/static/js/components/workspaces/WorkspacesList.jsx

I think "0 Workspaces" (with the "s") sounds right?
Right now what I see in the header is
> 0 Workspace0

Fix plurals in workspace section header.

---

CHANGELOG-service-dep-message.md
context/app/static/js/components/ServiceStatusTable/ServiceStatusTable.jsx

- Would fix #2719
Up to you, Nils, whether this is needed or not: I was unaware of the dependency, and it feels like it might be useful to someone if they were looking at the services page, trying to debug an outage. But maybe it's clutter.

Trivial change to Services page

---

CHANGELOG-not-substring.md
context/app/static/js/components/cells/AutocompleteEntity/AutocompleteEntity.jsx

- Fix #2766
I'm not confident this is the right choice... would it be better to say `gene or protein` or either `gene` or `protein` depending on the context?
(Whatever the name is here, I think keeping the same name internally makes sense: Devs are just going to think of it as a substring.)

change to "marker"... or "Select gene to query"

---

CHANGELOG-keyerror-files.md
context/app/api/client.py

- Towards #2772
Instead of failing in python, vitessce load now fails... which is a little better.

Fix `KeyError: 'files'`

---

CHANGELOG-profile-find-vis-bugs.md
scripts/qa/find-vis-bugs.py

Zhou might be using this as part of the index update process, so I was thinking about speeding it up... but before going there, I wanted to understand what was actually slow. In the process, realized that #2811 broke this script.

profile find-bugs

---

CHANGELOG-ws-ui.md
context/app/static/js/components/workspaces/JobDetails.jsx
context/app/static/js/components/workspaces/JobLink.jsx
context/app/static/js/components/workspaces/JobStatus.jsx
context/app/static/js/components/workspaces/WorkspaceDetails.jsx
context/app/static/js/components/workspaces/WorkspacesList.jsx
context/app/static/js/components/workspaces/style.js
context/app/static/js/components/workspaces/utils.js
context/app/static/js/shared-styles/Links/index.js

Present a uniform UI for workspaces, regardless of whether Jupyter is already running, or if it needs to be started from scratch. We're getting into territory where we're disguising how the system works behind the scenes, and that worries me a little.
@tsliaw :
- Is this acceptable, as far as it goes?
- How should we handle workspaces with no active jobs?
- This reminded me what #2746 was for. I'll branch from this and implement a stop-gap.

Bring the Workspaces closer to the design

---

CHANGELOG-ws-no-name.md
context/app/routes_notebooks.py

RIght now, it looks for a query parameter with the name of the workspace ... but my understanding of the planned UI is that there will be no prompt for a name, and the workspaces will be assigned names like "HBM989.VVXT.224 Workspace". If that is correct, this is a small step in the right direction.

users do not supply name when creating workspace

---

CHANGELOG-fix-log-script.md
etc/qa/query-portal-logs.py

Same approach as #2821. You may have an idea for moving the `sys.path.append` code block to a utils file (or whatever the Python convention is...) for reuse between scripts. Alternatively, I could move the  `portal-logs-errors` output dir down to `etc/qa`.

John conroy/fix log script

---

CHANGELOG-workspaces-link.md
context/app/static/js/components/Header/UserLinks/UserLinks.jsx

- Should `userEmail` also be pulled from context, since it's there? Or is there an argument for passing things explicitly, sometimes?
- I think the plan for the future would be for this not to be conditional: If they aren't logged in, the workspaces page doesn't do much, but we'd still link to it?

add workspaces link to menu

---

CHANGELOG-reenable-ws-delete.md
context/app/static/js/components/workspaces/WorkspacesList.jsx

Juan had disabled it in the API for some repairs, and the timeline was uncertain... Turns out it was relatively quick.

Reenable WS deletion

---

CHANGELOG-preserve-cells-order.md
context/app/static/js/components/cells/DatasetsSelectedByExpression/hooks.js
context/app/static/js/components/cells/DatasetsSelectedByExpression/hooks.spec.js

Previously order was determined by `search-api`, this will preserve order from cells service.
Ideally we could use elasticsearch's `_mget` endpoint which allows us to fetch the documents given `_id`s which will retain the order of the `_id`s included in the request body. I'll reach out to Bill to see if this is feasible.

John conroy/preserve cells order

---

CHANGELOG-v3-conf.md
context/app/api/client.py
context/app/default_config.py
context/app/static/js/components/ServiceStatusTable/ServiceStatusTable.jsx
context/app/utils.py

This change could have been made in env or in commons... but since we forgot to make the changes there before migration, it makes sense to make it here.
Going forward, if there's a "v4", there's one line that will need to be changed in `portal-ui` and no env change will be required.
On the service page, the new entry looks like:
> type-api	Up	https://search.api.hubmapconsortium.org/v3	search-adaptor 3.0.1	main:2e984ee	Included in search-api for historical reasons.

Update typeservice to V3

---

CHANGELOG-bump-ccf-path.md
context/app/default_config.py

- Follow-up to #2924
For now, I assume it makes sense for all of these to be using the same version, even thought they are all accessing different resources under `v3`. This is mostly a FYI.

version index for ccf

---

CHANGELOG-bump-portal-vis.md
context/requirements.in
context/requirements.txt

- Fix #2949
- I was definitely the one who introduced the bug... but it worries me that this was published without anyone raising an alarm. (I'm also a little concerned that new unstitched datasets are still being published.)

bump version number for portal-vis

---

CHANGELOG-powered-by.md
context/app/static/js/components/detailPage/visualization/Visualization/Visualization.jsx

Reviewing Ilan's PR it struck me that it could be useful to have a better exposure of the vitessce version number... Normally, wouldn't bother the user with too many internals, but since the string is already there, adding more info doesn't seem bad.... but it's fine not to approve this: Just an idea.

show vitessce version number

---

CHANGELOG-pass-job-types-id-on-start.md
context/app/static/js/components/workspaces/utils.js

Handle newly required `job_types_id` on PUT to start workspace job.

John conroy/pass job types id on start

---

CHANGELOG-handle-sample-category.md
README-deploy-qa.md
context/app/routes_api.py
context/app/static/js/components/detailPage/SampleTissue/SampleTissue.jsx
context/app/static/js/components/detailPage/SampleTissue/SampleTissue.spec.js
context/app/static/js/components/detailPage/derivedEntities/DerivedSamplesTable/DerivedSamplesTable.jsx
context/app/static/js/components/detailPage/entityHeader/EntityHeader/utils.js
context/app/static/js/components/detailPage/provenance/ProvTable/ProvTable.jsx
context/app/static/js/components/detailPage/summary/Summary/Summary.stories.js
context/app/static/js/components/entity-search/SearchWrapper/utils.js
context/app/static/js/components/entity-tile/EntityTile/EntityTile.stories.js
context/app/static/js/components/entity-tile/EntityTileBody/EntityTileBody.jsx
context/app/static/js/components/home/FacetSearch/FacetSearch.jsx
context/app/static/js/components/searchPage/config.js
context/app/static/js/components/tutorials/SearchDatasetTutorial/config.js
context/app/static/js/hooks/useDerivedEntitySearchHits.js
context/app/static/js/pages/Sample/Sample.jsx
context/app/static/js/pages/entity-search/DatasetSearch/DatasetSearch.jsx
context/app/static/js/pages/utils/entity-utils.spec.js

Replacing `mapped_specimen_type` and `specimen_type` with `sample_category`. There will be a follow-up in `search-api`'s `portal-translations` to capitalize the values and added grouped counts of `sample_category` values to `descendant_counts` and later here to use the new mapped field.

John conroy/handle sample category

---

CHANGELOG-source-in-publications-request.md
context/app/static/js/pages/Publications/hooks.js

Decreases publications response size on landing page.

Add source to publications request

---

CHANGELOG-publication-authors.md
context/app/static/js/components/detailPage/ContributorsTable/ContributorsTable.jsx
context/app/static/js/pages/Publication/Publication.jsx

Towards #3035. Add authors section to publication page.

John conroy/publication authors

---

CHANGELOG-use-es-for-dataset-collections.md
context/app/static/js/hooks/useDatasetsCollections.js

Fix #3084. Use es terms query to return collections which contain one of the given UUIDs in its datasets array.

John conroy/use es for dataset collections

---

CHANGELOG-workspace-globus-group.md
context/app/main.py
context/app/routes_auth.py
context/app/static/js/components/App.jsx
context/app/static/js/components/Header/UserLinks/UserLinks.jsx
context/app/static/js/components/Providers.jsx
context/app/static/js/index.jsx
context/app/static/js/pages/Dataset/Dataset.jsx
context/app/static/js/pages/Workspaces/Workspaces.jsx
context/app/templates/base-pages/base.html
context/app/utils.py
context/test-utils/functions.js

Fix #3080. Filed #3087 to remove workspaces allow list down the road.
The way data is passed from flask is inconsistent and requires drilling the data through multiple functions. We already have #2653 and I filed #3088.

John conroy/workspace globus group

---

CHANGELOG-fix-collection-hook-deps.md
context/app/static/js/hooks/useDatasetsCollections.js

Fix bug introduced in #3085. Filed an issue in jira to introduce https://swr.vercel.app/ for our fetch hooks. One benefit of the library is that the `useSWR` hook performs deep compares for its dependencies and we wouldn't have to memoize arrays or objects.

John conroy/fix collections hook deps

---

CHANGELOG-replace-to-sorted.md
context/app/static/js/hooks/useDatasetsCollections.js

`toSorted` isn't supported by Firefox. 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toSorted#browser_compatibility

John conroy/replace to sorted

---

.vscode/settings.json
CHANGELOG-fix-publication-vignettes.md
context/app/static/js/components/detailPage/visualization/Visualization/Visualization.jsx
context/app/static/js/components/detailPage/visualization/VisualizationWrapper/VisualizationWrapper.jsx
context/app/static/js/components/publications/PublicationVignette/PublicationVignette.jsx
context/app/static/js/components/publications/PublicationVisualizationsSection/PublicationsVisualizationSection.jsx
context/app/static/js/hooks/useStickyToggle.js
context/app/static/js/pages/Donor/Donor.jsx
context/app/static/js/pages/Publication/Publication.jsx
context/app/static/js/pages/Sample/Sample.jsx

This PR adjusts the behavior of the vitessce visualizations on the publication page:
- All accordion contents are initially rendered to prefetch vitessce conf
- Vitessce conf fetching is disabled when a conf already exists for that vignette
- Stale requests for vitessce conf data are aborted if effect re-triggers before it completes
- The `Vitessce` component is only mounted once the accordion it's in finishes expanding
In essence, this PR should make it so that the animation of switching from one vignette to another goes smoothly in more cases; however, this still has limitations. If a user tries to go to another vignette while the current one is still loading, the event does not immediately register; this is because Vitessce fires a lot of effects etc when it's first mounted which …

NickAkhmetov/HMP-19 Improve perceived performance of vignette accordion on publication pages

---

CHANGELOG-fix-minor-publication-errors.md
context/app/static/js/components/Routes/Routes.jsx
context/app/static/js/components/detailPage/StatusIcon/StatusIcon.jsx
context/app/static/js/components/entity-search/facets/FacetAccordion/style.js
context/app/static/js/components/entity-search/facets/FacetGroupAccordion/style.js
context/app/static/js/components/publications/PublicationCitation/PublicationCitation.jsx
context/app/static/js/components/publications/PublicationSummary/PublicationSummary.jsx
context/app/static/js/components/publications/PublicationVisualizationsSection/PublicationsVisualizationSection.jsx
context/app/static/js/components/searchPage/filters/FilterInnerAccordion/style.js
context/app/static/js/components/searchPage/filters/FilterOuterAccordion/style.js
context/app/static/js/components/searchPage/filters/style.js
context/app/static/js/shared-styles/accordions/PrimaryColorAccordionSummary/style.js
context/app/static/js/shared-styles/accordions/StepAccordion/StepAccordion.jsx
context/app/static/js/shared-styles/accordions/StepAccordion/style.js
context/app/static/js/shared-styles/sections/LabelledSectionText/LabelledSectionText.jsx
context/app/static/js/theme.jsx

This PR cleans up some of the errors we would see in the browser console when viewing the Publication page:
- `createMuiTheme` function call has been changed to `createTheme`
- `vignette_json` now has a proptypes entry
- `doiUrl` string that always evaluates to true is no longer used as divider condition
- Import the `Accordion` components instead of the deprecated `ExpansionPanel`
- Add handling for `SUBMITTED` status to StatusIcon
The following errors remain in the browser console:
- Entity/Provenance API failures (I'm assuming this is dev env only)
- `fade` color utility was renamed to `alpha` - this appears to be from MUI internals, nothing in our code uses the `fade` utility
- Any errors coming from the Vitessce component (e.g. a missing key for list items error, mipmap generation, …

NickAkhmetov/ Publication Page console error bugfixes

---

CHANGELOG-start-workspace-on-workspaces-page.md
context/app/routes_notebooks.py
context/app/static/js/components/entity-search/MetadataMenu/hooks.js
context/app/static/js/components/workspaces/WorkspaceDetails/WorkspaceDetails.jsx
context/app/static/js/components/workspaces/WorkspacesList.jsx
context/app/static/js/components/workspaces/hooks.js
context/app/static/js/components/workspaces/utils.js
context/app/static/js/pages/Dataset/Dataset.jsx
context/app/static/js/pages/Dataset/hooks.js
context/package-lock.json
context/package.json

Workspaces are now started when launching on the workspace page or in actions where a workspace is created and launched immediately. Previously, workspaces were started on the loading page which caused workspaces you may have stopped to start again unexpectedly.
Introduces [swr](https://swr.vercel.app/docs/getting-started) to better manage external data. The workspaces data used to generate the workspaces list is revalidated when `mutate` is called and, among other situations, when a tab is refocused. Workspace lists across tabs should now reflect each workspace's true status.

john-conroy/start workspaces on workspace page HMP-7

---

CHANGELOG-hmp-97-add-download-notebook-to-expanded-view.md
context/app/static/js/components/detailPage/entityHeader/EntityHeaderContent/EntityHeaderContent.jsx
context/app/static/js/components/detailPage/visualization/Visualization/Visualization.jsx
context/app/static/js/pages/Dataset/Dataset.jsx
context/app/static/js/stores/useVisualizationStore.js

This PR adds the Jupyter Notebook download button to the expanded visualization view.
- vizNotebookId / setVizNotebookId states have been added to the Visualization store
- When a visualization with a notebook mounts, the vizNotebookId is set to the uuid of the visualization; if the visualization does not have a notebook, the value is set to null.
- The `EntityHeaderContent` component accesses the `vizNotebookId` value in the store and conditionally inserts the download button if it's not null.
**Screenshot** with tab-focused button visible at the top right:

NickAkhmetov / HMP-97 Add Jupyter Notebook download button to expanded visualization

---

CHANGELOG-hmp-102-fix-expanded-preview.md
context/app/static/js/components/detailPage/visualization/Visualization/style.js

This PR adjusts the height offset of the vitessce container when it's expanded on the preview page; there was previously an exception for paths starting with `/preview` which excluded the entity header from being included in this offset.
I'm holding off from requesting reviews until after the long weekend so as to not disturb anyone's rest; I just had some spare time with nothing to do so I figured I'd pick a low-hanging fruit 😄 
Expanded preview page visualization after changes:

NickAkhmetov / HMP-102 Fix header offset of vitessce container on preview page

---

CHANGELOG-add-file-browser-to-publication-page.md
context/app/api/client.py
context/app/routes_browse.py
context/app/static/js/components/Routes/Routes.jsx
context/app/static/js/components/detailPage/files/FileBrowserDirectory/FileBrowserDirectory.jsx
context/app/static/js/components/detailPage/files/FileBrowserFile/FileBrowserFile.jsx
context/app/static/js/pages/Publication/Publication.jsx

Adds files section to publication pages. While we do have pipeline support for publications with files, no publications with files exist now.
@tsliaw The mockup doesn't include Globus links, but the typical files section includes Globus links for both the main entity and 'support' entity.

John conroy/add file browser to publication page HMP-9

---

.vscode/settings.json
CHANGELOG-hmp-100-fix-vitessce-conf-gen-errors.md
context/app/api/client.py
context/app/static/js/components/detailPage/entityHeader/EntityHeaderContent/EntityHeaderContent.jsx

This PR
- Fixes support page entity header so the application doesn't crash to a white screen when scrolling down on Support entities' pages
- Adds handling for cases where the image pyramid descendants are missing file metadata
- Add more informative error messages on vitessce conf gen failures

NickAkhmetov / HMP-100 Improve vitessce conf generation errors

---

CHANGELOG-fix-publication-duplication.md
context/app/static/js/pages/Publications/hooks.js
context/app/static/js/pages/Publications/utils.js
context/app/static/js/pages/Publications/utils.spec.js

Fix duplication of publications as both published and pre-print.
We should fetch the publications data differently instead of making one big request. Ideally we'd make an aggregations request to populate the counts published/pre-print tabs, and then separate scrolling requests for each tab. We really only expect a handful of publications in the short to medium term so I've filed an issue and will table it for now.

John conroy/fix publication duplication HMP-140

---

CHANGELOG-hmp-113-fix-provenance-table.md
context/app/static/js/components/detailPage/provenance/ProvTable/ProvTable.jsx

The previous `isSampleSibling` logic was using the `Sample` entity type string as the source array for `sample_category` comparison. This led to a typerror being thrown when there were more samples than the length of this string.
This PR fixes the logic to compare the current sample's `sample_category` to the previous one by using the sorted `items` from the `.map` method signature to access the previous item.
To verify fix:
- attempt to access this dataset  on prod: https://portal.hubmapconsortium.org/browse/dataset/d15a20b5c07c638e758a25bb320091e1
- attempt to access this dataset on this branch: http://localhost:5001/browse/dataset/d15a20b5c07c638e758a25bb320091e1

Nickakhmetov/HMP-113 Fix provenance table sample calculation logic

---

CHANGELOG-vitessce-v3.md
context/app/preview/cell-type-annotations.md
context/app/preview/multimodal-mass-spectrometry-imaging-data.md
context/app/static/js/components/detailPage/visualization/Visualization/Visualization.jsx
context/app/static/js/components/detailPage/visualization/VisualizationWrapper/VisualizationWrapper.jsx
context/app/static/js/components/publications/PublicationVignette/PublicationVignette.jsx
context/package-lock.json
context/package.json

Fixes the bugs on the preview pages and upgrades to Vitessce v3.0.0.
The changes related to UUIDs originate from not previously having examples with more than one `<Vitessce/>` element rendered on the same HTML page.
The fixes in this PR are needed as of v3.0.0, but they are not ideal.
I am trying to remove the need for the UUID logic, hopefully in a v3.0.1:
- Removing the need for the changes related to `config.uid`: https://github.com/vitessce/vitessce/pull/1587 
- Removing the need for a `uid` prop on the `<Vitessce/>` component: https://github.com/vitessce/vitessce/pull/1596

Bump Vitessce version and add uids to Vitessce configs

---

CHANGELOG-hmp-174-fix-metadata-table.md
context/app/static/js/components/detailPage/MetadataTable/MetadataTable.jsx

Following up on #3126, I was able to identify which change caused the regression we observed after @lchoy isolated the commits which it happened in; this revert should correct the display of metadata tables.
The `mapped_metadata` in flaskData did not include 
Example dataset:

HMP-174 Restore `MetadataTable` props

---

CHANGELOG-hmp-99-fix-marker-genes
context/requirements.in

This PR is to be merged in only after merge of https://github.com/hubmapconsortium/portal-visualization/pull/78 and release; I'm marking this as a draft in the meantime.
This PR bumps the version of portal-visualization to implement the fixes related to HMP-99 which were done in the scope of that version change.

NickAkhmetov / HMP-99 Bump portal-visualization version to 0.0.11

---

CHANGELOG-donor-hotfix.md
context/app/static/js/pages/Donor/Donor.jsx

This builds on to my previous hotfix for #3127 to restore metadata table functionality on the donor page after fixing it on the other browse pages.

NickAkhmetov / Hotfix Donor Page Metadata Table

---

 CHANGELOG-hmp-183-fix-donor-derived-samples.md
CHANGELOG-hmp-183-fix-donor-derived-samples.md
context/app/static/js/components/detailPage/derivedEntities/DerivedEntitiesSection/DerivedEntitiesSection.jsx

This PR fixes a minor error in variable referencing; `entityType` was undefined when referenced from flask data due to flask data variables being formatted in `snake_case` instead of `camelCase` for easy searchability between the front/back end.
https://portal-prod.stage.hubmapconsortium.org/browse/donor/7adf466f027c44278e19b57fb59bacdc
http://localhost:5001/browse/donor/7adf466f027c44278e19b57fb59bacdc

HMP-183 Fix `entityType` TypeError blocking donor pages

---

CHANGELOG-remove-non-datasets-from-datasets-charts.md
context/app/static/js/components/home/HuBMAPDatasetsChart/HuBMAPDatasetsChart.jsx
context/app/static/js/components/organ/OrganDatasetsChart/OrganDatasetsChart.jsx
context/app/static/js/helpers/queries.js

Removes publications and other dataset subtypes from dataset charts. Also, removes the already merged changelog. I believe it wasn't cleaned up because it wasn't a markdown file?

John conroy/remove dataset subtypes from charts HMP-185

---

CHANGELOG-hmp-99-fix-marker-genes
CHANGELOG-remove-support-files-from-publications.md
context/app/routes_browse.py
context/app/static/js/components/Routes/Routes.jsx
context/app/static/js/pages/Publication/Publication.jsx

Remove globus link for lifted publication ancillary entities on publication pages.

John conroy/remove support files from publications HMP-175

---

context/app/static/js/components/App.jsx

This PR fixes the white screen currently blocking site access.
Since `userGroups` has a default of `[]` in its destructuring assignment, it looks safe to do `userGroups.includes`; however, when I spun `main` up locally, I instantly ran into a type error that blocked the homepage from loading due to `userGroups`' value being `null`. As documented in the `MDN`, [the default value is not applied if the key is `null`, only if it is `undefined`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#default_value)

NickAkhmetov / Hotfix null user groups case

---

CHANGELOG-hmp-207-fix-line-break.md
context/app/static/js/components/detailPage/summary/SummaryData/SummaryData.jsx
context/app/static/js/components/publications/PublicationSummary/PublicationSummary.jsx

This PR adjusts the publication header to match designs:
- The DOI no longer has a divider after it
- The header information now appears in one line if it fits; otherwise, it wraps after the DOI.
- The header change is only applied to the publication page; a refactor may be in order eventually to make the header components easier to work with.
Sample publication page:
Sample publication page with wrapping on smaller viewport:
Sample dataset page (unchanged):

NickAkhmetov/HMP-207 Fix publication header

---

CHANGELOG-hmp-229.md
context/app/static/js/components/App.jsx
context/app/static/js/components/detailPage/files/PDFViewer/PDFViewer.jsx
context/jest.config.js
context/package-lock.json
context/package.json

Separate PR for the react-pdf upgrade - seems to work fine after testing, but since it involved a bit of reconfiguration I figured it makes sense to split it off from the rest of the upgrade for now. Since this is related to the React 18 upgrade, I based this PR on that branch.
The perceivable benefits of the version bump are some simplification of Jest config (no more special handling for react-pdf import) and the offloading of PDF processing from the main thread, meaning there's less of a freeze-up when the PDF loads.

HMP-229 Upgrade React-PDF

---

CHANGELOG-hmp-103-round-2.md
CHANGELOG-hubmap-logo.md
context/app/static/assets/svg/hubmap-logo.svg

This PR fixes the style of the HuBMAP SVG to remove the `fill:white` style defined on the file level. The color is now properly applied as white in the header and as purple in the footer.

HMP-225 Remove element-level white fill style

---

CHANGELOG-collection-dataset-query.md
context/app/static/js/components/detailPage/CollectionDatasetsTable/CollectionDatasetsTable.jsx
context/app/static/js/components/detailPage/CollectionDatasetsTable/hooks.js
context/app/static/js/components/detailPage/CollectionDatasetsTable/style.js
context/app/static/js/components/detailPage/derivedEntities/columns.js
context/app/static/js/components/publications/PublicationRelatedEntities/hooks.js
context/app/static/js/shared-styles/tables/EntitiesTable/style.js

- Get collection datasets from separate search-api query instead of the collection es document.
- Use `RelatedEntitiesTable` for display.
- Fix display of organ column.

John conroy/collection dataset query HMP-257

---

CHANGELOG-hmp-204-preprint-date-change.md
context/app/routes_api.py
context/app/static/js/components/detailPage/summary/Summary/Summary.spec.js
context/app/static/js/components/detailPage/summary/SummaryBody/SummaryBody.jsx
context/app/static/js/components/publications/PublicationSummary/PublicationSummary.jsx
context/app/static/js/components/publications/PublicationsPanelList/utils.js
context/app/static/js/components/publications/PublicationsPanelList/utils.spec.js
end-to-end/cypress/e2e/portal/publication-page.cy.js

This PR
- Adjusts the date text in preprint search results on the `publications` page from `published` to `preprint date` to avoid confusion
- Adjusts the `publication date` label and `publication` entity name (above publication name) on the publication pages of preprints to indicate that the user is viewing a preprint
Screenshots were taken the `test` environment.
Published search results:
Preprint search results:
Published publication page:
Preprint publication page:

Nickakhmetov/HMP-204 Change preprint date label and standardize "last modified date"

---

CHANGELOG-scroll-prov.md
context/app/static/js/components/detailPage/provenance/NodeElement/NodeElement.jsx
context/app/static/js/components/detailPage/provenance/ProvGraph/ProvGraph.jsx
context/app/static/js/components/detailPage/provenance/ProvGraph/ProvGraph.spec.js
context/app/static/js/components/detailPage/provenance/ProvGraph/style.js
context/app/static/js/stores/useProvenanceStore.js

Feels a bit hacky. I had a slightly less hacky version before the [commit to introduce the dom selector](https://github.com/hubmapconsortium/portal-ui/commit/13475bd7d1c001e34e94fd8228e00eda236c4d6f), but the detail pane would be inside the scrollbox without the changes introduced in the commit.
Initial position without detail pane.
Initial position with detail pane outside of scrollbox.
Graph without scroll.

John conroy/scroll prov HMP-258

---

CHANGELOG-publication-collection-aggs.md
context/app/static/js/components/publications/AggsList/AggsList.jsx
context/app/static/js/components/publications/AggsList/hooks.js
context/app/static/js/components/publications/PublicationSummary/PublicationSummary.jsx
context/app/static/js/pages/Publication/Publication.jsx

There is room for some refactoring to remove the additional request when an associated collection is not present and to push the datasets mapping inside the SWR fetcher so it's only run once, but I wanted to get this out sooner.

John conroy/publication collection aggs HMP-270

---

CHANGELOG-hmp-269-implement-publication-slide.md
context/app/routes_main.py
context/app/static/js/components/home/ImageCarouselContainer/ImageCarouselContainer.jsx
context/app/utils.py

This PR adds a flag sent from the server-side which is enabled after the unix timestamp passes 2023-07-19 at 15:00:00 UTC (the end of the publication embargo). This behavior can be overridden by adding the `ENABLE_PUBLICATIONS` key to `app.conf` and setting it to `True` for ease of testing (e.g. in `dev`/`test`)
The time gate works by running a comparison of the current unix timestamp against the timestamp of 2023-07-19 at 15:00:00 UTC (1689778800). I cross-checked the timestamp from `datetime.now().timestamp()` with https://www.unixtimestamp.com/ (which I used to derive the embargo expiration timestamp) to confirm this method works for all time zones.
The flag enables the new hubmap publications slide, which links to `/publications` with its get started button and pulls the proper image …

Nickakhmetov/HMP-269 Implement time-gated publication slide

---

CHANGELOG-hmp-275.md
context/app/static/js/components/detailPage/related-entities/RelatedEntitiesSectionHeader/RelatedEntitiesSectionHeader.jsx
context/app/static/js/components/publications/PublicationRelatedEntities/PublicationRelatedEntities.jsx

I adjusted the approach to displaying the tooltip text so that it has to be passed in to the `RelatedEntitiesSectionHeader` instead of it providing its own hardcoded tooltip.

Nickakhmetov/HMP-275 Fix publication tooltip appearing on other pages

---

context/app/static/js/components/detailPage/BulkDataTransfer/FilesConditionalLink.jsx
context/app/static/js/components/detailPage/BulkDataTransfer/GlobusLink.jsx
context/app/static/js/components/detailPage/BulkDataTransfer/Link.jsx
context/app/static/js/components/detailPage/BulkDataTransfer/style.js

Fix handling of Globus support links to reflect design. The tooltip should only be shown on support links.
Fix styling of dbGaP links.

John conroy/fix globus support

---

CHANGELOG-fix-conditional-link-icon.md
context/app/static/js/components/detailPage/BulkDataTransfer/FilesConditionalLink.jsx
context/app/static/js/components/detailPage/BulkDataTransfer/style.js

The icon wasn't showing before the DUA has been agreed upon.

John conroy/fix conditional link icon

---

CHANGELOG-no-auth-for-unauthed.md
context/app/static/js/components/publications/PublicationVignette/hooks.ts

This PR disables the auth header/groups token inclusion when the current user is not logged in in order to enable access to publication vignettes in Globus after the embargo is up.
Screenshot taken with env pointed at the stage endpoints, note the `Log In` prompt at the top right as evidence of being unauthed:
Original slack discussion for posterity: https://hubmapconsortium.slack.com/archives/C011RF3NQ23/p1689702903588899

NickAkhmetov/HMP-294 - No header for unauthenticated users

---

CHANGELOG-reverse-toc-nowrap.md
context/app/static/js/shared-styles/sections/TableOfContents/style.js

Reversing styles recently introduced which cause overflow in the table of contents.
Before
After

John conroy/reverse toc nowrap

---

.vscode/tasks.json
CHANGELOG-dev-args.md
end-to-end/cypress/e2e/portal/publication-page.cy.js
etc/dev/dev-start.sh

This PR adds options to the `dev-start` script which allow us to skip pip/npm installs if necessary; this change was motivated by my other current ticket (upgrading the vitessce-python version in portal-visualization). The script still runs as expected without args, and the `start` alias also accepts these args.
Fixes #3107 
---
`-h` shows help text
`-n` and `--no-npm-install` skip the `npm install` line
`-p` and `--no-pip-install` skip the `pip install` line
`-s` and `--skip-install` skips both installs

NickAkhmetov/HMP-295 Add args to dev-start script / create `tasks.json` file / disable flaky entity header test

---

CHANGELOG-fix-protocols-errors.md
context/app/static/js/components/Providers.jsx
context/app/static/js/components/detailPage/Protocol/Protocol.jsx
context/app/static/js/helpers/swr.ts
context/app/static/js/hooks/useProtocolData.js
context/app/static/js/shared-styles/Links/HelpLink.tsx

Fixes the handling of loading and errors for protocols.io requests in protocols section. Previously the non-200s were not being treated as errors and the resulting display matches what is shown in https://hms-dbmi.atlassian.net/browse/HMP-306. That being said, the requests were only failing locally due to our out of date `app.conf` files. Requests on PROD should work.
I'm not sure if the mismatched key passed to `protocolsContext` in `Providers` would have caused any issues ( it does not seem like we're using this context anywhere?), but I fixed it to match the types defined in `ProctocolAPIContext`. Should typescript have picked this up?
I've also added `HelpLink` to be used throughout the application. I've filed https://hms-dbmi.atlassian.net/browse/HMP-307.
200
Non-200

John conroy/fix protocols errors HMP-306

---

CHANGELOG-fix-storybook-typescript.md
context/.storybook/main.js
context/package-lock.json
context/package.json

Storybook was failing to load as it was treating typescript files as javascript since it compiles with babel by default. Configuring storybook to use `swc` with `storybook-addon-swc` seems to fix it.

John conroy/fix storybook typescript

---

CHANGELOG-HMP-302-Implement-icons-for-entity-headers-and-tables-Swedlow-feedback-response.MD
context/app/static/js/components/Header/HeaderContent/HeaderContent.jsx
context/app/static/js/components/Header/HeaderContent/style.js
context/app/static/js/components/detailPage/provenance/ProvTable/ProvTable.jsx
context/app/static/js/components/detailPage/provenance/ProvTable/style.js
context/app/static/js/components/detailPage/related-entities/RelatedEntitiesTabs/RelatedEntitiesTabs.jsx
context/app/static/js/components/detailPage/related-entities/RelatedEntitiesTabs/style.js

The following tasks were in the story for this PR:
1. Add icon to entity header
This task had already been completed in the past so there is no additional code added. 
2. Add entity icons to header links to search pages
As mentioned in the previous pull request (https://github.com/hubmapconsortium/portal-ui/pull/3195) Tiffany requested that the entire space be clickable so padding is used for the div around the icon and text instead of margin. 
3. Add entity icons to provenance table tab for entity headers
4. Add sample and dataset icon to tabs in "Derived Sample and Datasets"
I added additional comment at the bottom in response to Nik's suggestion. 
I understand that it is not ideal to use !important, but the custom styling I was giving was getting overwritten by MUI. If there is a …

kevin-yoo/HMP-302-Implement-icons-for-entity-headers-and-tables-Swedlow-feedback-response

---

CHANGELOG-mui-qa-fixes-1.md
context/app/static/js/components/Footer/style.js
context/app/static/js/components/Header/Dropdown/Dropdown.jsx
context/app/static/js/components/Header/Dropdown/style.js
context/app/static/js/components/detailPage/provenance/ProvTable/style.js
context/app/static/js/pages/search/style.js

- Removes unnecessary `px` suffixes missed during upgrade/merge process to fix broken spacing
- Adjusts popover positioning on desktop to use the `modifiers` API from Popover v2 since margin is no longer usable for popover positioning
Prov table headers before/after:
Header dropdowns before/after:
Search headers before/after:
Footer before/after:

NickAkhmetov/HMP-314 QA Fixes after MUI 5 upgrade

---

CHANGELOG-fix-collections-header.md
context/app/static/js/components/detailPage/summary/SummaryData/style.js
context/app/static/js/shared-styles/icons/entityIconMap.js

This PR adds the Collections icon to the `entityIconMap` used for detail page headers; this was previously not present, which led to a weird spacing issue. I also fixed the margins by removing the `px` suffix.

NickAkhmetov/HMP-316 Add missing collections icon to header

---

CHANGELOG-mui-qa-fixes-1.md
CHANGELOG-mui-qa-fixes-2.md
context/app/static/js/pages/Diversity/style.js
context/app/static/js/theme.jsx

This PR restores the previous global default font sizes to address sizing issues on components which were previously using these default styles. It also updates the Diversity page to use the global PageTitle component
Fixed SRA experiment sizes: 
Fixed diversity header:

Nickakhmetov/HMP-317 HMP-318 fix font sizes

---

CHANGELOG-hmp-323.md
context/app/static/js/components/searchPage/MetadataMenu/MetadataMenu.jsx
context/app/static/js/components/searchPage/MetadataMenu/style.js

The default `underline` prop for MUI links was changed from `hover` to `always` in MUI 5. I changed the prop to `underline="none"` and removed the unnecessary extra style.

NickAkhmetov/HMP-323 Remove underline on Visualize link

---

CHANGELOG-HMP-330.md
context/app/static/js/components/cells/AutocompleteEntity/AutocompleteEntity.jsx
context/app/static/js/components/cells/QuerySelect/QuerySelect.jsx

This PR
- Fixes the centering of the protein vs. gene select
- Fixes the display of the autocomplete search results
Gene and Protein options are properly centered:
Gene lookup results are displayed as expected:
I also added a loading state so that the autocomplete doesn't flash "No results" while there's a pending lookup:

HMP-330 Fix autocomplete/selects on Molecular Data Query page

---

CHANGELOG-hmp-271.md
context/app/routes_main.py
context/app/static/js/components/Routes/Routes.jsx
context/app/static/js/components/home/ImageCarouselContainer/ImageCarouselContainer.jsx
context/app/utils.py

This PR removes the `enable_publications` flag from the flask data. The homepage is still set to display the publication slide by default, but the extra logic to determine whether the launch date/time has passed has been removed.

NickAkhmetov/HMP-271 Tear down publication time gate

---

context/app/static/js/components/entity-search/Search/Search.jsx
context/app/static/js/components/entity-search/Search/hooks.js
context/app/static/js/components/entity-search/searchkit-modifications/useSearchkitSDK.js

This PR adds an escape hatch to the current behavior of resetting selections when the results change to specifically allow users to make selections across multiple search pages on the test-search datasets page. 
Since this selection reset is defined as part of the SearchKit behavior and we're planning a revamp of it in the near future, this seemed like a good way to avoid introducing potentially unwanted behavior on the other search pages by removing the deselection logic outright. If that would be preferable, I can adjust this accordingly.
https://github.com/hubmapconsortium/portal-ui/assets/19957804/45fab5cd-2b30-4619-9ec1-3b958d08793d

NickAkhmetov/HMP-333 Persist selections on dataset test-search page

---

CHANGELOG-hmp-322-fix-donor-toc.md
context/.eslintrc.yml
context/app/static/js/components/detailPage/derivedEntities/DerivedEntitiesSection/DerivedEntitiesSection.jsx
context/app/static/js/helpers/functions.js
context/app/static/js/helpers/functions.spec.js
context/app/static/js/pages/Donor/Donor.jsx

This PR adjusts the ID used to reference the Derived Samples and Datasets section on the donor page so that it is properly translated by the ID -> title translation function for the table of contents. 
This PR also extends the logic for this function to no longer capitalize `['of', 'to', 'and', 'the', 'a']` if they are not the first word in the title and adds test cases to document this functionality.
https://github.com/hubmapconsortium/portal-ui/assets/19957804/0dc55a5c-7f2f-428f-8ff3-645081b70867

NickAkhmetov/HMP-322 Fix table of contents link to derived samples and datasets section

---

CHANGELOG-hmp-307-help-links.md
context/app/static/js/components/Footer/Footer.jsx
context/app/static/js/components/detailPage/BulkDataTransfer/usePanelSet.jsx
context/app/static/js/components/error/ErrorBody/ErrorBody.jsx
context/app/static/js/components/home/DataUseGuidelines/DataUseGuidelines.jsx
context/app/static/js/components/workspaces/WorkspacesAuthenticated.jsx
context/app/static/js/pages/Workspaces/Workspaces.jsx
context/app/static/js/shared-styles/Links/HelpLink.tsx

This PR:
- Replaces all references to emailiconlinks with an email of `help@hubmapconsortium.org` with the `HelpLink` component
- Adjusts the HelpLink component to allow overrides of the text in the link to handle an edge case where the text is "contact support"

NickAkhmetov/HMP-307 Use `HelpLink` component

---

.vscode/tasks.json
CHANGELOG-hmp-359-housekeeping.md
README.md
context/app/static/js/components/home/ImageCarouselControlButtons/ImageCarouselControlButtons.jsx
end-to-end/README.md

This PR is an effort to improve our READMEs by updating any outdated/dead links, documenting changes to our best practices, and providing instructions for various common tasks in our development process.
I also made some other minor adjustments:
- I adjusted the `Storybook` task not to depend on `npm install`; this makes the `dev-start (no install)` task function as expected.
- I fixed the `dev-start (no install)` task not having a problem matcher set, which made it prompt for a problem matcher each time it was run
- I adjusted the tabIndex for the homepage carousel controls to be passed in as a number (`{-1}` instead of `"-1"`) to remove a large warning that popped up in the dev console on the homepage

Nickakhmetov/HMP-358 Readme cleanup/housekeeping

---

CHANGELOG-swr-fixes.md
context/app/static/js/helpers/swr/errors.ts
context/app/static/js/helpers/swr/fetchers.ts

This PR fixes some minor TypeScript issues that I noticed in the SWR helpers file:
- I added a custom `SWRError` constructor to include the response info/status in the returned error object
- I fixed some minor type issues with the non-plural `fetcher` which still expected a `urls` param to be passed
In order to keep these changes separate from the new cell types page implementation, I'm making them in a separate PR. Since I am building on top of the changes in the HMP-371 PR, I'm currently using that as a base.
The build errors in this PR should be resolved when #3244 is merged.

NickAkhmetov/Fix TypeScript issues in SWR helpers

---

CHANGELOG-hmp-389-lint.md
context/app/static/js/components/cells/AutocompleteEntity/AutocompleteEntity.tsx
context/app/static/js/components/cells/AutocompleteEntity/hooks.ts

This PR fixes the lint issues that slipped through when I merged in HMP-389; since that branch was opened before updates to lint packages were added, CI did not pick up these issues earlier.

NickAkhmetov/HMP-389 Hotfix lint issues

---

context/app/markdown/CHANGELOG.md

Corrects the recent release's version number to reflect the dockerhub/git-tag version.

Update main changelog

---

CHANGELOG-hmp-409-markdown.md
context/app/static/js/components/App.jsx
context/app/static/js/components/Markdown/Markdown.jsx
context/app/static/js/components/organ/Azimuth/Azimuth.jsx
context/app/static/js/components/style.js
context/package-lock.json
context/package.json

This PR removes all usages of `marked` in favor of using `react-markdown`, which does not require us to dangerously set inner HTML. I tested the places in the application where this was in use (organ pages' `reference analysis` pane, global alert, and markdown pages such as /changelog) and confirmed functionality is unaffected.
Fixes #3067

Nickakhmetov/HMP-409 Remove `marked` in favor of `react-markdown`

---

CHANGELOG-update-reference-to-vitessce-version.md
context/app/routes_notebooks.py

Fix bug relayed by Phil in hive developers where a user had issues downloading the notebook from https://portal.hubmapconsortium.org/notebooks/entities/dataset/ade8d4ca1fd95afbafdc78a2461bab9c.ws. In the `python-vitessce` version included in the recent update of `portal-visualization`, `vitessce` no longer has a `__version__` attribute.

John conroy/update reference to vitessce version

---

CHANGELOG-hmp-315.md
context/app/static/js/components/home/ImageCarouselContainer/ImageCarouselContainer.jsx

This PR updates the homepage publication slide's text to match the ticket description:

NickAkhmetov/HMP-315 Update publication slide link

---

CHANGELOG-HMP-430.md
context/app/static/js/components/Providers.jsx

This PR fixes the calls to `faro.logError` and `faro.logWarning` - these functions don't exist and I didn't catch this in my initial implementation because `Providers` is a `.jsx` file (and thus ESLint does not throw errors when a non-existing property is referenced).
I've revised these calls to `faro.api.pushError` and `faro.api.pushEvent`, respectively.

NickAkhmetov/HMP-430 Fix Faro SWR logs

---

CHANGELOG-HMP-433-restore-search-icon.md
context/app/static/js/components/searchPage/Search.scss

This PR restores the search icon to the search pages' search bars.
This was likely a result of the upgrade to Webpack 5 a while ago, since the core error appears to be an unreadable SVG reference in the SCSS code.
Since this is the only case where we import our SVG's from SCSS and it's only necessary in order to override default searchkit styles, I've revised the style so it applies the icon via a data URL instead.

NickAkhmetov/HMP-433 Restore magnifying glass icon to search bars

---

context/app/static/js/components/App.jsx
context/app/static/js/components/cells/DatasetsSelectedByExpression/DatasetsSelectedByExpression.jsx
context/app/static/js/components/detailPage/BulkDataTransfer/GlobusLink.jsx
context/app/static/js/components/detailPage/BulkDataTransfer/usePanelSet.jsx
context/app/static/js/components/detailPage/Citation/Citation.jsx
context/app/static/js/components/detailPage/related-entities/RelatedEntitiesTable/RelatedEntitiesTable.jsx
context/app/static/js/shared-styles/dropdowns/DropdownMenu/DropdownMenu.jsx
context/app/static/js/shared-styles/icons/URLSvgIcon/URLSvgIcon.tsx

This PR makes a few minor adjustments to address React warnings surfaced by React Strict Mode.
Remaining concerns related to dependencies:
- `searchkit` throws warnings due to use of string refs and legacy context API usage
- `vitessce` throws warnings due to a key uniqueness issue in a subcomponent, usage of `findDOMNode` in place of a node ref, and legacy context API usage
- `@hms-dbmi/react-workflow-viz` uses `findDOMNode` as well
I kept StrictMode enabled for now, but it can be toggled back off if requested. It [applies some changes to behavior only](https://react.dev/reference/react/StrictMode) to make it easier to spot bugs during development.

NickAkhmetov/HMP-231 Add React Strict Mode/make adjustments to hide warnings

---

CHANGELOG-fix-nav-link.md
context/app/static/js/components/Header/DropdownLink/DropdownLink.tsx

The previous appearance seems to be maintained. I believe this also resolves HMP-451 which was misdiagnosed.

John conroy/fix nav click HMP-452

---

CHANGELOG-update-release-tag.md
context/app/markdown/CHANGELOG.md
etc/build/push.sh

Adds a check at the start of the push.sh script to check if Docker is running. The push should exit early to avoid the changelog version getting out of sync with the docker tag.
Updates erroneous tag in last CHANGELOG entry.

HMP-475 Fix changelog version and exit build if Docker is not running

---

CHANGELOG-hmp-492.md
context/app/static/js/components/workspaces/api.ts

This PR prevents noisy calls to fetch workspaces/jobs by users without access to the workspaces API.

NickAkhmetov/HMP-492 Prevent unnecessary calls to workspaces API by users without permissions

---

CHANGELOG-HMP-482.md
context/app/static/js/helpers/trackers.js

This PR replaces every space in event category names with underscores by applying a regex to the category before sending it via faro. This is only applied to faro events in order to avoid impacting matomo/GA values.

NickAkhmetov/HMP-482 Remove spaces from tracked event names

---

CHANGELOG-gene-endpoints.md
context/app/static/js/components/genes/hooks.ts

This PR adjusts the gene API endpoints:
- Gene Detail is now coming from `/genes/GENE_IDENTIFIER`
- Gene List is now coming from `/genes-info`

NickAkhmetov/Update UBKG endpoints for gene lookups

---

CHANGELOG-update-hra-api-endpoint.md
context/app/static/js/pages/Iframe/Iframe.jsx
context/app/templates/special-pages/ccf-eui.html

For both EUI and the organ-info web component, we are switching the API endpoint to a hubmap-only version of the HRA-API (formerly known as the CCF-API). It is exactly the same code as in production, but just limited to HuBMAP data.
This has been a request for a while and should provide good performance now. It can be merged at any time.

Updated the HRA API endpoint to point to the HuBMAP-only version

---

CHANGELOG-hmp-496.md
context/app/static/js/components/workspaces/hooks.ts

This PR adjusts the `useRunningWorkspace` functionality to properly identify when there is an activating workspace job in order to prevent users from launching an additional job while one is already starting up.

NickAkhmetov/HMP-496 Prevent launch of additional workspaces while a launch is already in progress

---

CHANGELOG-hmp-457.md
context/app/static/js/components/workspaces/WorkspaceSessionWarning.tsx
context/app/static/js/components/workspaces/hooks.ts
context/app/static/js/pages/Workspace/Workspace.tsx
context/app/static/js/pages/Workspaces/Workspaces.tsx
context/app/static/js/shared-styles/alerts/Alert.tsx

This PR adds an alert to the top of the workspaces list which allows for the renewal of active workspace sessions.
https://github.com/hubmapconsortium/portal-ui/assets/19957804/9f2aa718-3693-4dae-be85-13c96e833998
Ideas for additional improvements:
- Adding a threshold time at which to start displaying that alert; right now, it displays this alert whenever any workspace is active
- Linking to the running workspace's detail page as part of the alert

NickAkhmetov/HMP-457 Add workspace session renewal

---

CHANGELOG-HMP-505.md
context/app/static/js/components/workspaces/api.ts

This PR causes an error page to be displayed when a workspace detail request fails.
Note that a webpack overlay is initially displayed if this error is thrown while in development; this overlay will not appear in production.

NickAkhmetov/HMP-505 Add handling for workspace API 404's

---

CHANGELOG-HMP-501.md
context/app/static/js/components/genes/CellTypes/CellTypes.tsx

This PR adds links from the gene detail page's `cell types` table to the corresponding organ.
During development, I discovered we don't currently handle the edge case where we don't have any available cell types/organs to display and created https://hms-dbmi.atlassian.net/browse/HMP-512 to track this.

NickAkhmetov/HMP-501 Link to organ pages from gene detail page

---

CHANGELOG-fix-workspace-launch-error-message.md
context/app/static/js/components/workspaces/NewWorkspaceDialog/NewWorkspaceDialogFromSelections.tsx

This PR pulls the workspace error message rendering logic outside of the condition that checks whether to display the protected datasets field in order to make other errors appear as expected.

NickAkhmetov/HOTFIX Fix workspace launch error message display logic

---

CHANGELOG-hmp-514.md
context/app/static/js/components/workspaces/WorkspaceSessionWarning.tsx
context/app/static/js/components/workspaces/hooks.ts
context/app/static/js/pages/Workspaces/Workspaces.tsx
context/package.json

This PR adds a link to a workspace's details page from the workspaces list to ease navigation/provide clarity.
Workspace list view:
Workspace detail page view:
I also added an `npm run clean` script to let us clean up the `public` folder generated after build to troubleshoot issues with module updates not working as expected.

NickAkhmetov/HMP-514 Link to workspace details page from session time alert

---

CHANGELOG-matomo-groups.md
context/app/static/js/helpers/trackers.js

This PR fixes tracking for user groups. I consulted the types for the matomo tracker and discovered that when multiple custom dimensions are defined in the instantiation of the tracker, they need to be provided as an array of arrays. The groups are now included as part of the tracking request.

NickAkhmetov/HOTFIX - Fix matomo user group tracking

---

CHANGELOG-workspace-tutorial.md
context/app/routes_main.py
context/app/static/js/components/Routes/Routes.jsx
context/app/static/js/components/workspaces/WorkspacesAuthenticated.jsx
context/app/static/js/pages/Tutorial/Tutorial.tsx
context/app/static/js/pages/Tutorial/index.tsx
context/app/static/js/pages/Tutorials/Tutorials.tsx
context/app/static/js/pages/Tutorials/index.tsx
context/app/static/js/shared-styles/tutorials/Prompt/Prompt.jsx
context/app/static/js/shared-styles/tutorials/Prompt/index.js

We'll need to revisit the styling when there are more tutorials, but this works for now. We should also refactor the tutorial prompt and convert it to ts at a later date.
I imagine we'll want to add the tutorials link to navigation once workspaces is live?

John conroy/workspace tutorial HMP-425

---

CHANGELOG-biomarker-search.md
context/app/static/js/components/biomarkers/hooks.ts

This PR adjusts the biomarkers landing page search functionality so the input is automatically uppercased when sent to the server; this is a workaround for the `genes-info` endpoint currently being case sensitive and only matching against gene symbols.

NickAkhmetov/Hotfix - Uppercase biomarkers search input

---

CHANGELOG-HMP-538.md
end-to-end/cypress/e2e/portal/publication-page.cy.js

This PR reenables Cypress tests which were disabled to account for the sync of PROD and TEST environments.

NickAkhmetov/HMP-538 Restore disabled cypress tests

---

cloudformation-templates/portal-images.yml

Largely adapted from the 'CORS-With-Preflight' policy. Unfortunately you can't combine an existing `CloudFrontResponseHeadersPolicy` with a managed policy of the same type.

Update portal images cloud formation

---

CHANGELOG-HMP-566.md
context/app/static/js/components/Footer/Footer.jsx

This PR:
- Adds an external link icon to the GitHub link
- Makes the portal analytics link available while in maintenance and adds an external link icon
Non-maintenance footer:
Maintenance footer:

NickAkhmetov/HMP-566 Make footer link icons consistent

---

CHANGELOG-fix-matomo-events.md
CHANGELOG-github-action-node-version
context/app/markdown/CHANGELOG.md
context/app/static/js/helpers/trackers.js
context/app/static/js/hooks/useTrackID.ts
context/app/static/js/pages/Collection/Collection.jsx
context/app/static/js/pages/Dataset/Dataset.jsx
context/app/static/js/pages/Donor/Donor.jsx
context/app/static/js/pages/Publication/Publication.jsx
context/app/static/js/pages/Sample/Sample.jsx

- Fix matomo event tracking to provide name field where applicable.
- Track entity page visits by HuBMAP ID not UUID.
I also added tracking for publication pages and cleaned up an old changelog file that wasn't compiled as it was missing a `.md` extension.

John conroy/fix matomo events

---

CHANGELOG-fix-entity-page-tracker.md
context/app/static/js/components/detailPage/summary/SummaryData/SummaryData.jsx
context/app/static/js/components/detailPage/summary/SummaryData/style.js
context/app/static/js/components/detailPage/summary/SummaryJSONButton/SummaryJSONButton.tsx
context/app/static/js/components/detailPage/summary/SummaryJSONButton/index.ts
context/app/static/js/components/detailPage/useTrackEntityPageEvent.ts
context/app/static/js/shared-styles/buttons/TooltipButton/TooltipIconButton.tsx
context/app/static/js/shared-styles/buttons/TooltipButton/index.ts

Fixes `useTrackEntityPageEvent` to handle undefined `entity_type` and `hubmap_id` inside the flask data context. We could consider defining a new field in the flask data for detail pages which would be the `entity_type` for search-api dependent detail pages and manually set for other pages like workspaces.
I also went on a little bit of a tangent to pull the tracker out of `SummaryData`.

John conroy/fix entity page tracker CAT-553

---

CHANGELOG-fix-missing-viz.md
context/app/api/client.py

Fix bug in which new datasets without deprecated `data_types` field were not displaying visualizations correctly.

John conroy/fix missing viz CAT-566

---

CHANGELOG-globus-all-statuses.md
context/app/static/js/components/detailPage/BulkDataTransfer/usePanelSet.jsx

Show Globus link for datasets regardless of their status.
@tsliaw Until now all consortium access datasets showed the now removed 'These data are still being prepared, processed, or curated...' message since they all have a non-published status. This PR makes it so the public message shows for those datasets. Is that ok or do you want a different message?

John conroy/globus all statuses CAT-579

---

CHANGELOG-cat-593.md
context/app/static/js/components/detailPage/ContributorsTable/utils.ts

The `contacts` in data collections do not have a `version` field, while `contributors` do. Since the adapter I had built out for this as part of #3391 assumed that all legacy contacts have a `version` field while all CEDAR contacts have the `metadata_schema_id` field, I had used the presence of the `version` field as the discriminator to determine which adapter function to use. As this assumption has been proven incorrect, I have reversed this logic - if the metadata schema ID field is present, we know it's a CEDAR schema contributor, while if the metadata schema ID is missing, we know it's legacy data.

NickAkhmetov/CAT-593 Support display of legacy contact information without `version` field

---

CHANGELOG-cat-591.md
context/app/static/js/components/searchPage/config.js

This PR adds the missing field that was causing the tile view of search pages to crash if viewing any query but the default.

NickAkhmetov/CAT-591 Fix tile search view

---

CHANGELOG-fix-publication-test.md
end-to-end/cypress/e2e/portal/publication-page.cy.js

The test broke as the data underlying the publication changed. This should be less fragile. We should look into why the data for the publication changed.

John conroy/fix publication test

---

CHANGELOG-pyyaml-cython.md
context/Dockerfile

Use a constraints file to force pip to use cython<3 at build time to address:
"AttributeError: cython_sources" with Cython 3.0.0a10 #601 (comment)
https://stackoverflow.com/questions/77490435/attributeerror-cython-sources 
We may be able to remove this after upgrading to PyYaml 6. 
https://github.com/yaml/pyyaml/issues/724
```
25.60 Collecting pyyaml==5.4
25.61   Downloading PyYAML-5.4.tar.gz (174 kB)
25.62      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 174.8/174.8 kB 25.9 MB/s eta 0:00:00
25.69   Installing build dependencies: started
27.15   Installing build dependencies: finished with status 'done'
27.15   Getting requirements to build wheel: started
27.26   Getting requirements to build wheel: finished with status 'error'
27.27   error: subprocess-exited-with-error
27.27   
27.27   × …
```

Resolve attribute error when installing pyyaml dependency.

---

CHANGELOG-container-arch.md
context/app/markdown/CHANGELOG.md
etc/build/build.sh
etc/dev/docker.sh

Docker will automatically select an image variant which matches your OS and architecture. To instruct docker to pass the --platform flag to build our Docker image for an x86/amd64 platform, we set the environment variable `DOCKER_DEFAULT_PLATFORM` in the build script.

Set platform environment variable.

---

CHANGELOG-hotfix-metadata.md
context/app/static/js/pages/Dataset/Dataset.jsx

This PR is a hotfix which corrects a typo that causes the metadata section to not appear as expected in dataset pages.
This was not caught during development due to the culmination of a few factors:
- both `combineMetadata` and `combinedMetadata` were in the file
- the file was not yet converted to TypeScript, so the type difference was not caught
Due to the time-crunch we were in at the time of the merge (shortly before demo days) we missed this detail during QA as well; I've updated the QA notes to include confirming the metadata section is populated.
Metadata section after applying fix:

NickAkhmetov/HOTFIX - Metadata section typo

---

CHANGELOG-CAT-610.md
context/app/static/js/components/detailPage/multi-assay/MultiAssayProvenance/MultiAssayProvenance.tsx

This PR removes the extra "S" from the multi-assay provenance component.

NickAkhmetov/CAT-610 Remove extra "S" on prov tables

---

CHANGELOG-portal-vis.md
context/requirements.in

This PR updates the portal-visualization version to support the new columns in the 10X multiome datasets.

NickAkhmetov/bump portal-vis to 0.2.2

---

CHANGELOG-vitessce-tracker-fixes.md
context/app/static/js/components/detailPage/visualization/VisualizationThemeSwitch/VisualizationThemeSwitch.jsx
context/app/static/js/components/detailPage/visualization/VisualizationTracker/hooks.ts

This PR:
- Fixes the reporting of theme toggle actions so that selections of `null` theme properly report as the user attempting to select the already-active theme
- Adjusts the reporting of zoom/scroll actions depending on the target Vitessce component.

NickAkhmetov/Visualization tracker fixes (CAT-620 / CAT-644)

---

CHANGELOG-cat-298.md
context/app/default_config.py
context/app/routes_api.py
context/app/routes_main.py
context/app/static/js/components/Contexts.tsx
context/app/static/js/components/Header/UserLinks/UserLinks.jsx
context/app/static/js/components/Routes/Routes.jsx
context/app/static/js/components/detailPage/entityHeader/EntityHeaderContent/EntityHeaderContent.tsx
context/app/static/js/components/detailPage/summary/SummaryTitle/SummaryTitle.tsx
context/app/static/js/components/detailPage/utils.js
context/app/static/js/components/detailPage/utils.ts
context/app/static/js/components/profile/MyLists.tsx
context/app/static/js/components/profile/MyWorkspaces.tsx
context/app/static/js/components/profile/Summary/Description.tsx
context/app/static/js/components/profile/Summary/Groups.tsx
context/app/static/js/components/profile/Summary/Summary.tsx
context/app/static/js/components/profile/Summary/Title.tsx
context/app/static/js/components/profile/Summary/hooks.ts
context/app/static/js/components/profile/Summary/index.ts
context/app/static/js/components/profile/index.ts
context/app/static/js/components/workspaces/workspaceMessaging.tsx
context/app/static/js/pages/Profile/Profile.tsx
context/app/static/js/pages/Profile/index.ts
context/app/static/js/shared-styles/alerts/LoginAlert.tsx
context/app/static/js/shared-styles/icons/entityIconMap.ts
context/app/static/js/shared-styles/icons/icons.ts
context/requirements.in
context/requirements.txt

This PR implements the user profile page.
<details><summary>Logged in HuBMAP user with access to workspaces</summary>
<p>
</p>
</details> 
<details><summary>Logged in HuBMAP user with no access to workspaces</summary>
<p>
</p>
</details> 
<details><summary>Logged in external user</summary>
<p>
</p>
</details>
<details><summary>Unauthenticated user</summary>
<p>
</p>
</details> 
<details><summary>Minor Details</summary>
<p>
I made the buttons more "call to action"-y if there are no existing lists or workspaces. 
If no lists are available:
If no workspaces have been created but user has access to workspaces:
</p>
</details>

NickAkhmetov/CAT-298 Implement profile page

---

CHANGELOG-cat-643.md
context/requirements.in
context/requirements.txt

This PR bumps portal-visualization to 0.2.4 to pull in the changes in https://github.com/hubmapconsortium/portal-visualization/pull/89.

NickAkhmetov/CAT-643 Bump portal-visualization

---

CHANGELOG-cat-641.md
context/app/api/client.py

This PR fixes visualizations appearing on primary datasets with image descendants. Instead of only checking for `is_support` or `is_image`, image pyramid cases need to check for the presence of both hints (which is also why we can't use a `terms`	condition here, since that returns if any of the matched terms are met).
AF Dataset:
CODEX (non-processed) dataset:
CODEX (processed) dataset:

NickAkhmetov/CAT-641 Fix unexpected visualizations on unprocessed datasets

---

CHANGELOG-cat-698.md
context/app/static/js/components/profile/Summary/hooks.ts

This PR removes the `other groups` section of the profile page:

NickAkhmetov/CAT-698 Remove "other groups" from profile pages

---

CHANGELOG-cat-704.md
context/app/static/js/pages/Diversity/DonorChart.jsx

This PR restores the legends to the diversity charts by providing the `Legend` plugin to the bar chart component.

NickAkhmetov/CAT-704 Restore donor diversity chart legends

---

CHANGELOG-cat-712.md
context/app/static/js/components/home/Hero/Hero.tsx

This PR fixes the "explore datasets" link on the updated homepage to direct to the dataset search page; it was previously an "explore organs" link until a last minute change, so the URL got missed.

NickAkhmetov/CAT-712 Fix "explore datasets" link

---

CHANGELOG-nav-qa.md
context/app/static/js/components/Header/HeaderButton/HeaderButton.tsx
context/app/static/js/components/Header/HeaderButton/styles.ts
context/app/static/js/components/Header/HeaderNavigationDrawer/HeaderNavigationDrawer.tsx
context/app/static/js/components/Header/HeaderNavigationDrawer/instances.tsx
context/app/static/js/components/Header/UserIcon/UserIcon.tsx
context/app/static/js/components/Header/UserIcon/index.ts
context/app/static/js/components/Header/staticLinks/staticLinks.tsx
context/app/static/js/shared-styles/Drawer/DrawerItem.tsx
context/app/static/js/shared-styles/Drawer/NavigationDrawer.tsx
context/app/static/js/shared-styles/Drawer/styles.tsx

- Fixed technical documentation description
- decreased spacing between header icons and text from 8px to 4px
- decreased navigation drawer gap between components
- made icons swap to "close" buttons when drawer is expanded, prevented drawer from covering header on mobile, and updated profile drawer options/button icon:

NickAkhmetov/Navigation QA fixes

---

CHANGELOG-s3-urls.md
context/app/preview/3d-tissue-maps.md
context/app/preview/cell-type-annotations.md
context/app/preview/multimodal-molecular-imaging-data.md

With migration of Vitessce-related AWS resources to the DBMI Landing Zone, I have also moved the data in the vitessce-data S3 buckets behind CloudFront distributions, located at subdomains of `vitessce.io`. This will provide our team with full control over these URLs moving forward instead of being locked into S3 bucket naming and other restrictions.
Fixes #3483 
Describe how the feature has been tested, including both automated and manual testing strategies.

Update vitessce-data s3 bucket urls in preview configs

---

CHANGELOG-fix-prov-overflow.md
context/app/static/js/components/detailPage/multi-assay/MultiAssayProvenance/MultiAssayProvenance.tsx

This PR adds flex wrapping to multi-assay provenance tile sections. This prevents overflow when there are more than three tiles.
https://hms-dbmi.atlassian.net/browse/CAT-836
I checked the datasets linked in the original ticket; verification screenshots are included below.

NickAkhmetov/CAT-836 Fix multi-assay provenance overflow 

---

CHANGELOG-push-script-cat-842.md
etc/build/push.sh

This PR updates the `push.sh` script to allow making major version bumps.
Major version bumps are opted into by including a second param while calling the script (e.g. `./etc/build/push.sh major`). Otherwise, the previous behavior is used.
In order to account for the major version no longer being a constant 0, I had to adjust the logic for whether a patch or minor version release is made. Rather than calculating the new version tag based on a starting date in 2021, the updated logic compares the date of the last minor or major version to the current date to determine whether to make a minor or patch version bump.
https://hms-dbmi.atlassian.net/browse/CAT-842
Manually tested by adding a `die` statement after the version tag was printed and attempting both major and minor version bumps. …

NickAkhmetov/CAT-842 Update push script to handle major version bumps

---

CHANGELOG-homepage-text-updates.md
context/app/static/js/components/Header/staticLinks/staticLinks.tsx
context/app/static/js/components/home/ExternalLinks/ExternalLinks.tsx
context/app/static/js/components/home/Hero/const.tsx

This PR adjusts language related to the HRA/ASCT+B Reporter/EUI and updates the link for the 10X/Visium news item to point to those assays on the search page specifically.
[CAT-787](https://hms-dbmi.atlassian.net/browse/CAT-787)
[CAT-856](https://hms-dbmi.atlassian.net/browse/CAT-856)
Manually tested by updating text and verifying changes persisted.
https://github.com/user-attachments/assets/8b417cfb-3530-4f8c-b447-30bf684b8a54
[CAT-787]: https://hms-dbmi.atlassian.net/browse/CAT-787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CAT-856]: https://hms-dbmi.atlassian.net/browse/CAT-856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU …

NickAkhmetov/Homepage text adjustments (CAT-856, CAT-787)

---

CHANGELOG-cat-844.md
context/app/routes_browse.py
context/app/static/js/components/detailPage/provenance/ProvTable/ProvTable.tsx
context/app/static/js/components/detailPage/provenance/ProvTableTile/ProvTableTile.tsx
context/app/static/js/components/detailPage/provenance/queries.ts
context/app/static/js/components/entity-tile/EntityTile/EntityTile.tsx
context/app/static/js/components/types.ts
context/app/static/js/hooks/useEntityData.ts
context/app/static/js/pages/search/DevSearch.jsx

This PR removes the portal UI's dependencies on the direct ancestor/descendant information available in the entity API in favor of using the corresponding `ids`.
- `ancestors`
- `descendants`
- Not in use.
- `immediate_ancestors`
- Mentioned in an artillery config, but otherwise not present.
- `immediate_descendants`
- ~~`useImmediateDescendantProv` is used for the `view derived entities` button~~ This actually uses the entity API endpoint; this can be improved to use the search API equivalent once the upstream change is made to the search API, but is not currently a blocker.
https://hms-dbmi.atlassian.net/browse/CAT-844
Manually verified, confirmed functionality is analogous to current production behaviors.
Not very informative since this matches existing functionality, but for …

NickAkhmetov/CAT-844 Migrate away from using `descendants` and `ancestors` in favor of `id` equivalents

---

CHANGELOG-workspaces-user-group.md
context/app/routes_auth.py
context/app/static/js/components/App.jsx

Enables members of either the workspaces or hubmap globus groups to access workspace features. Confirmed with Zhou that the 'WORKSPACES_GROUP_ID' is still configured.
I opened a workspace.

John conroy/workspaces user group CAT-865

---

CHANGELOG-handle-creators-or-contributors-collections.md
context/app/static/js/pages/Collection/Collection.jsx

Zhou asked that we handle both `contributors` and `creators` until they can rename `creators` to `contributors`.

John conroy/handle creators or contributors collections

---

CHANGELOG-fix-303-redirect.md
context/app/static/js/components/publications/PublicationsDataSection/PublicationsDataSection.jsx
context/app/static/js/helpers/swr/fetchers.ts
context/app/static/js/hooks/useSearchData.ts

Fixes regression to 303 redirect to s3 handling introduced in fetcher refactoring. I also introduced `_source` to the publication collections query to avoid the 303.

John conroy/fix 303 redirect CAT-874

---

CHANGELOG-cat-875.md
context/app/static/js/components/detailPage/ProcessedData/ProcessedDataset/ProcessedDatasetAccordion.tsx

This PR adjusts processed dataset accordions' icons to improve visibility when the accordion is collapsed.
https://hms-dbmi.atlassian.net/issues/CAT-875
Manually tested.
Expanded Published:
Collapsed Published:
Collapsed Error:
Collapsed QA:

NickAkhmetov/CAT-875 Improve status icon visibility for collapsed processed dataset accordions

---

CHANGELOG-cat-876.md
context/app/static/js/components/detailPage/DatasetRelationships/nodeTypes.tsx
context/app/static/js/components/detailPage/ProcessedData/ProcessedDataset/ProcessedDatasetAccordion.tsx
context/app/static/js/components/detailPage/ProcessedData/ProcessedDataset/ProcessedDatasetContext.tsx
context/app/static/js/hooks/useHash.ts
context/app/static/js/pages/Dataset/utils.ts

This PR adds an explanatory toast/tooltip to dataset relationship nodes and makes dataset sections expand when navigated to via table of contents or the dataset relationship nodes.
Some caveats/limitations I've attempted to address but could not find a satisfactory solution for:
- If the user navigates to a processed dataset via a hash to expand it, manually collapses it, then scrolls back up to the dataset relationships and clicks the link again, the accordion will not expand as a hashchange event does not fire in this circumstance. Forcing an update in the `useHash` function doesn't help.
- Since the vitessce instance in the accordion mounts when the accordion expands, the initial scroll can be laggy as a result. Keeping the Vitessce instances always mounted by disabling the …

NickAkhmetov/CAT-876 Scrolling improvements, expand collapsed datasets on hash navigation

---

CHANGELOG-cat-880.md
context/app/static/js/components/detailPage/files/DataProducts/DataProducts.spec.tsx
context/app/static/js/components/detailPage/files/DataProducts/hooks.ts
context/app/static/js/components/detailPage/files/FileBrowser/FileBrowser.spec.tsx
context/app/static/js/components/detailPage/files/FileBrowserFile/FileBrowserFile.spec.tsx
context/app/static/js/components/detailPage/files/FileBrowserNode/FileBrowserNode.spec.tsx
context/app/static/js/components/detailPage/files/Files/Files.spec.tsx
context/app/static/js/pages/Dataset/Dataset.tsx

This PR adjusts the data products and files components to use the proper dataset UUID when building their links. As part of this change, I needed to add relevant wrappers to all the specs.
I also removed the top level `data products` component as there are no data products on primary datasets, i.e. they are only present on processed datasets.
https://hms-dbmi.atlassian.net/browse/CAT-880
Manually tested several datasets' downloads, adjusted unit tests to pass.
Primary dataset UUID: 8afd1dccac093106c08c76209dde02d6
Download link includes processed dataset UUID:

NickAkhmetov/CAT-880 Ensure data product and file URLs use relevant dateset UUID

---

CHANGELOG-cat-879.md
context/app/static/js/components/detailPage/DatasetRelationships/nodeTypes.tsx

This PR corrects an issue introduced in #3530; attempting to access the `pipeline` of a dataset which had not finished loading led to this regression.
https://hms-dbmi.atlassian.net/browse/CAT-879
Manually tested with the dataset that was crashing on stage.

NickAkhmetov/CAT-879 Improve handling of loading/potentially undefined data in dataset relationship diagram

---

CHANGELOG-cat-858.md
context/app/static/js/components/detailPage/provenance/NodeElement/NodeElement.tsx
context/app/static/js/components/detailPage/provenance/ProvGraph/ProvGraph.spec.js

This PR hides the internal ID that was being displayed as part of the provenance graph for `step` nodes, as these are not accessible/meaningful in any way and only introduce confusion.
https://hms-dbmi.atlassian.net/browse/CAT-858
Manually tested on same dataset linked in original ticket.

NickAkhmetov/CAT-858 Hide HuBMAP ID's for non-entity nodes in provenance graph

---

CHANGELOG-new-ws-envs.md
context/app/static/js/components/workspaces/LaunchWorkspaceDialog/LaunchWorkspaceDialog.tsx
context/app/static/js/components/workspaces/NewWorkspaceDialog/NewWorkspaceDialog.tsx
context/app/static/js/components/workspaces/WorkspaceEnvironmentDescription/WorkspaceEnvironmentDescription.tsx
context/app/static/js/components/workspaces/WorkspaceEnvironmentDescription/index.ts
context/app/static/js/components/workspaces/WorkspaceJobTypeField/WorkspaceJobTypeField.tsx
context/app/static/js/components/workspaces/constants.ts
context/app/static/js/shared-styles/text/HighEmphasis.tsx

Add language to workspace environment sections to help users distinguish between environments.
- [Ticket](https://hms-dbmi.atlassian.net/browse/CAT-902)
- [Figma](https://www.figma.com/design/NgBjvs0jRbDHhiyn5nicDm/Workspace?node-id=3235-2490&node-type=canvas&m=dev)
New Workspace
Launch Workspace
Tooltips

John conroy/new ws envs CAT-902

---

CHANGELOG-last-minute-workspace-updates.md
context/app/static/js/components/workspaces/constants.ts
context/app/static/js/components/workspaces/types.ts
context/app/static/js/pages/Template/Template.tsx

- Increase maximum resource options for workspace jobs from 2 CPUs to 16, 32GB of memory to 128GB and session length from 6 hours to 12.
- Add last modified date to template detail pages.

John conroy/last minute workspace updates

---

CHANGELOG-fix-template-resource.md
context/app/static/js/components/workspaces/NewWorkspaceDialog/useCreateWorkspaceForm.ts
context/app/static/js/components/workspaces/types.ts

Fix bug where template examples with default resource options would not launch.

John conroy/fix template resource

---

CHANGELOG-cat-881.md
context/app/static/js/pages/Dataset/utils.spec.ts
context/app/static/js/pages/Dataset/utils.ts

This PR adds logic to prevent duplicate URL anchors on unified dataset pages that have multiple errored runs, such as https://portal.hubmapconsortium.org/browse/dataset/9e9085a732ae35d4a46b68d86167f475?redirected=True#summary-salmon%2barchr%2bmuon-error
Error datasets are the only duplicate state we've observed so far in the system, but I have implemented this such that we can extend this logic at will in the future.
https://hms-dbmi.atlassian.net/browse/CAT-881
Unit tests have been added for the related utility function, including a case specifically covering duplicate dataset statuses.
Sample URL after changes:

NickAkhmetov/CAT-881 deduplicate errored processed datasets' urls

---

CHANGELOG-cat-896.md
etc/build/push.sh

After the revisions in #3510 and #3516, subsequent releases have not followed the logic of only incrementing the patch version if it has been less than two weeks since the last minor version.
Upon revisiting, this appears to be due to the logic checking for the last release with a 0 major version. This approach worked during development, since I was testing it with a `0.` major version, but broke immediately following the first major version. I have adjusted the logic to check for the last minor version with any major version.
https://hms-dbmi.atlassian.net/browse/CAT-896
Local testing with dry-runs of the push script, with the `git` pieces commented out to test the date logic.
Before the change:
After the change:
Potential future improvements:
- An explicit `--dry-run` option could be …

NickAkhmetov/CAT-896 Fix push script logic

---

CHANGELOG-cat-751.md
context/app/static/js/components/detailPage/provenance/ProvGraph/ProvGraphErrorBoundary.tsx
context/app/static/js/components/detailPage/provenance/ProvSection/ProvSection.tsx
context/app/static/js/components/detailPage/provenance/ProvTabs/ProvTabs.tsx

This donor's provenance data is incomplete (it is missing the edges that connect activities to their parent entities): https://portal.hubmapconsortium.org/browse/donor/a0bdb4249eb3a6bd1865f948875c2f96
Removing the `required` status from that key does not resolve the issue, since these edges are mandatory to be able to draw the graph.
I have escalated the underlying data issue to Zhou in a private message; in the meantime, we can improve the way this error is handled on the front-end by preventing the triggering of the full-page error boundary and interrupting the user's browsing session. 
I used the same `DetailsAccordion` component we use to report Vitessce visualization errors to be consistent.
https://hms-dbmi.atlassian.net/browse/CAT-751
The problematic donor page has been visited …

NickAkhmetov/CAT-751 Prevent full-page errors from malformed provenance data

---

CHANGELOG-cat-435.md
context/app/static/js/components/detailPage/visualization/VisualizationTracker/hooks.ts

This PR adjusts the Visualization Tracker to prevent default behaviors for arrow key events when the user has the vitessce visualization focused. This keeps the visualization in place while the user adjusts e.g. the position of a scatterplot or spatial view.
https://hms-dbmi.atlassian.net/browse/CAT-435
Manually tested; see video below.
In this video, I switch between the same dataset on production and on my local environment to compare the behaviors before and after these changes.
https://github.com/user-attachments/assets/2a0d0958-aefe-4342-876a-a0a5c97931ed

NickAkhmetov/CAT-435 disable scrolling full page when using arrow keys to explore Vitessce visualizations

---

CHANGELOG-update-hive-group.md
context/app/static/js/components/detailPage/MetadataTable/MetadataTable.tsx
context/app/static/js/components/detailPage/ProcessedData/ProcessedDataset/ProcessedDataset.tsx
context/app/static/js/components/detailPage/entityHeader/EntityHeaderContent/EntityHeaderContent.tsx
context/app/static/js/components/entity-tile/EntityTileBody/EntityTileBody.tsx
context/app/static/js/components/searchPage/ResultsTable/utils.jsx
context/app/static/js/shared-styles/tooltips/DonorAgeTooltip/DonorAgeTooltip.tsx
context/app/static/js/shared-styles/tooltips/InfoTextTooltip/InfoTextTooltip.tsx
context/app/static/js/shared-styles/tooltips/InfoTextTooltip/index.ts
context/app/static/js/shared-styles/tooltips/InfoTextTooltip/style.ts

Update group for HIVE-processed datasets to be 'HIVE' with an explanatory tooltip. Refactoring was also done to tooltips for donor age messaging, as the style for both can be shared.
[CAT-941 Jira ticket ](https://hms-dbmi.atlassian.net/browse/CAT-941?atlOrigin=eyJpIjoiMjEwYWVhYzc4ODU5NGY4ZWEzMGViMzllM2I0OGY3MmQiLCJwIjoiaiJ9)
Manually checked group names for central and lab-processed dataset detail pages. 
<details>
<summary>Updated group names</summary>
Central processed:
Lab processed:
</details>
<details>
<summary>Refactored age tooltips</summary>
Entity header:
Entity tile:
Metadata table:
Search page:
</details>

Austenem/CAT-941 Update HIVE group

---

CHANGELOG-cat-419.md
context/app/static/js/components/home/EntityCounts/hooks.ts

This PR adds a query to the aggregation on the homepage which prevents collection entities without a registered/published DOI from being included in the counts while not impacting the other counts. This filtering behavior matches the conditions applied to the count and list on the collections page.
https://hms-dbmi.atlassian.net/browse/CAT-419
Manual testing/comparison to the logged in portal.
Hovering the samples count to verify the added query does not affect any of the other entity counts; the actual fix can be seen by checking the collections count on the right.
Logged in on prod:
Logged in locally:
Not sure how else to test this functionality; the idea of using an e2e test to compare the counts came to mind, but since this issue was only observable while logged in as a HIVE user, …

NickAkhmetov/CAT-419 Filter collections without DOI from being counted on homepage

---

CHANGELOG-cat-882.md
context/app/static/js/components/detailPage/entityHeader/EntityHeader/EntityHeader.tsx

This PR adjusts the entity header to automatically respond to screen size changes.
- On change from large screen to small screen, the entity header is set to the narrow view.
- On change from small screen to large screen, the entity header is restored to its previous view.
https://hms-dbmi.atlassian.net/browse/CAT-882
Manually tested via screen resizing.
https://github.com/user-attachments/assets/b8a1e241-12fa-4552-912e-d09ea8fa368c

NickAkhmetov/CAT-882 Improve entity header resize handling

---

CHANGELOG-remove-qa-workspace-option.md
context/app/static/js/components/detailPage/visualization/Visualization/Visualization.tsx
context/app/static/js/components/detailPage/visualization/VisualizationWorkspaceButton/VisualizationWorkspaceButton.tsx
context/app/static/js/components/detailPage/visualization/VisualizationWrapper/VisualizationWrapper.tsx

Fixes issue of Workspaces button being available for protected datasets in the Visualization section.
[CAT-922 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-922?atlOrigin=eyJpIjoiZmY4M2YyYjViODUzNGU1M2E5YzYwMWU0ZmE3NjI2ZjEiLCJwIjoiaiJ9)
Tested protected and public datasets to ensure Workspaces button appeared only for visualizations of public + published datasets.
Local on left, prod on right:

Austenem/CAT-922 Remove QA workspace option

---

CHANGELOG-cat-706.md
context/app/markdown/CHANGELOG.md
etc/build/push.sh

This PR leverages the existing markdown page logic to add a title to changelog markdown pages.
The markdown page logic looks for the first top-level header to use as the title; since the changelog did not include such a header, it was assigned the default `(no title)` title.
My change appends a `# Changelog` to the start of generated changelogs in the `push` script, then skips the first line of the old changelog during appending. This approach prevents duplicate `# Changelog` entries from appearing.
https://hms-dbmi.atlassian.net/browse/CAT-706
Manually tested by commenting out all git/docker-based functionalities and running the push script.

NickAkhmetov/CAT-706 Add title to changelog page

---

CHANGELOG-fix-header-bug.md
context/app/static/js/components/Header/Header/Header.tsx
context/app/static/js/components/detailPage/DetailPageSection/DetailPageSection.tsx

Fixes a bug resulting from #3569 that caused the entity header to cut off the top of the page. This was addressed by taking a different approach to fixing the entity header bug that was resolved in #3569, which resolved both issues. 
**Original bug:** header shifted off-screen on initial page load on narrow browser window sizes.
**New bug:** header cut off the top of the page (due to being removed from the document flow). 
[CAT-955 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-955?atlOrigin=eyJpIjoiZTFlNmZkNjAzYTM5NDBiNGFlY2E0NmVhNGZmMjExYWMiLCJwIjoiaiJ9)
Tested that both bugs were resolved in Chrome and Safari.
<details>
<summary>Original bug on prod:</summary>
https://github.com/user-attachments/assets/0043111f-d370-41ad-8b1e-3c99c8344c24
</details>
<details>
<summary>Resolved …

Austenem/CAT-955 Fix header bug

---

CHANGELOG-update-hra.md
context/app/static/js/components/HRA/CCFOrganInfo.tsx
context/app/static/js/pages/Iframe/Iframe.jsx
context/app/templates/special-pages/ccf-eui.html
context/app/templates/special-pages/organ.html

Updated both the EUI and organ-info web components. I'm not able to test this locally. It should work fine, but please give it a local test.

Updated HRA EUI and organ-info web components to latest version

---

CHANGELOG-fix-shaking-viewport.md
context/app/static/js/components/detailPage/ProcessedData/ProcessedDataset/ProcessedDatasetAccordion.tsx

Fixes bug where scrolling to the top of a processed dataset section led to a shaking viewport.
**Explanation:** The processed dataset helper panel appears when any part of the processed dataset accordion is visible. In narrower browser windows, opening the helper panel means there is less width for the accordion, so it is moved further down the page. The panel then closes, which causes the accordion to be visible, which opens it again and triggers an infinite loop.
This was resolved by only showing the helper panel when 10% or more of the accordion is visible, and only hiding the panel when the accordion is completely off-screen.
[CAT-957 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-954?atlOrigin=eyJpIjoiYWQ2NTkzNGI2MzVkNGJjYWE4MGM0MDBkZWE4MTg1ZWQiLCJwIjoiaiJ9)
Attempted to …

Austenem/CAT-957 Fix shaking viewport

---

CHANGELOG-show-panel-title-on-hover.md
context/app/static/js/components/detailPage/ProcessedData/HelperPanel/HelperPanel.tsx
context/app/static/js/components/detailPage/summary/SummaryBody/SummaryDescription.tsx
context/app/static/js/shared-styles/text/LineClampWithTooltip.tsx
context/app/static/js/shared-styles/text/index.ts

If a title or description in a processed dataset helper panel is truncated, show the full text on hover in a tooltip.
[CAT-962 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-962?atlOrigin=eyJpIjoiN2U3Y2RlYzI3MWFlNDE0YThlMmE3YzViYTQxMmVlODkiLCJwIjoiaiJ9)
Tested by checking both truncated and non-truncated panel text examples.

Austenem/CAT-962 Show panel title on hover

---

CHANGELOG-update-external-processing-labels.md
context/app/static/js/components/detailPage/DatasetRelationships/hooks.ts
context/app/static/js/hooks/useSoftAssay.tsx

Displays EPIC datasets as being generated via external processing in dataset relationship diagrams. Previously, segmentation mask datasets were being shown as being generated via "Image Pyramid" processing due to their `vitessce-hints`.
[CAT-964 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-964?atlOrigin=eyJpIjoiMGUzNzE0MjNhOGUwNDIwMGEyY2E4MmY0ZGU4MGQ2ZDIiLCJwIjoiaiJ9)
Verified using a segmentation mask EPIC on dev: https://portal.dev.hubmapconsortium.org/browse/dataset/22901da5f080b219a514e38381acbb0e
Dev:
Local:

Austenem/CAT-964 Update external processing labels

---

CHANGELOG-minor-group-updates.md
context/app/static/js/components/detailPage/ProcessedData/HelperPanel/HelperPanel.tsx
context/app/static/js/components/detailPage/ProcessedData/ProcessedDataset/ProcessedDataset.tsx
context/app/static/js/components/detailPage/ProcessedData/ProcessedDatasetGroup.tsx
context/app/static/js/components/detailPage/summary/SummaryBody/SummaryBody.tsx
context/app/static/js/components/publications/PublicationCollections/PublicationCollections.tsx

Several minor updates mainly related to groups on the dataset detail pages:
- Fix typo in publication collections summary (CAT-795)
- Label centrally processed dataset groups as HIVE in the helper panel (CAT-972)
- Add group name to raw dataset summary section (CAT-982)
[CAT-795 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-795?atlOrigin=eyJpIjoiNmI0ZWJlYTkyZjE1NDY5ZjliNzEzYTI4M2YzY2FjNGMiLCJwIjoiaiJ9)
[CAT-972 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-972?atlOrigin=eyJpIjoiZWNjODg3OTNkM2YzNDQ0Njk2ZTFkYjFkYmY1NTdmZjMiLCJwIjoiaiJ9)
[CAT-982 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-982?atlOrigin=eyJpIjoiNjMyMjBjNzRlMWVhNGIyYWI1ZTc5N2QxNzE3MDViZGIiLCJwIjoiaiJ9)
Tested by manually checking detail pages for updates.
<details>
<summary>CAT-795</summary> …

Austenem/Minor group updates (CAT-795, CAT-972, & CAT-982)

---

CHANGELOG-cat-974.md
context/app/static/js/pages/Dataset/hooks.ts

This PR fixes an issue introduced in #3570. Since the parent UUID was being added as a property on the array object, `Array.isArray` was no longer picking up the resulting object as an array. This PR adjusts the approach so that the parent UUID is properly passed down to the configs themselves.
https://hms-dbmi.atlassian.net/browse/CAT-974
Manually tested.

NickAkhmetov/CAT-974 Fix parent UUID handling for multi-vitessce conf datasets

---

CHANGELOG-cat-990-fix-prov-viewport.md
context/app/static/js/components/detailPage/provenance/ProvGraph/style.ts

This PR fixes a regression which caused the provenance graph not to be constrained to 500px tall max. This appears to be due to the migration from styled-components 5 to 6 that occurred as part of the unified views work.
https://hms-dbmi.atlassian.net/browse/CAT-990
Loaded http://localhost:5001/browse/publication/e8338966c69e759157d6c6ad24847989, provenance graph did not massively grow the page.

NickAkhmetov/CAT-990 Fix ProvGraph Viewport

---

CHANGELOG-cat-977.md
context/app/static/js/components/detailPage/Citation/Citation.tsx
context/app/static/js/components/detailPage/summary/SummaryBody/SummaryBody.tsx
context/app/static/js/pages/Collection/Collection.tsx

This PR adjusts the collection page DOI links to copy on click instead of opening a new tab to the same page and removes the duplicated DOI link at the top of the page. Future self-referential DOI's can also be marked with an `internalDOI` prop.
https://hms-dbmi.atlassian.net/browse/CAT-977
Manually tested with the collection page linked in the ticket.
Before:
After:
Copy toast:

NickAkhmetov/CAT-977 Revise Collection DOI links to copy on click

---

CHANGELOG-cat-961.md
context/app/static/js/components/Footer/style.ts

This PR introduces an 8-px gap between footer columns to improve readability/ensure that column text doesn't touch.
https://hms-dbmi.atlassian.net/browse/CAT-961
I initially tried a 4px gap, but this did not provide enough space (the columns were still very close together). After bumping the spacing up to 8px, I confirmed it looks okay at all breakpoints.
Mobile (385px):
Tablet (768px):
Desktop:

NickAkhmetov/CAT-961 Increase spacing between footer columns

---

CHANGELOG-cat-985-remove-publication-workspace-button.md
context/app/static/js/components/detailPage/entityHeader/EntityHeaderActionButtons/EntityHeaderActionButtons.tsx

Removes nonfunctional workspace menu button from publication pages.
[CAT-985 Jira ticket ](https://hms-dbmi.atlassian.net/browse/CAT-985?atlOrigin=eyJpIjoiMzU3MDc3NGI5NjJkNGI2YTgzMmZkZTFmOWM4MmUwN2EiLCJwIjoiaiJ9)
Manually checked for logged-in and logged-out publication pages.
Local:
Prod:

Austenem/CAT-985 Remove publication workspace button

---

CHANGELOG-cat-661.md
context/app/static/js/components/detailPage/files/PDFViewer/PDFViewer.tsx
context/app/static/js/components/detailPage/files/PDFViewer/style.ts

This PR fixes the "View PDF" button disappearing while the PDF is processing. It also fixes the styles for the PDF modal's "close" button, which had a typo that caused the background of the close button to show up without a border radius.
https://hms-dbmi.atlassian.net/browse/CAT-661
Tested manually with datasets linked in original ticket.
View button doesn't disappear while loading anymore:
https://github.com/user-attachments/assets/63bae256-bdf2-4c55-be4c-a274496c21d7
Close button has appropriate styles:

NickAkhmetov/CAT-661 Fix View PDF button disappearance

---

CHANGELOG-cat-969.md
context/app/static/js/components/home/EntityCounts/hooks.ts

This PR:
- Excludes datasets in a non-QA/Published state from being counted on the homepage.
- Excludes samples/donors without a descendant dataset from being counted on the homepage.
https://hms-dbmi.atlassian.net/browse/CAT-969
I tested by comparing homepage counts while logged in on local and production environments, and confirming that the dataset total count matches a manually calculated count from the search page.
Localhost counts:
Prod counts:
There is a related ticket to exclude these samples/donors from the search page results (https://hms-dbmi.atlassian.net/browse/CAT-968); I did not include that change in this PR because of the pending searchkit changes, but these changes should probably be deployed in tandem to minimize confusion from the donor/sample count mismatches.

NickAkhmetov/CAT-969 Increase homepage counts query specificity

---

context/app/static/js/components/search/Facets/TermFacet.tsx

Dedupes hierarchical facet items where the parent only has a single child which matches the parent.

Dedupe single valued hierarchical parents/children

---

CHANGELOG-cat-976.md
context/app/static/js/pages/Dataset/hooks.ts

This PR adjusts the logic for whether or not to display the `visualization` link in the table of contents.
The current logic just checks whether there is a loaded conf in the SWR cache; this approach works well for fast-running configs (such as self-contained processed datasets) but runs into issues with configs that are slower to build (such as image pyramids with multiple slides or other multi-conf cases like 10X).
The updated approach adds a heuristic condition to check whether the dataset is an image pyramid; since image pyramids always have visualizations, this is a safe assumption to make.
https://hms-dbmi.atlassian.net/browse/CAT-976
Tested with image pyramid datasets and 10X datasets to confirm the visualization link shows up when expected. Tested with non-image pyramid processed …

NickAkhmetov/CAT-976 Visualization link in table of contents

---

CHANGELOG-update-portal-viz.md
context/requirements.in
context/requirements.txt

This PR updates the portal-viz hash to reflect the changes in view width for the EPIC segmentation masks
[CAT-673](https://hms-dbmi.atlassian.net/browse/CAT-673)
Manually tested
[CAT-673]: https://hms-dbmi.atlassian.net/browse/CAT-673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Updated portal-viz hash

---

context/app/static/js/components/search/store.ts
context/app/static/js/components/search/utils.ts
context/app/static/js/pages/search/S.tsx

Sorts by `publication_date` to put published data at the top, then by `mapped_status`.

John conroy/sort by pub CAT-970

---

CHANGELOG-add-spacing.md
context/app/static/js/pages/Dataset/Dataset.tsx

Fixes spacing between organ icon and name on detail pages.
[CAT-1021 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-1021?atlOrigin=eyJpIjoiYTg4ZDZmZmJiZTc2NDA5ZWExNzI1MTIzMTUyYjVjMTIiLCJwIjoiaiJ9)
Checked relevant detail pages.
Local:
Prod:

Austenem/CAT-1021 Add spacing

---

CHANGELOG-improve-scroll-tracking.md
context/app/static/js/shared-styles/sections/TableOfContents/TableOfContents.tsx
context/app/static/js/shared-styles/sections/TableOfContents/hooks.ts
context/app/static/js/shared-styles/sections/TableOfContents/utils.ts

Fixes scroll tracking on detail page table of contents so that processed dataset subsections are properly selected. Also adjusts scroll tracking to track the element closest to the middle of the page rather than the element at the top of the page.
[CAT-1020 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-1020?atlOrigin=eyJpIjoiNWI5OGUzMmI0YzY5NGVmOGI2MWZjMGY2YTRjZjhhMDciLCJwIjoiaiJ9)
Tested examples of entity detail pages with and without processed dataset sections.
Local:
https://github.com/user-attachments/assets/553db1af-055c-425e-aab9-75f3d0c4f719
Prod:
https://github.com/user-attachments/assets/3e1f8614-ca1b-4c58-a55c-9a8abf4545dc

Austenem/CAT-1020 Improve scroll tracking

---

CHANGELOG-entity-header-alignment.md
context/app/static/js/components/Routes/Route/Route.tsx
context/app/static/js/components/detailPage/ProcessedData/HelperPanel/HelperPanel.tsx

Ensures that helper menu/table of contents only appear when the browser is wide enough to show both fully, preventing the header and menu from being cut off.
[CAT-1022 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-1022?atlOrigin=eyJpIjoiZjA2NTExYTRkZDc5NDlhYmE0YTE4NzllMjg4NjE3ZmMiLCJwIjoiaiJ9)
Local:
https://github.com/user-attachments/assets/ffadf0bd-f35a-460e-a574-89dbe2f39dba
Prod:
https://github.com/user-attachments/assets/067f0941-afdc-484d-a9e2-c278a8b6f689

Austenem/CAT-1022 Entity header alignment

---

CHANGELOG-search-qa-fixes.md
context/app/static/js/components/search/Facets/DateRangeFacet.tsx
context/app/static/js/components/search/Facets/FilterChips.tsx
context/app/static/js/components/search/Results/ResultsTiles.tsx
context/app/static/js/components/search/Search.tsx
context/app/static/js/components/search/SearchNote.tsx
context/app/static/js/components/search/store.ts
context/app/static/js/components/search/utils.ts
context/app/static/js/pages/search/S.tsx

Applies QA fixes for the search page. @NickAkhmetov I'm just waiting to hear back from Tiffany regarding the calendar font colors.

John conroy/search qa fixes CAT-1040 CAT-1041 CAT-1042 CAT-1043 CAT-1038 CAT-1039

---

CHANGELOG-switch-pipeline-to-search.md
context/app/static/js/components/detailPage/DatasetRelationships/hooks.ts

- Get dataset pipeline info from search-api not the soft assay endpoint.

John conroy/switch pipeline to search CAT-1054

---

CHANGELOG-fix-date-facet-typing.md
context/app/static/js/components/search/Facets/DateRangeFacet.tsx

- Makes the date facet text field read only.
- Changes date facet's icon button color.
Making the text field read only is the simplest fix for now, but we can revisit in the future.

John conroy/fix date facet typing CAT-1045

---

CHANGELOG-search-last-page.md
context/app/static/js/components/search/utils.ts

Phil noticed a bug scrolling through deeper search pages. The `sort_after` requires a unique tiebreaker.
From Phil:
> The "see more results" stops working before it gets to the very end of the list of datasets (see snapshot where it stopped revealing more datasets)

John conroy/search last page

---

CHANGELOG-hotfix-portal-vis.md
context/requirements.in
context/requirements.txt

THis PR bumps the version of `portal-visualization` to pull in a fix for a regression that occured with conf fetching, where the entity UUID was not properly pulled in to the `get_entity` function.
N/A
- confirmed visualizations broke with portal-vis 0.3.3 locally
- applied fix to portal-vis and bumped version
- Confirmed visualizations fixed with portal-vis 0.3.4
Python environment issues led to this - my local environment did not update to 0.3.3 successfully when originally QA testing this, so I mistakenly thought it was all set.

Hotfix portal-visualization regression

---

CHANGELOG-portal-vis-0.3.6.md
context/requirements.in
context/requirements.txt

This PR fixes the remaining regression issue from portal-viz 0.3.3-0.3.5, where the visualizations for image pyramids failed to visualize due to the `get parent entity` lookup function being inconsistently passed either a string or an object containing a uuid key; this has been resolved upstream.
Link to any design documents, diagrams, or JIRA tickets relevant to this feature.
Tested manually with datasets that failed in `portal-prod.test` environment.

NickAkhmetov/Fix portal-visualization image pyramid regression

---

CHANGELOG-scrolling-accessibility-issue
context/app/static/js/components/detailPage/MetadataTable/MetadataTable.tsx

Addresses the accessibility issue `ensure elements with scrollable content are accessible by keyboard` in the metadata table included in the donor/sample/dataset pages.
[CAT-1067](https://hms-dbmi.atlassian.net/browse/CAT-1067)
Manually tested with Axe devTool
[CAT-1067]: https://hms-dbmi.atlassian.net/browse/CAT-1067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Addressed the issue in metadata table

---

CHANGELOG-add-manifest-success-alert.md
context/app/static/js/components/bulkDownload/BulkDownloadSuccessAlert.tsx
context/app/static/js/components/bulkDownload/hooks.ts
context/app/static/js/components/detailPage/BulkDataTransfer/BulkDataTransferSection.tsx
context/app/static/js/components/detailPage/derivedEntities/DerivedEntitiesSection/DerivedEntitiesSection.tsx
context/app/static/js/components/search/Search.tsx
context/app/static/js/stores/useBulkDownloadStore.ts

Adds informative alert upon successful bulk download manifest downloads. This alert is present wherever bulk download options are available.
[CAT-1084 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-1084?atlOrigin=eyJpIjoiMGQwNDM2YTU2YjlkNGE2NDhjZDNkNGQ3ZDRiOTI4NWYiLCJwIjoiaiJ9)
Search page:
Bulk Data Transfer section:
Derived Data section:

Austenem/CAT-1084 Add manifest success alert

---

CHANGELOG-refactor-ingest-metadata.md
context/app/static/js/components/detailPage/ProcessedData/ProcessedDataset/ProcessedDataset.tsx
context/app/static/js/components/detailPage/ProcessedData/ProcessedDataset/hooks.ts
context/app/static/js/components/detailPage/files/DataProducts/hooks.ts
context/app/static/js/components/search/Results/utils.ts
context/app/static/js/components/searchPage/ResultsTable/utils.jsx
context/app/static/js/components/types.ts
context/app/static/js/helpers/metadata.ts
context/app/static/js/pages/Dataset/hooks.ts
context/app/static/js/pages/search/DevSearch.jsx

Updates the portal to account for refactored metadata from search api.
The relevant search-api changes include:
`Dataset.ingest_metadata.metadata` → `Dataset.metadata`
`Dataset.ingest_metadata.files` → `Dataset.files`
`Dataset.metadata` → `Dataset.ingest_metadata`
[CAT-966 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-966?atlOrigin=eyJpIjoiNzAwOTVlNDQyNmViNDgxNjg1MDhmZmFjM2VhZTIyZmIiLCJwIjoiaiJ9)
Checked detail pages and in particular metadata sections from several entities.

Austenem/CAT-966 Refactor ingest metadata

---

CHANGELOG-fix-processed-analysis.md
context/app/static/js/components/detailPage/ProcessedData/ProcessedDataset/ProcessedDataset.tsx
context/app/static/js/pages/Dataset/hooks.ts

Update processed dataset files and analysis sections to match updated ingest metadata.
Previously:
- Files section intermittently produced runtime error in cases where the files property was absent.
- Analysis section did not appear when expected.
[CAT-1086 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-1086?atlOrigin=eyJpIjoiNjRiMmQzYzE5NzJhNDZkMmI4Y2FiNzNiYTc5MzI4ODUiLCJwIjoiaiJ9)
Local:
On TEST:

Austenem/CAT-1086 Fix processed dataset sections

---

CHANGELOG-fix-push-early-return.md
etc/build/push.sh

- Fix issue in push script where if the number of days since the last release is 0 the script returns early.

John conroy/fix push early return

---

CHANGELOG-ws-token-for-users.md
context/app/routes_auth.py

- Only request workspaces token for workspaces users during auth routine. This will unblock Juan's work for discovering users when sharing workspaces.

John conroy/ws token for users

---

CHANGELOG-dev-metadata-filter.md
context/app/static/js/pages/search/DevSearch.jsx

Fixes "No metadata?" filter on dev-search.
[CAT-1090 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-1090?atlOrigin=eyJpIjoiNjU1NDM4ZWJmZWFhNGNjMzg2NDIwNjRkYjkyOTMzMmIiLCJwIjoiaiJ9)
Local:
Test:

Austenem/CAT-1090 Dev-search metadata filter

---

CHANGELOG-fix-prov-for-datasets-without-descendants.md
context/app/static/js/components/detailPage/provenance/hooks.ts

Zhou noticed an issue while testing provenance changes where some datasets did not show the provenance graph.
This PR fixes the provenance graph for datasets without descendants.

John conroy/fix prov for datasets without descendants

---

CHANGELOG-homepage-updates.md
context/app/static/js/components/home/Hero/const.tsx

This PR adds the news items related to the implementation of the bulk download manifest creator and the scfind/cellpop templates.
https://hms-dbmi.atlassian.net/wiki/spaces/GL/pages/3536748545/Homepage+Latest+Changes+Entries

NickAkhmetov/CAT-1072 Add news items to homepage changes list

---

CHANGELOG-marker-gene-fix.md
context/app/routes_browse.py

This PR fixes a regression observed when navigating from the biological query results, where a marker gene is provided as part of the URL params. Due to the logic to redirect to the unified primary dataset page not explicitly including the marker param, this param has been getting dropped since the implementation of unified views.
https://hms-dbmi.atlassian.net/browse/CAT-1073
Locally tested by following reproduction steps in original ticket.

NickAkhmetov/CAT-1073 Keep the `marker` URL param during redirect to unified view

---

CHANGELOG-check-for-missing-symlinks.md
context/app/static/js/helpers/functions.ts

Adds checks before trying to access a workspace's symlinked files (resolves 2023 workspaces API bug that resulted in malformed workspaces with empty `current_workspace_details` objects).
[CAT-1118 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-1118?atlOrigin=eyJpIjoiOTU3NmNkNDY5ZjI3NDkxOWI5NDdkYTU3YzgyNjAyYzEiLCJwIjoiaiJ9)
Was able to reproduce the original error by calling `isWorkspaceAtDatasetLimit` on a workspace with a manually deleted `current_workspace_details` object, and used the same method to confirm that the issue was resolved by this fix.

Austenem/CAT-1118 Check for missing symlinks

---

CHANGELOG-add-sample-workspace-banner.md
context/app/static/js/pages/Template/Template.tsx

Adds an info banner to template pages without sample workspaces.
[CAT-1085 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-1085?atlOrigin=eyJpIjoiZGY3MTFkZmUzNGI2NGRkMzg3ZTdkNDA3MWFjNWU1MWYiLCJwIjoiaiJ9)
Local:
Prod:

Austenem/CAT-1085 Add sample workspace banner

---

CHANGELOG-cellpop-fixes.md
context/app/static/js/components/organ/CellPop/CellPopDescription.tsx
context/package-lock.json
context/package.json

This PR contains fixes for several cellpop issues which were identified during QA testing.
https://hms-dbmi.atlassian.net/browse/CAT-1122
https://hms-dbmi.atlassian.net/browse/CAT-1123
https://hms-dbmi.atlassian.net/browse/CAT-1125
https://hms-dbmi.atlassian.net/browse/CAT-1126
Manually tested.
CAT-1122 - fixed Azimuth link, removed period from inside link.
The other fixes were made upstream and published in cellpop 0.0.8.
CAT-1123 - Fixed cellpop crash which occured from changing row visibility while another row is expanded. Also implemented behavior to control expand/hide behavior:
* Expanding a hidden row now marks the row as visible
* Hiding an expanded row now collapses the row
https://github.com/user-attachments/assets/007b4763-97be-4d03-befb-c9613ca088a2
CAT-1125 - Fixed `Heatmap …

NickAkhmetov/CAT-1122, CAT-1123, CAT-1125, CAT-1126 Cellpop Fixes

---

CHANGELOG-even-more-cellpop-fixes.md
context/package-lock.json
context/package.json

This PR fixes more cellpop issues identified during QA. These fixes were all made upstream in the cellpop repo: https://github.com/hms-dbmi/cellpop/pull/61/files/c40d27ad973107909b419946667d013fa3e6a761..1afd50d044a915b81cf720742ffddd5e934ffe76
https://hms-dbmi.atlassian.net/browse/CAT-1126
https://hms-dbmi.atlassian.net/browse/CAT-1129
https://hms-dbmi.atlassian.net/browse/CAT-1130
Manual testing
CAT-1126 - fixed overlap between expanded bar chart scale and violins/bars when there were few rows
CAT-1129 - fixed background color for heatmap normalization label
CAT-1130 - prevent scrolling while plot controls modal is open
Additionally, the expanded bar chart now displays normalized data.

NickAkhmetov/CAT-1126, CAT-1129, CAT-1130, More cellpop fixes

---

CHANGELOG-fix-protected-datasets-bug.md
context/app/static/js/hooks/useProtectedDatasets.tsx

Fix bug allowing non-public datasets to be added to workspaces.
[CAT-1074 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-1074?atlOrigin=eyJpIjoiYWU3YjM3ODQ5ZDM0NDk3MWI2NzhmMjQ3ZjgzYWRmZTIiLCJwIjoiaiJ9)
Tested by attempting to add various combinations of public and non-public datasets from the search page to a workspace.

Austenem/CAT-1074 Fix protected datasets bug

---

CHANGELOG-organ-page-fixes.md
context/app/organ/fallopian-tube.yaml
context/app/organ/ovary.yaml
context/app/organ/urinary-bladder.yaml
context/app/routes_file_based.py
context/app/utils.py
context/package-lock.json
context/package.json

This PR fixes a few issues all related to the organ page:
* The `urinary bladder` page now includes `bladder` datasets
* The `ovary` and `fallopian tube` pages now include appropriate search terms for handling laterality, i.e. they now include the left/right ovary and fallopian tube datasets, respectively.
* Queries for organ information against the portal UI back-end now accept search terms as synonyms for the main term for lookup purposes, which should fix icon lookup issues for organ icons whose common names do not match their full anatomical names (e.g. bladder and urinary bladder).
* Updates cellpop so that the control drawer is drawn under the HuBMAP appbar.
Fallopian tube/ovary/bladder datasets missing from organ page: https://hms-dbmi.atlassian.net/browse/CAT-1111
Missing organ …

NickAkhmetov/CAT-1111, CAT-965, CAT-1148 Organ Page Fixes

---

CHANGELOG-add-my-lists-metrics.md
context/app/static/js/components/detailPage/entityHeader/EntityHeaderActionButtons/EntityHeaderActionButtons.tsx
context/app/static/js/components/detailPage/summary/SummarySaveEntityButton/SummarySaveEntityButton.tsx
context/app/static/js/components/organ/Samples/Samples.tsx
context/app/static/js/components/savedLists/SaveEntitiesButton/SaveEntitiesButton.tsx
context/app/static/js/components/savedLists/SaveEntitiesButtonFromSearch/SaveEntitiesButtonFromSearch.tsx
context/app/static/js/components/savedLists/SaveToListDialog/SaveToListDialog.tsx
context/app/static/js/components/savedLists/SavedListsDescription/SavedListsDescription.tsx
context/app/static/js/components/savedLists/constants.ts
context/app/static/js/components/savedLists/hooks.ts
context/app/static/js/components/savedLists/types.ts

Adds metrics for the "My Lists" feature.
[CAT-1113 Jira ticket ](https://hms-dbmi.atlassian.net/browse/CAT-1113?atlOrigin=eyJpIjoiY2QwODFjMDQ1NzE3NDA3ZGIzNjY2Yjk2NmEwZTcwMWEiLCJwIjoiaiJ9)
Tested using Matomo and event logging.

Austenem/CAT-1113 Add list metrics

---

CHANGELOG-fix-search-menu-styles.md
context/app/static/js/components/workspaces/NewWorkspaceDialog/NewWorkspaceDialogFromSelections.tsx
context/app/static/js/components/workspaces/WorkspacesDropdownMenu/WorkspacesDropdownMenu.tsx

- Update search page menu styles.
Tiffany asked that all menus be outlined outside of the tile sort dropdown. I've also updated the icons in the workspaces menu to be primary in color.

John conroy/fix search menu styles CAT-762

---

CHANGELOG-restrict-lists-to-hubmap.md
context/app/static/js/components/detailPage/entityHeader/EntityHeaderActionButtons/EntityHeaderActionButtons.tsx
context/app/static/js/components/detailPage/summary/SummarySaveEntityButton/SummarySaveEntityButton.tsx
context/app/static/js/components/savedLists/NoItemsSaved/NoItemsSaved.tsx
context/app/static/js/components/savedLists/SaveEntitiesButton/SaveEntitiesButton.tsx
context/app/static/js/components/savedLists/SavedListsDescription/SavedListsDescription.tsx
context/app/static/js/components/savedLists/api.ts
context/app/static/js/pages/SavedLists/SavedLists.tsx

Restricts "My Lists" feature from all logged-in users to HuBMAP users in accordance with current restrictions on UKV API authentication.
[CAT-1180 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-1180?atlOrigin=eyJpIjoiNzcyYjhmMjliNTYwNDg3YWJiMzkyNGQzNzllM2FkMTMiLCJwIjoiaiJ9)

Austenem/CAT-1180 Restrict lists to HuBMAP users

---

CHANGELOG-fix-blood-chart-casing.md
context/app/static/js/pages/Diversity/DonorChart.jsx

- Fix casing of ABO blood group chart titles on diversity page.

John conroy/fix blood chart casing CAT-1179

---

CHANGELOG-cat-1119.md
context/app/routes_browse.py
context/app/static/js/components/Contexts.tsx
context/app/static/js/components/detailPage/BulkDataTransfer/BulkDataTransferSection.tsx
context/app/static/js/components/detailPage/DatasetRelationships/DatasetRelationships.tsx
context/app/static/js/components/detailPage/ProcessedData/ProcessedDataset/hooks.ts
context/app/static/js/components/detailPage/entityHeader/EntityHeaderActionButtons/EntityHeaderActionButtons.tsx
context/app/static/js/components/detailPage/multi-assay/MultiAssayRelationship/MultiAssayRelationship.tsx
context/app/static/js/components/detailPage/multi-assay/MultiAssayRelationship/index.ts
context/app/static/js/components/detailPage/multi-assay/RelatedMultiAssayLinks/RelatedMultiAssayLinks.tsx
context/app/static/js/components/detailPage/multi-assay/SnareSeq2Alert/SnareSeq2Alert.tsx
context/app/static/js/components/detailPage/multi-assay/SnareSeq2Alert/index.ts
context/app/static/js/components/detailPage/multi-assay/hooks.ts
context/app/static/js/components/detailPage/multi-assay/useRelatedMultiAssayDatasets.ts
context/app/static/js/components/detailPage/provenance/ProvTabs/ProvTabs.tsx
context/app/static/js/pages/Dataset/Dataset.tsx
context/app/static/js/pages/Dataset/hooks.ts
context/app/utils.py

This PR implements changes to the detail page to provide more information to users when they are viewing multi-assay datasets, particularly SnareSeq2. We are restoring the text-based "multi assay relationship" section and are now displaying component datasets in the bulk data transfer tabs.
https://hms-dbmi.atlassian.net/browse/CAT-1119
<details><summary>Full page screenshot</summary>
<p>
</p>
</details>

NickAkhmetov/CAT-1119 SnareSeq2/Multi-Assay Changes

---

CHANGELOG-add-data-products-tracking.md
context/app/static/js/components/organ/DataProducts/DataProducts.tsx
context/app/static/js/components/organ/ViewEntitiesButton.tsx
context/app/static/js/pages/Organ/Organ.tsx
context/app/static/js/pages/Organ/hooks.ts

Adds event tracking for data products sections on organ pages.
[CAT-1234 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-1234?atlOrigin=eyJpIjoiZDM1OWI0YzNiYzk5NDEyNDg2ZWFiNTU0Zjk2ZmQ0MjQiLCJwIjoiaiJ9)
[Trackable organ page events](https://docs.google.com/spreadsheets/d/18hF0VDrepN58GiDX22_jJ6vsnfGwKE_GiL8hdD_Art4/edit?gid=126226029#gid=126226029)
Tested by logging formatted events in `trackEvent`.
Ex: `{category: "Organ Detail Page: Data Products", action: "Data Products / Download Raw", label: "Kidney Laterality: right Assay: rna-seq File: RK_raw.h5ad", name: "Kidney Laterality: right Assay: rna-seq File: RK_raw.h5ad"}`

Austenem/CAT-1234 Add data products tracking

---

CHANGELOG-update-portal-viz.md
context/requirements.in
context/requirements.txt

This PR updates the portal-container to fix the scaling issue for the Visium datasets.
[CAT-1206](https://hms-dbmi.atlassian.net/browse/CAT-1206)
Manually tested for the datasets.
[CAT-1206]: https://hms-dbmi.atlassian.net/browse/CAT-1206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Updated portal-viz version

---

CHANGELOG-remove-contributors-sorting.md
context/app/static/js/components/detailPage/ContributorsTable/ContributorsTable.tsx
context/app/static/js/components/detailPage/ContributorsTable/utils.ts

Lists publication contributors in original author order.
[CAT-1199 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-1199?atlOrigin=eyJpIjoiNzY4NGZhZDg5OGJkNGM2MmE5ZDlhMDhmODk2ZjY2ZmUiLCJwIjoiaiJ9)
Checked that contributor tables on publication pages match original author order. On dataset detail pages, contributor order is often already provided in alphabetical order by last name.
Local:
Prod:
Verify that we are also removing sorting for dataset and collection detail pages, which do not always list contributors in order of most->least contribution as is the norm for publications.

Austenem/CAT-1199 Remove contributors sorting

---

CHANGELOG-add-admin-banner.md
context/app/static/js/components/Header/Header/Header.tsx
context/app/static/js/components/Header/HeaderAppBar/style.ts

Add admin banner to top of portal header.
[CAT-1241 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-1241?atlOrigin=eyJpIjoiZjgwMjQxN2Y2NTE1NDhkN2FmNjVkZDNkNDU1NDJmMjgiLCJwIjoiaiJ9)

Austenem/CAT-1241 Add admin banner

---

CHANGELOG-hide-shiny-app-links.md
context/app/static/js/components/organ/DataProducts/DataProducts.tsx

Hides links to Shiny apps in organ data products if unavailable.
[CAT-1242 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-1242?atlOrigin=eyJpIjoiZDUyMzIzNGY1MTkzNGUxY2EzODk5OWMzNWE0MjYzODEiLCJwIjoiaiJ9)

Austenem/CAT-1242 Hide Shiny app links

---

CHANGELOG-revert-portal-viz
context/requirements.in
context/requirements.txt

This PR reverts the portal-viz version update done to fix the scalability issue with visium datasets.
[CAT-1206](https://hms-dbmi.atlassian.net/browse/CAT-1206)
Manually performed on the visium datasets.
[CAT-1206]: https://hms-dbmi.atlassian.net/browse/CAT-1206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Rolled back portal-viz version update

---

CHANGELOG-easy-hierarchical-links.md
context/app/static/js/components/search/Facets/FilterChips.tsx
context/app/static/js/components/search/utils.ts

The team working on the ingest portal needs to easy link to the search page with hierarchical facets selected. This PR enables easy links to the search page with hierarchical facets selected.
The child terms won't all be selected, but this is a quick start.

John conroy/easy hierarchical links

---

.github/workflows/python-ci.yml
CHANGELOG-workspace-sharing-fixes.md
context/app/static/js/components/workspaces/ConfirmDeleteInvitationDialog/ConfirmDeleteInvitationDialog.tsx
context/app/static/js/components/workspaces/Tables/WorkspaceItemsTable/components/TableContent.tsx
context/app/static/js/components/workspaces/Tables/WorkspaceItemsTable/style.ts

Fixes dialog text in the "delete shared workspace invitation" dialog (which named the sharer instead of the sharee), and fixes the checkbox header styling on the workspace landing page.
[CAT-1254 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-1254?atlOrigin=eyJpIjoiOGI2Y2M0NDMyMDcxNDUxZThhYWM3OWM4YjRhNGEzODAiLCJwIjoiaiJ9)
Aligned checkbox header
Corrected dialog text

Austenem/CAT-1254 Workspace sharing fixes

---

CHANGELOG-search-by-publication.md
context/app/static/js/components/search/Facets/ExistsFacet.tsx
context/app/static/js/components/search/fieldConfigurations.ts
context/app/static/js/components/search/utils.ts
context/app/static/js/pages/search/S.tsx

Adds a facet to dataset search page to filter datasets to only those linked to a publication (alternate approach to the search-api update now that the collections edge case will be removed).
[CAT-1260 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-1260?atlOrigin=eyJpIjoiOTAwN2RlMGZhNDliNGZmN2I1YjkzNDlkYjY2ZDkwNzQiLCJwIjoiaiJ9)

Austenem/CAT-1260 Search by publication

---

CHANGELOG-cat-1277.md
context/app/static/js/components/cells/MolecularDataQueryForm/AutocompleteEntity/hooks.ts

This PR adjusts the condition for the effect which updates the set of genes to fetch when querying with a selected gene pathway or deselecting a pathway, as this effect should not run while the form is in a submitted state.
This should fix the regression which causes the query not to run.
https://hms-dbmi.atlassian.net/browse/CAT-1277
https://github.com/user-attachments/assets/f5e9da9f-94be-430d-bea1-925512f0f1ab

NIckAkhmetov/CAT-1277 Fix gene pathways effect causing molecular data queries to fail

---

CHANGELOG-cat-1106.md
context/app/static/js/api/scfind/useLabelToCLID.ts
context/app/static/js/components/Routes/Routes.jsx
context/app/static/js/components/organ/Azimuth/ReferenceBasedAnalysis.tsx
context/app/static/js/components/organ/OrganCellTypes/CellTypes.tsx
context/app/static/js/components/organ/OrganCellTypes/CellTypesTable.tsx
context/app/static/js/components/organ/OrganCellTypes/CellTypesTableCells.tsx
context/app/static/js/components/organ/OrganCellTypes/IndexedDatasetsSummary.tsx
context/app/static/js/components/organ/OrganCellTypes/hooks.ts
context/app/static/js/components/organ/OrganCellTypes/index.ts
context/app/static/js/components/organ/OrganCellTypes/styles.ts
context/app/static/js/components/organ/OrganCellTypes/types.ts
context/app/static/js/components/organ/hooks.ts
context/app/static/js/components/organ/types.ts
context/app/static/js/hooks/useUBKG.ts
context/app/static/js/pages/Organ/Organ.tsx
context/app/static/js/pages/Organ/hooks.ts
context/app/static/js/shared-styles/charts/ChartWrapper/ChartWrapper.tsx
context/app/static/js/shared-styles/icons/sectionIconMap.ts
context/app/static/js/shared-styles/sections/Description/Description.tsx
context/app/static/js/shared-styles/sections/Description/style.ts
context/app/static/js/shared-styles/tables/EntitiesTable/EntityTable.tsx
context/app/static/js/shared-styles/tables/EntitiesTable/EntityTableHeaderCell.tsx
context/app/static/js/shared-styles/tables/ExpandableRow/ExpandableRow.tsx
context/app/static/js/shared-styles/tables/columns.tsx

This PR
* Resolves some minor sitewide issues which clogged the console (e.g. complaints about using default values with proptypes instead of using the built-in JS functionality, missing keys where they were necessary, extraneous keys where they were not needed)
* Adds the Cell Types section/table to the organ page
* Adds the ability to reverse the existing `ExpandableRow` component
* Moves the entity table header cell functionality into its own component/file for reuse
* Fixes a minor issue with entity table ID cells displaying empty parentheses for non-dataset entities
https://hms-dbmi.atlassian.net/browse/CAT-1106
https://hms-dbmi.atlassian.net/browse/CAT-1169
* local testing with kidney/lung organ pages

NickAkhmetov/CAT-1106 Add Cell Types table to organ page

---

CHANGELOG-gene-detail-page-fixes.md
context/app/static/js/components/genes/CellTypes/GeneCellTypes.tsx
context/app/static/js/components/genes/Summary/Summary.tsx
context/app/static/js/components/genes/constants.ts
context/app/static/js/pages/Genes/Genes.tsx

This PR fixes CAT-1285, CAT-1286, and CAT-1287 after minor issues with the gene detail page implementation were surfaced during QA. 
https://hms-dbmi.atlassian.net/browse/CAT-1285
https://hms-dbmi.atlassian.net/browse/CAT-1286
https://hms-dbmi.atlassian.net/browse/CAT-1287
Manual testing
Restored summary section:
No more `other` cells in table:
Correct link from `biomarkers` button: 
- [ x New `CHANGELOG-your-feature-name-here.md` is present in the root directory, describing the change(s) in full sentences.

NickAkhmetov/Gene Detail Page Fixes

---

CHANGELOG-Workspaces-sharing-dialog-typo.md
context/app/static/js/components/workspaces/ShareWorkspacesDialog/ShareWorkspacesDialog.tsx

Fix minor typo on Workspaces Sharing dialog to change 'copy of the workspace at it exists' to 'copy of the workspace as it exists'.
[CAT-1295](https://hms-dbmi.atlassian.net/browse/CAT-1295)
Manual test.
- [x ] Code follows the project's coding standards
- [ x] Lint checks pass locally
- [x ] New `CHANGELOG-your-feature-name-here.md` is present in the root directory, describing the change(s) in full sentences.
- [x ] Unit tests covering the new feature have been added
- [x ] All existing tests pass
- [x ] Any relevant documentation in JIRA/Confluence has been updated to reflect the new feature
- [x ] Any new functionalities have appropriate analytics functionalities added
None
[CAT-1295]: https://hms-dbmi.atlassian.net/browse/CAT-1295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5Y …

CAT-1295: Fixes typo on Workspaces Sharing dialog

---

CHANGELOG-add-init-workspace-state.md
context/app/static/js/components/workspaces/statusCodes.ts
context/app/static/js/shared-styles/icons/workspaceStatusIconMap.ts

Adds support for new "initializing" workspace state.
[CAT-1298 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-1298?atlOrigin=eyJpIjoiM2Y4NmQyNDI2NmQxNDA0OTlkNWI0MmJkNzNiYTMwNDMiLCJwIjoiaiJ9)

Austenem/CAT-1298 Add init workspace state

---

CHANGELOG-add-data-permissions.md
CHANGELOG-fix-data-products.md
context/app/static/js/components/bulkDownload/BulkDownloadDialog/BulkDownloadDialog.tsx
context/app/static/js/components/bulkDownload/hooks.ts
context/app/static/js/components/detailPage/ProcessedData/ProcessedDataWorkspaceMenu.tsx
context/app/static/js/components/workspaces/AddDatasetsFromSearchDialog/hooks.ts
context/app/static/js/components/workspaces/AddDatasetsTable/hooks.ts
context/app/static/js/components/workspaces/NewWorkspaceDialog/NewWorkspaceDialogFromSelections.tsx
context/app/static/js/components/workspaces/NewWorkspaceDialog/useCreateWorkspaceForm.ts
context/app/static/js/components/workspaces/formHooks.ts
context/app/static/js/hooks/useDatasetPermissions.tsx
context/app/static/js/hooks/useRestrictedDatasets.tsx
context/app/static/js/pages/Organ/hooks.ts
context/app/static/js/shared-styles/tables/columns.tsx

Checks a user's access to specific datasets for workspace and bulk download operations using new ingest api access endpoint (which is now on PROD).
Many changes involve removing the previous warning messages that were applied to any action involving protected datasets, as the new endpoint is a single source of truth about whether the user has access to a given dataset.
[CAT-1311 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-1311?atlOrigin=eyJpIjoiOGE0NWI5Y2IyNjIzNDIzNWE2ZmUzOTY5ZDZlYjYyN2YiLCJwIjoiaiJ9)
Tested by going through workspace and bulk download dialog user flows with both restricted and non-restricted datasets.
Bulk download dialog:
Workspace dialog:

 Austenem/CAT-1311 Add data permissions

---

CHANGELOG-organs.md
context/app/organ/bronchus.yaml
context/app/organ/lung.yaml
context/app/static/js/components/organ/Assays/Assays.tsx
context/app/static/js/components/organ/OrganDatasetsChart/OrganDatasetsChart.tsx
context/app/static/js/shared-styles/charts/ChartWrapper/ChartWrapper.tsx

This PR adds missing search terms to ensure that all lateral organs' data is included on organ pages.
It also fixes the display of the assays graph on the organs page
https://hms-dbmi.atlassian.net/browse/CAT-1337
Checked organ pages after updating yamls.

CAT-1337 NickAkhmetov/Fix disparities with organ page data inclusion

---

CHANGELOG-scfind-fixes.md
context/app/static/js/api/scfind/useLabelToCLID.ts
context/app/static/js/components/Header/staticLinks/staticLinks.tsx
context/app/static/js/components/biomarkers/BiomarkersPanelItem.tsx
context/app/static/js/components/biomarkers/BiomarkersPanelList.tsx
context/app/static/js/components/biomarkers/BiomarkersSearchContext.tsx
context/app/static/js/components/cell-types/CellTypesBiomarkersTable.tsx
context/app/static/js/components/cell-types/CellTypesDistribution/MultiOrganCellTypesDistributionChart.tsx
context/app/static/js/components/cell-types/CellTypesDistribution/hooks.ts
context/app/static/js/components/cell-types/CellTypesDistribution/index.tsx
context/app/static/js/components/cells/CellsCharts/CellTypesChart.tsx
context/app/static/js/components/cells/DatasetsOverview/DatasetsOverview.tsx
context/app/static/js/components/cells/MolecularDataQueryForm/AutocompleteEntity/AutocompleteEntity.tsx
context/app/static/js/components/cells/SCFindResults/SCFindCellTypeQueryResults.tsx
context/app/static/js/components/genes/Summary/Summary.tsx
context/app/static/js/components/home/Hero/const.tsx
context/app/static/js/pages/Biomarkers/Biomarkers.tsx
context/app/static/js/pages/Cells/Cells.tsx
context/app/static/js/shared-styles/charts/VerticalStackedBarChart/VerticalStackedBarChart.tsx
context/app/static/js/shared-styles/tables/EntitiesTable/EntityTableHeaderCell.tsx

Consolidating a few small closely related items into one PR.
* CAT-1322 Cell type landing page bars lead to cell type detail page on click
* Added links to target cell types.
* CAT-1323 Handle mismatch between scFind-indexed and UBKG-indexed genes
* Added handling for genes without a description. Was not able to reproduce cases where the description re-attempts to load after failing. Related design ticket for genes without scFind-indexed data (CAT-1330) is in progress.
* CAT-1324 Add tooltips to biomarkers table column headers on cell type detail page
* Took the opportunity to also get rid of the hacky workaround I had originally implemented before finding out that TableSortLabel exists.
* CAT-1326 Fix icon for cell type search tab
* CAT-1327 Add bottom margin to expanded cell type row …

NickAkhmetov/SCFind Fixes 

---

CHANGELOG-scfind-id-adapter.md
context/app/static/js/api/scfind/useSCFindIDAdapter.ts
context/app/static/js/components/cell-types/hooks.tsx
context/app/static/js/components/cells/CellsCharts/CellTypesChart.tsx
context/app/static/js/components/cells/CellsCharts/SCFindGeneCharts.tsx
context/app/static/js/components/cells/CellsCharts/hooks.ts
context/app/static/js/components/cells/DatasetsOverview/hooks.ts
context/app/static/js/components/cells/SCFindResults/SCFindCellTypeQueryResults.tsx
context/app/static/js/components/cells/SCFindResults/SCFindGeneQueryResults.tsx
context/app/static/js/components/cells/SCFindResults/columns.tsx
context/app/static/js/components/genes/CellTypes/GeneCellTypes.tsx
context/app/static/js/components/organ/OrganCellTypes/IndexedDatasetsSummary.tsx
context/app/static/js/pages/Organ/hooks.ts

This PR aims to support scFind queries with both HuBMAP IDs and UUIDs.
Getting the inputs to work dynamically as well will require additional effort to track which index is currently being queried against, so I will leave some related todos/make tickets to resolve them.
This is a hotfix for an issue which developed with the last scFind index deploy. A follow-up ticket to handle the inputs has been created: https://hms-dbmi.atlassian.net/browse/CAT-1339 
Manually testing each page with scFind-derived elasticsearch queries (cell types, cell type details, genes, gene details, molecular queries for cell types and genes).
scFind stories will also be updated as part of CAT-1339.

NickAkhmetov/Support scFind results with both UUID and HBM ID outputs

---

CHANGELOG-cat-1345.md
context/app/static/js/components/cells/SCFindResults/columns.tsx
context/app/static/js/components/organ/Samples/Samples.tsx
context/app/static/js/shared-styles/tables/EntitiesTable/EntityTable.tsx
context/app/static/js/shared-styles/tables/EntitiesTable/EntityTableHeaderCell.tsx
context/app/static/js/shared-styles/tables/EntitiesTable/types.ts
context/app/static/js/shared-styles/tables/columns.tsx
context/app/static/js/typings/search.ts

This PR adds fixed widths which are applied to infinite scroll table columns when viewed in a large viewport. This prevents the columns from being resized as the user scrolls through the entity list. The `width` prop is optional and can be omitted when defining a column.
I found that the organ page had some free space available with these sizing adjustments in place; after confirming with Tiffany, I added the `Anatomy` column to the organ page's list of samples to provide more biological context for each sample.
https://hms-dbmi.atlassian.net/browse/CAT-1345
Tested on molecular data query page, organ page, and cell/gene pages.
https://github.com/user-attachments/assets/646b4301-4ca3-45c6-9e90-9ed9110a7473

NickAkhmetov/CAT-1345 Set fixed widths for columns to prevent jittering on scroll

---

CHANGELOG-cat-1344.md
context/app/static/js/components/cells/DatasetsOverview/DatasetsOverviewChart.tsx
context/app/static/js/shared-styles/charts/ChartWrapper/ChartWrapper.tsx
context/app/static/js/shared-styles/charts/StackedBar/StackedBar.tsx

This PR updates the dataset overview chart to display "matched" values with stripes instead of using completely different colors for the matched and unmatched segments of each bar.
https://hms-dbmi.atlassian.net/browse/CAT-1344
Manually tested, including PNG export functionality.
I also improved the sizing for the legend to be less squished.

NickAkhmetov/CAT-1344 Display dataset overview chart with stripes to indicate matched status

---

CHANGELOG-cat-1391.md
context/app/static/js/components/cell-types-landing/CellTypesPanelItem.tsx
context/app/static/js/components/cell-types-landing/CellTypesSearchContext.tsx

This PR adjusts the logic for the organs filter on the cell type search page.
* The existing approach shows all organs as selected in the dropdown if no organs are selected. This makes the functionality of the select all/deselect all buttons unclear. 
* The updated approach only displays the checkmarks next to selected organs. The clarity for the "no organs selected" case not applying any filtering is maintained by using the `filterIsInactive` state as one of the options for whether to color the text as primary or secondary.
* Filter clarity is further enhanced by setting the color for non-selected organs to `text.disabled` instead of `text.primary`.
https://hms-dbmi.atlassian.net/browse/CAT-1391
Manually tested by applying various combinations of filters.
No organs selected:
All organs …

NickAkhmetov/CAT-1391 Improve organ filter clarity

---

CHANGELOG-cat-1408-1409.md
context/app/static/js/components/cells/DatasetsOverview/DatasetsOverviewChart.tsx
context/app/static/js/components/cells/DatasetsOverview/hooks.ts
context/app/static/js/components/genes/CellTypes/GeneCellTypes.tsx
end-to-end/cypress/e2e/portal/pages/genes.cy.js

This PR:
* Fixes the dataset overview chart not showing the `unmatched` data in the comparison
* Adds a link to the scfind documentation to the dataset overview chart caption
* Fixes the missing "organs" list on the indexed datasets summary of the gene page
https://hms-dbmi.atlassian.net/browse/CAT-1408
https://hms-dbmi.atlassian.net/browse/CAT-1409
Manually tested to confirm functionality is restored, added cypress tests for basic gene page functionalities.
<details><summary>Dataset Overview Chart Fixes</summary>
<p>
with comparison turned off:
with comparison turned on:
with comparison turned on/percentage enabled:
with comparison turned on/compare to all enabled:
with comparison turned on/compare to all and percentage mode enabled:
</p>
</details> 
<details><summary>Fixed gene page …

NickAkhmetov/CAT-1408 CAT-1409 Datasets Overview Chart Fixes
